# Bollinger Band Reversal (BBR)

## Import Libs

In [3]:
import pandas as pd 
import numpy as np
import os
from pandas import DataFrame, Series
import plotly.graph_objects as go

## Functions

### Get FE Data

In [1]:
def get_fe_price_data(
        filename: str = "../output/FE_V2_GBPUSD_15mins_1yr_End_20250311.csv"
        ) -> DataFrame:
    """
    Return the FE price data as a DatetimeIndexed 
    DataFrame set to US/Eastern TZ
    """
    PATH = os.getcwd()
    df = pd.read_csv(filename)
    df["Date"] = pd.DatetimeIndex(df["Date"], tz="US/Eastern")
    df.set_index("Date", inplace=True)
    return df

### Simulate Short Positions (Range-Based)

In [188]:
def range_short_gains(
        df: Series, 
        high: Series, 
        low: Series,
        close: Series,
        signal_name: str,
        sl_pct_range: int,
        tp_pct_range: int,
        range_type: str = "ADR"
        ):
    """Get the pip gain and apply to df"""

    win = 0
    loss = 0
    target_pips = 0 
    sl_pips = 0
    gain = 0
    trade_start =  None
    trade_end = None
    
    if df[signal_name] is True:
        idx = int(df["Idx"])
        iday_idx = int(df["Iday_Idx"])
        # get signal start of fx day timestamp
        day_start_ts = high.iloc[idx-iday_idx:idx-iday_idx+1].index[0]
        OFFSET = day_start_ts + pd.DateOffset(days=1) # end of signal's fx day
        START = df.name # signal start time
        TD = pd.Timedelta(minutes=15)
        END = OFFSET - TD # 17:00 on the signals fx day

        # get stop loss time:
        sl_window = high.loc[START+TD:END] # from signal idx+1 to EOD
        close_window = close.loc[START+TD:END] # from signal idx+1 to EOD
        stop = False # update if stopped 
        sl_ts = None # get timestamp when stopped out

        for i in range(len(sl_window)): 
            if sl_window.iloc[i] >= (df["Close"] + df[range_type] * sl_pct_range ):
                stop = True # trade hit stop loss
                # get stop loss timestamp
                sl_ts = sl_window.iloc[i:i+1].index[0] 
                break
        # if not stopped out then the stop window is signal:EOD
        # don't include trade if it is the last candle of the day
        if stop is False:
            if close_window.empty is False:
                sl_ts = close_window.iloc[-1:].index[0]
            else:
                sl_ts = START+TD
        # Take profit price
        tp = df["Close"] - (df[range_type] * tp_pct_range)
        
        # trade window
        tp_window = low[START+TD:sl_ts+TD]
        trade_start = START+TD
        trade_end = sl_ts
        target_pips = df["Close"] - tp
        sl_pips = df["Close"] - (df["Close"] + df[range_type] * sl_pct_range) 
        if tp_window.min() <= tp:
            win = 1
            gain = df["Close"] - tp
        else:
            loss = 1
            if stop is True:
                gain = sl_pips
            else:
                gain = df["Close"] - close_window.iloc[-1] if close_window.empty is False else 0
    
    data = win, loss, \
        target_pips, sl_pips, \
        gain, \
        trade_start, trade_end
    
    return data

# Set new columns 
# gains_cols = [ 
#     "Win", "Loss", 
#     "TP", "SL", 
#     "Gain",
#     "Trade_Start", "Trade_End"
#     ]

#df[pct_50_idr_cols] = df.apply(get_bear_bbr_pip_gain, axis=1, args=[df["High"], df["Low"], df["Close"]], result_type='expand')

### Simulate Long Positions (Range-Based)

In [189]:
def range_long_gains(
        df: Series, 
        high: Series, 
        low: Series,
        close: Series,
        signal_name: str,
        sl_pct_range: int,
        tp_pct_range: int,
        range_type: str = "ADR"
        ):
    """Get the pip gain and apply to df"""

    win = 0
    loss = 0
    target_pips = 0 
    sl_pips = 0
    gain = 0
    trade_start =  None
    trade_end = None
    
    if df[signal_name] is True:
        idx = int(df["Idx"])
        iday_idx = int(df["Iday_Idx"])
        # get signal start of fx day timestamp
        day_start_ts = low.iloc[idx-iday_idx:idx-iday_idx+1].index[0]
        OFFSET = day_start_ts + pd.DateOffset(days=1) # end of signal's fx day
        START = df.name # signal start time
        TD = pd.Timedelta(minutes=15)
        END = OFFSET - TD # 17:00 on the signals fx day

        # get stop loss time:
        sl_window = low.loc[START+TD:END] # from signal idx+1 to EOD
        close_window = close.loc[START+TD:END] # from signal idx+1 to EOD
        stop = False # update if stopped 
        sl_ts = None # get timestamp when stopped out

        for i in range(len(sl_window)): 
            if sl_window.iloc[i] <= (df["Close"] - df[range_type] * sl_pct_range ):
                stop = True # trade hit stop loss
                # get stop loss timestamp
                sl_ts = sl_window.iloc[i:i+1].index[0] 
                break
        # if not stopped out then the stop window is signal:EOD
        # don't include trade if it is the last candle of the day
        if stop is False:
            if close_window.empty is False:
                sl_ts = close_window.iloc[-1:].index[0]
            else:
                sl_ts = START+TD

        # Take profit price
        tp = df["Close"] + (df[range_type] * tp_pct_range)
           
        # trade window
        tp_window = high[START+TD:sl_ts+TD]
        trade_start = START+TD
        trade_end = sl_ts
        target_pips = tp - df["Close"]
        sl_pips = (df["Close"] - df[range_type] * sl_pct_range) - df["Close"] 
        if tp_window.max() >= tp:
            win = 1
            gain = tp - df["Close"]
        else:
            loss = 1
            if stop is True:
                gain = sl_pips
            else:
                gain = close_window.iloc[-1] - df["Close"] if close_window.empty is False else 0
    
    data = win, loss, \
        target_pips, sl_pips, \
        gain, \
        trade_start, trade_end, \
        
    return data

# Set new columns 
# long_gains_cols = [
#     "Win", "Loss", 
#     "TP", "SL", 
#     "Gain",
#     "Trade_Start", "Trade_End",
#     ]

#df[pct_50_idr_cols] = df.apply(get_bull_bbr_pip_gain, axis=1, args=[df["High"], df["Low"], df["Close"]], result_type='expand')

### Simulate Long/Short Trend Position

In [132]:
def trend_gains(
        df: Series, 
        close: Series,
        sma: Series,
        signal_name: str,
        trade_direction: int
        ):
    """Get the pip gain and apply to df
    
    - trade_direction must be:
        - Long: 1
        - Short -1
    """

    win = 0
    loss = 0
    target_pips = 0 
    sl_pips = 0
    gain = 0
    trade_start =  None
    trade_end = None
    
    if df[signal_name] is True:
        idx = int(df["Idx"])
        iday_idx = int(df["Iday_Idx"])
        # get signal start of fx day timestamp
        day_start_ts = close.iloc[idx-iday_idx:idx-iday_idx+1].index[0]
        OFFSET = day_start_ts + pd.DateOffset(days=1) # end of signal's fx day
        START = df.name # signal start time
        TD = pd.Timedelta(minutes=15)
        END = OFFSET - TD # 17:00 on the signals fx day

        sma_window = sma.loc[START+TD:END] # from signal idx+1 to EOD
        close_window = close.loc[START+TD:END] # from signal idx+1 to EOD
        stop = False # update if stopped 
        sl_ts = None # get timestamp when stopped out
        
        # find exit timestamp:
        for i in range(len(close_window)): 
            # exit condition
            if trade_direction == 1:
                exit_condition = close_window.iloc[i] < sma_window.iloc[i]
            elif trade_direction == -1:
                exit_condition = close_window.iloc[i] > sma_window.iloc[i]
            # get stop loss time:
            if exit_condition:
                stop = True # trade hit stop loss
                # get stop loss timestamp
                sl_ts = close_window.iloc[i:i+1].index[0] 
                break
        # if not stopped out then the stop window is signal:EOD
        # don't include trade if it is the last candle of the day
        if stop is False:
            if close_window.empty is False:
                sl_ts = close_window.iloc[-1:].index[0]
            else:
                sl_ts = START+TD if (START+TD) < END else START

        # Win / Loss / Gain / Pips
        if trade_direction == 1:
            gain = close[sl_ts] - df["Close"]
        elif trade_direction == -1:
            gain = df["Close"] - close[sl_ts]
        trade_start = START+TD
        trade_end = sl_ts
        target_pips = df["ATR4"]
        sl_pips = -(df["ATR4"])
        win = 1 if gain > 0 else 0
        loss = 1 if gain < 0 else 0
    
    data = win, loss, \
        target_pips, sl_pips, \
        gain, \
        trade_start, trade_end, \
        
    return data

In [64]:
# Set new columns 
gains_cols = [ 
    "Win", "Loss", 
    "TP", "SL", 
    "Gain",
    "Trade_Start", "Trade_End"
    ]

### Trade Stats

In [133]:
def trade_stats(df: DataFrame, signal_name: str):
    win_count = df.query(f"{signal_name} == True and Win > 0")[f"{signal_name}"].count()
    loss_count = df.query(f"{signal_name} == True and Loss > 0")[f"{signal_name}"].count()
    total_trades = win_count + loss_count
    win_rate = win_count/total_trades * 100
    win = df.query(f"{signal_name} == True and Gain > 0")["Gain"]
    loss = df.query(f"{signal_name} == True and Gain < 0")["Gain"]
    win_avg_pips = win.mean()
    loss_avg_pips = loss.mean()
    win_pips = win.sum()
    loss_pips = loss.sum()
    total_pips = win_pips + loss_pips

    stats = {
        "Win_Count": win_count,
        "Loss_Count": loss_count,
        "Total_Trades": total_trades,
        "Win_Rate": win_rate,
        "Avg_Win": win_avg_pips,
        "Avg_Loss": loss_avg_pips,
        "Win_Pips": win_pips,
        "Loss_Pips": loss_pips,
        "Total_Pips": total_pips
    }

    return stats

## Breakout

In [331]:
pd.options.display.max_rows = 100
data_end_date: str = "20250311"
path: str = f"./price_data/FE_GBPUSD_15mins_1yr_End_{data_end_date}.csv"
bull_bo_df = get_fe_price_data(filename=path)
bear_bo_df = get_fe_price_data(filename=path)

long_signal = "BBU_BO"
short_signal = "BBL_BO"

# long
bull_bo_df[gains_cols] = bull_bo_df.apply(
    trend_gains,
    axis=1,
    args=[bull_bo_df["Close"], bull_bo_df["SMA8"], long_signal, 1],
    result_type='expand'
)
# short
bear_bo_df[gains_cols] = bear_bo_df.apply(
    trend_gains,
    axis=1,
    args=[bear_bo_df["Close"], bear_bo_df["SMA8"], short_signal, -1],
    result_type='expand'
)

bull_bo_gains_df = trade_stats(bull_bo_df.query("SMA_Trend in [0,2] and Iday_Range < (Yday_High - Yday_Low) * 0.50"), long_signal)
bear_bo_gains_df = trade_stats(bear_bo_df.query("SMA_Trend in [0,-2] and Iday_Range < (Yday_High - Yday_Low) * 0.50"), short_signal)

bo_gains_df = pd.DataFrame(data=[bull_bo_gains_df, bear_bo_gains_df],
             index=[long_signal,short_signal]
             )

bo_gains_df

/var/folders/zj/znqgk8kn6rqg7hbspq68r8_h0000gp/T/ipykernel_2283/850889442.py:9: DtypeWarning: Columns (34,45,46,48,49,50,51,56,57,58,59,60,61,62,63,65,66,67,68,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/zj/znqgk8kn6rqg7hbspq68r8_h0000gp/T/ipykernel_2283/850889442.py:9: DtypeWarning: Columns (34,45,46,48,49,50,51,56,57,58,59,60,61,62,63,65,66,67,68,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)

,Win_Count,Loss_Count,Total_Trades,Win_Rate,Avg_Win,Avg_Loss,Win_Pips,Loss_Pips,Total_Pips
BBU_BO,48,105,153,31.372549,0.001271,-0.000707,0.060990,-0.074210,-0.01322
BBL_BO,66,95,161,40.993789,0.001864,-0.000708,0.123015,-0.067235,0.05578

In [329]:
bull_bo_df[[*gains_cols, "Close_Pct_SMA", "RSI_DVG", "SMA32_Slope_SMA", "SMA16_Slope_SMA"]].query("Win > 0").iloc[0:100]

,Win,Loss,TP,SL,Gain,Trade_Start,Trade_End,Close_Pct_SMA,RSI_DVG,SMA32_Slope_SMA,SMA16_Slope_SMA
Date,,,,,,,,,,,
2024-03-14 03:00:00-04:00,1.0,0.0,0.000471,-0.000471,0.001365,2024-03-14 03:15:00-04:00,2024-03-14 06:30:00-04:00,0.052402,NaN,-6.749566,-14.752260
2024-03-14 04:00:00-04:00,1.0,0.0,0.000696,-0.000696,0.000315,2024-03-14 04:15:00-04:00,2024-03-14 06:30:00-04:00,0.109442,NaN,-5.638673,-3.756310
2024-03-15 05:30:00-04:00,1.0,0.0,0.000781,-0.000781,0.000105,2024-03-15 05:45:00-04:00,2024-03-15 07:00:00-04:00,0.056736,NaN,-6.116460,9.318714
2024-03-20 10:00:00-04:00,1.0,0.0,0.000757,-0.000757,0.007865,2024-03-20 10:15:00-04:00,2024-03-20 16:45:00-04:00,0.098321,NaN,-28.773365,-27.065973
2024-03-20 14:15:00-04:00,1.0,0.0,0.001530,-0.001530,0.004825,2024-03-20 14:30:00-04:00,2024-03-20 16:45:00-04:00,0.166645,NaN,8.790106,39.127460
2024-03-20 14:30:00-04:00,1.0,0.0,0.002523,-0.002523,0.002480,2024-03-20 14:45:00-04:00,2024-03-20 16:45:00-04:00,0.324947,NaN,12.992826,41.645734
2024-03-20 14:45:00-04:00,1.0,0.0,0.002867,-0.002867,0.000565,2024-03-20 15:00:00-04:00,2024-03-20 16:45:00-04:00,0.438490,NaN,17.429682,44.505556
2024-03-22 08:15:00-04:00,1.0,0.0,0.001097,-0.001097,0.000350,2024-03-22 08:30:00-04:00,2024-03-22 10:00:00-04:00,0.156041,True,-52.459923,-52.398110
2024-03-24 21:15:00-04:00,1.0,0.0,0.000561,-0.000561,0.000130,2024-03-24 21:30:00-04:00,2024-03-24 23:15:00-04:00,0.084169,NaN,-9.884751,6.975655
2024-03-29 08:30:00-04:00,1.0,0.0,0.000924,-0.000924,0.000325,2024-03-29 08:45:00-04:00,2024-03-29 10:15:00-04:00,0.111739,NaN,-5.824513,-7.127198
2024-04-02 03:00:00-04:00,1.0,0.0,0.000645,-0.000645,0.001080,2024-04-02 03:15:00-04:00,2024-04-02 06:15:00-04:00,0.080685,NaN,-5.326645,-1.157763
2024-04-03 10:15:00-04:00,1.0,0.0,0.001651,-0.001651,0.004275,2024-04-03 10:30:00-04:00,2024-04-03 15:00:00-04:00,0.217444,NaN,-0.002080,8.357213
2024-04-03 10:30:00-04:00,1.0,0.0,0.001920,-0.001920,0.002870,2024-04-03 10:45:00-04:00,2024-04-03 15:00:00-04:00,0.305711,NaN,2.658067,12.334237
2024-04-09 05:00:00-04:00,1.0,0.0,0.000734,-0.000734,0.001210,2024-04-09 05:15:00-04:00,2024-04-09 07:30:00-04:00,0.075729,NaN,-0.027124,0.838399
2024-04-09 05:30:00-04:00,1.0,0.0,0.000837,-0.000837,0.000245,2024-04-09 05:45:00-04:00,2024-04-09 07:30:00-04:00,0.137462,NaN,1.700778,3.282785
2024-04-10 03:45:00-04:00,1.0,0.0,0.000629,-0.000629,0.000950,2024-04-10 04:00:00-04:00,2024-04-10 07:15:00-04:00,0.071524,NaN,2.712907,9.159613
2024-04-10 04:45:00-04:00,1.0,0.0,0.000684,-0.000684,0.000345,2024-04-10 05:00:00-04:00,2024-04-10 07:15:00-04:00,0.092769,NaN,6.728421,16.256040
2024-04-17 22:00:00-04:00,1.0,0.0,0.000690,-0.000690,0.000430,2024-04-17 22:15:00-04:00,2024-04-18 01:00:00-04:00,0.078384,NaN,10.616625,1.975622
2024-04-23 20:15:00-04:00,1.0,0.0,0.000551,-0.000551,0.000220,2024-04-23 20:30:00-04:00,2024-04-23 22:45:00-04:00,0.046735,NaN,28.460185,-0.989607
2024-04-25 02:00:00-04:00,1.0,0.0,0.000432,-0.000432,0.003540,2024-04-25 02:15:00-04:00,2024-04-25 05:45:00-04:00,0.094024,NaN,7.743183,13.175580
2024-04-25 02:15:00-04:00,1.0,0.0,0.000673,-0.000673,0.002470,2024-04-25 02:30:00-04:00,2024-04-25 05:45:00-04:00,0.166268,NaN,8.638326,15.269895
2024-05-06 02:30:00-04:00,1.0,0.0,0.000642,-0.000642,0.002115,2024-05-06 02:45:00-04:00,2024-05-06 06:15:00-04:00,0.077908,NaN,-3.412893,-5.170447
2024-05-06 03:00:00-04:00,1.0,0.0,0.000732,-0.000732,0.001170,2024-05-06 03:15:00-04:00,2024-05-06 06:15:00-04:00,0.139733,NaN,-1.857343,-2.163356
2024-05-13 07:00:00-04:00,1.0,0.0,0.000594,-0.000594,0.001610,2024-05-13 07:15:00-04:00,2024-05-13 10:00:00-04:00,0.092314,NaN,6.540745,2.460948
2024-05-13 07:30:00-04:00,1.0,0.0,0.000718,-0.000718,0.000675,2024-05-13 07:45:00-04:00,2024-05-13 10:00:00-04:00,0.145861,NaN,9.544223,8.450234
2024-05-15 04:15:00-04:00,1.0,0.0,0.000640,-0.000640,0.000970,2024-05-15 04:30:00-04:00,2024-05-15 06:15:00-04:00,0.088673,NaN,7.362642,4.128403
2024-05-15 04:45:00-04:00,1.0,0.0,0.000735,-0.000735,0.000385,2024-05-15 05:00:00-04:00,2024-05-15 06:15:00-04:00,0.119072,NaN,9.623926,6.059776
2024-05-17 09:00:00-04:00,1.0,0.0,0.000539,-0.000539,0.003460,2024-05-17 09:15:00-04:00,2024-05-17 12:30:00-04:00,0.095818,NaN,-4.398234,-10.314006
2024-05-17 09:45:00-04:00,1.0,0.0,0.000942,-0.000942,0.002500,2024-05-17 10:00:00-04:00,2024-05-17 12:30:00-04:00,0.147519,NaN,-0.786133,-0.857512
2024-05-17 10:30:00-04:00,1.0,0.0,0.000992,-0.000992,0.000815,2024-05-17 10:45:00-04:00,2024-05-17 12:30:00-04:00,0.236618,NaN,3.618278,11.835856
2024-05-24 02:00:00-04:00,1.0,0.0,0.000796,-0.000796,0.001875,2024-05-24 02:15:00-04:00,2024-05-24 07:15:00-04:00,0.048706,NaN,-3.794759,-8.780305
2024-05-24 03:00:00-04:00,1.0,0.0,0.000690,-0.000690,0.001410,2024-05-24 03:15:00-04:00,2024-05-24 07:15:00-04:00,0.076056,NaN,-3.505019,-3.730497
2024-05-27 09:15:00-04:00,1.0,0.0,0.000751,-0.000751,0.000295,2024-05-27 09:30:00-04:00,2024-05-27 11:45:00-04:00,0.117830,NaN,14.204552,24.552733
2024-05-28 07:00:00-04:00,1.0,0.0,0.000640,-0.000640,0.000235,2024-05-28 07:15:00-04:00,2024-05-28 09:30:00-04:00,0.119982,True,-3.258896,-12.096030
2024-05-30 03:00:00-04:00,1.0,0.0,0.000883,-0.000883,0.000345,2024-05-30 03:15:00-04:00,2024-05-30 06:00:00-04:00,0.077780,True,-11.208834,-9.829205
2024-05-31 08:30:00-04:00,1.0,0.0,0.001210,-0.001210,0.000245,2024-05-31 08:45:00-04:00,2024-05-31 10:30:00-04:00,0.142663,NaN,-3.869609,10.085614
2024-05-31 15:30:00-04:00,1.0,0.0,0.000621,-0.000621,0.000255,2024-05-31 15:45:00-04:00,2024-05-31 16:45:00-04:00,0.063427,NaN,14.887424,-11.069577
2024-06-03 10:00:00-04:00,1.0,0.0,0.001562,-0.001562,0.000320,2024-06-03 10:15:00-04:00,2024-06-03 12:00:00-04:00,0.382690,NaN,-14.842909,19.488667
2024-06-04 20:30:00-04:00,1.0,0.0,0.000412,-0.000412,0.000065,2024-06-04 20:45:00-04:00,2024-06-04 22:45:00-04:00,0.035822,NaN,-4.513118,-24.998045
2024-06-18 09:00:00-04:00,1.0,0.0,0.001223,-0.001223,0.000470,2024-06-18 09:15:00-04:00,2024-06-18 10:30:00-04:00,0.117663,NaN,-15.841363,-10.897099
2024-06-24 09:15:00-04:00,1.0,0.0,0.000647,-0.000647,0.000815,2024-06-24 09:30:00-04:00,2024-06-24 11:30:00-04:00,0.093062,True,27.127589,25.846043
2024-06-26 21:45:00-04:00,1.0,0.0,0.000475,-0.000475,0.000825,2024-06-26 22:00:00-04:00,2024-06-27 02:30:00-04:00,0.061160,NaN,-11.729153,-6.530637
2024-06-30 20:30:00-04:00,1.0,0.0,0.000491,-0.000491,0.000175,2024-06-30 20:45:00-04:00,2024-06-30 22:30:00-04:00,0.052624,NaN,9.896223,14.875130
2024-06-30 21:00:00-04:00,1.0,0.0,0.000710,-0.000710,0.000010,2024-06-30 21:15:00-04:00,2024-06-30 22:30:00-04:00,0.054718,NaN,12.025831,17.724701
2024-07-01 01:30:00-04:00,1.0,0.0,0.000365,-0.000365,0.000790,2024-07-01 01:45:00-04:00,2024-07-01 03:15:00-04:00,0.049694,NaN,19.360576,16.098280
2024-07-03 08:30:00-04:00,1.0,0.0,0.000806,-0.000806,0.004270,2024-07-03 08:45:00-04:00,2024-07-03 11:45:00-04:00,0.153818,NaN,16.732577,28.657958
2024-07-03 09:00:00-04:00,1.0,0.0,0.001059,-0.001059,0.003165,2024-07-03 09:15:00-04:00,2024-07-03 11:45:00-04:00,0.210268,NaN,20.324149,31.678882
2024-07-05 03:45:00-04:00,1.0,0.0,0.000744,-0.000744,0.000595,2024-07-05 04:00:00-04:00,2024-07-05 07:30:00-04:00,0.074975,NaN,13.999041,13.806671
2024-07-10 09:30:00-04:00,1.0,0.0,0.001005,-0.001005,0.000800,2024-07-10 09:45:00-04:00,2024-07-10 13:00:00-04:00,0.186993,NaN,20.223996,27.466183
2024-07-10 10:00:00-04:00,1.0,0.0,0.001232,-0.001232,0.000695,2024-07-10 10:15:00-04:00,2024-07-10 13:00:00-04:00,0.171510,NaN,22.410770,28.468058
2024-07-12 03:30:00-04:00,1.0,0.0,0.000606,-0.000606,0.003540,2024-07-12 03:45:00-04:00,2024-07-12 08:15:00-04:00,0.068569,NaN,-2.826399,2.977065
2024-07-12 03:45:00-04:00,1.0,0.0,0.000761,-0.000761,0.002745,2024-07-12 04:00:00-04:00,2024-07-12 08:15:00-04:00,0.120402,NaN,-2.285961,6.585445
2024-07-12 09:45:00-04:00,1.0,0.0,0.001432,-0.001432,0.000325,2024-07-12 10:00:00-04:00,2024-07-12 11:45:00-04:00,0.148417,True,47.493204,51.676156
2024-07-16 14:30:00-04:00,1.0,0.0,0.000461,-0.000461,0.000620,2024-07-16 14:45:00-04:00,2024-07-16 16:45:00-04:00,0.088665,NaN,-10.304729,-5.314928
2024-07-17 03:00:00-04:00,1.0,0.0,0.001120,-0.001120,0.003355,2024-07-17 03:15:00-04:00,2024-07-17 06:30:00-04:00,0.162924,NaN,2.173040,4.348120
2024-07-17 03:30:00-04:00,1.0,0.0,0.001186,-0.001186,0.001930,2024-07-17 03:45:00-04:00,2024-07-17 06:30:00-04:00,0.243774,NaN,5.084149,10.683557
2024-07-21 18:15:00-04:00,1.0,0.0,0.000665,-0.000665,0.000385,2024-07-21 18:30:00-04:00,2024-07-21 20:00:00-04:00,0.101878,NaN,-7.830806,-9.961885
2024-07-24 05:45:00-04:00,1.0,0.0,0.000845,-0.000845,0.000900,2024-07-24 06:00:00-04:00,2024-07-24 10:30:00-04:00,0.135237,NaN,-11.062807,2.421041
2024-07-28 20:30:00-04:00,1.0,0.0,0.000544,-0.000544,0.000415,2024-07-28 20:45:00-04:00,2024-07-28 22:45:00-04:00,0.068862,NaN,8.872361,-7.219820
2024-08-02 08:45:00-04:00,1.0,0.0,0.002802,-0.002802,0.001870,2024-08-02 09:00:00-04:00,2024-08-02 10:30:00-04:00,0.435456,NaN,24.617384,32.598321
2024-08-02 09:00:00-04:00,1.0,0.0,0.003241,-0.003241,0.000610,2024-08-02 09:15:00-04:00,2024-08-02 10:30:00-04:00,0.496388,NaN,27.312648,35.574064
2024-08-06 20:45:00-04:00,1.0,0.0,0.000791,-0.000791,0.000695,2024-08-06 21:00:00-04:00,2024-08-07 00:30:00-04:00,0.086843,NaN,-9.480236,-9.507341
2024-08-08 10:00:00-04:00,1.0,0.0,0.001681,-0.001681,0.003015,2024-08-08 10:15:00-04:00,2024-08-08 15:30:00-04:00,0.189099,True,-5.766384,-14.311351
2024-08-08 22:15:00-04:00,1.0,0.0,0.000491,-0.000491,0.000080,2024-08-08 22:30:00-04:00,2024-08-09 00:15:00-04:00,0.082088,NaN,13.784210,-4.859598
2024-08-13 08:30:00-04:00,1.0,0.0,0.001294,-0.001294,0.001430,2024-08-13 08:45:00-04:00,2024-08-13 11:30:00-04:00,0.117119,True,21.295267,-7.100254
2024-08-13 09:15:00-04:00,1.0,0.0,0.001601,-0.001601,0.000560,2024-08-13 09:30:00-04:00,2024-08-13 11:30:00-04:00,0.168174,True,20.797124,-9.708219
2024-08-14 22:00:00-04:00,1.0,0.0,0.000600,-0.000600,0.001075,2024-08-14 22:15:00-04:00,2024-08-15 02:30:00-04:00,0.049629,NaN,-18.501961,-4.186755
2024-08-15 00:00:00-04:00,1.0,0.0,0.000306,-0.000306,0.000530,2024-08-15 00:15:00-04:00,2024-08-15 02:30:00-04:00,0.067958,NaN,-2.223767,3.300125
2024-08-15 21:15:00-04:00,1.0,0.0,0.000399,-0.000399,0.000480,2024-08-15 21:30:00-04:00,2024-08-15 23:15:00-04:00,0.065374,NaN,8.439794,4.092246
2024-08-16 05:15:00-04:00,1.0,0.0,0.000652,-0.000652,0.000635,2024-08-16 05:30:00-04:00,2024-08-16 07:15:00-04:00,0.108041,True,26.465128,23.008283
2024-08-19 10:00:00-04:00,1.0,0.0,0.001100,-0.001100,0.000235,2024-08-19 10:15:00-04:00,2024-08-19 11:30:00-04:00,0.174841,True,-3.928996,-25.199547
2024-08-21 10:00:00-04:00,1.0,0.0,0.001445,-0.001445,0.003905,2024-08-21 10:15:00-04:00,2024-08-21 15:00:00-04:00,0.130140,NaN,16.165394,36.392779
2024-08-21 10:15:00-04:00,1.0,0.0,0.001729,-0.001729,0.003315,2024-08-21 10:30:00-04:00,2024-08-21 15:00:00-04:00,0.160669,NaN,18.196057,38.368330
2024-08-21 10:30:00-04:00,1.0,0.0,0.001911,-0.001911,0.002940,2024-08-21 10:45:00-04:00,2024-08-21 15:00:00-04:00,0.176075,NaN,20.081754,39.612514
2024-08-22 02:15:00-04:00,1.0,0.0,0.000590,-0.000590,0.001925,2024-08-22 02:30:00-04:00,2024-08-22 06:15:00-04:00,0.063214,NaN,-11.117182,-10.792715
2024-08-22 03:00:00-04:00,1.0,0.0,0.000791,-0.000791,0.001520,2024-08-22 03:15:00-04:00,2024-08-22 06:15:00-04:00,0.084269,NaN,-5.834342,-5.025226
2024-08-23 10:00:00-04:00,1.0,0.0,0.002692,-0.002692,0.000010,2024-08-23 10:15:00-04:00,2024-08-23 11:45:00-04:00,0.528291,NaN,17.803857,-1.911364
2024-08-27 04:15:00-04:00,1.0,0.0,0.001027,-0.001027,0.000145,2024-08-27 04:30:00-04:00,2024-08-27 06:15:00-04:00,0.139034,NaN,13.028836,23.209577
2024-08-27 14:00:00-04:00,1.0,0.0,0.000746,-0.000746,0.000400,2024-08-27 14:15:00-04:00,2024-08-27 16:45:00-04:00,0.142531,True,24.579062,36.960273
2024-08-28 20:00:00-04:00,1.0,0.0,0.000332,-0.000332,0.000390,2024-08-28 20:15:00-04:00,2024-08-28 21:45:00-04:00,0.056309,NaN,-16.214173,21.632574
2024-08-30 02:00:00-04:00,1.0,0.0,0.000471,-0.000471,0.000840,2024-08-30 02:15:00-04:00,2024-08-30 04:45:00-04:00,0.070000,NaN,-6.470815,-3.898095
2024-09-04 09:45:00-04:00,1.0,0.0,0.001051,-0.001051,0.001095,2024-09-04 10:00:00-04:00,2024-09-04 11:15:00-04:00,0.145356,NaN,7.259148,4.067175
2024-09-12 10:30:00-04:00,1.0,0.0,0.001220,-0.001220,0.005000,2024-09-12 10:45:00-04:00,2024-09-12 16:45:00-04:00,0.148820,NaN,9.305243,11.606203
2024-09-12 20:00:00-04:00,1.0,0.0,0.000431,-0.000431,0.000100,2024-09-12 20:15:00-04:00,2024-09-12 21:30:00-04:00,0.096249,NaN,52.133987,47.689884
2024-09-15 23:15:00-04:00,1.0,0.0,0.000480,-0.000480,0.000095,2024-09-15 23:30:00-04:00,2024-09-16 00:45:00-04:00,0.080563,NaN,12.570922,31.434718
2024-09-16 02:45:00-04:00,1.0,0.0,0.000721,-0.000721,0.002405,2024-09-16 03:00:00-04:00,2024-09-16 06:45:00-04:00,0.095127,NaN,32.840125,34.157291
2024-09-16 03:30:00-04:00,1.0,0.0,0.000834,-0.000834,0.001980,2024-09-16 03:45:00-04:00,2024-09-16 06:45:00-04:00,0.107932,True,33.339390,33.729181
2024-09-17 03:30:00-04:00,1.0,0.0,0.000935,-0.000935,0.000175,2024-09-17 03:45:00-04:00,2024-09-17 05:30:00-04:00,0.083697,NaN,-7.784488,-1.381216
2024-09-18 02:00:00-04:00,1.0,0.0,0.000670,-0.000670,0.003580,2024-09-18 02:15:00-04:00,2024-09-18 06:45:00-04:00,0.097195,NaN,1.694948,-7.258168
2024-09-18 02:45:00-04:00,1.0,0.0,0.001336,-0.001336,0.002850,2024-09-18 03:00:00-04:00,2024-09-18 06:45:00-04:00,0.134301,NaN,3.852984,-3.290634
2024-09-19 02:00:00-04:00,1.0,0.0,0.000820,-0.000820,0.003835,2024-09-19 02:15:00-04:00,2024-09-19 06:30:00-04:00,0.208744,NaN,-12.698838,17.558680
2024-09-19 02:30:00-04:00,1.0,0.0,0.001089,-0.001089,0.002825,2024-09-19 02:45:00-04:00,2024-09-19 06:30:00-04:00,0.237969,NaN,-2.951663,31.206527
2024-09-19 02:45:00-04:00,1.0,0.0,0.001214,-0.001214,0.001855,2024-09-19 03:00:00-04:00,2024-09-19 06:30:00-04:00,0.281373,NaN,2.882158,38.394753
2024-09-26 05:15:00-04:00,1.0,0.0,0.000949,-0.000949,0.001600,2024-09-26 05:30:00-04:00,2024-09-26 08:15:00-04:00,0.104368,NaN,27.858802,24.098864
2024-09-26 06:30:00-04:00,1.0,0.0,0.001095,-0.001095,0.000205,2024-09-26 06:45:00-04:00,2024-09-26 08:15:00-04:00,0.168166,NaN,29.686122,24.006320
2024-10-11 03:30:00-04:00,1.0,0.0,0.000844,-0.000844,0.000635,2024-10-11 03:45:00-04:00,2024-10-11 05:00:00-04:00,0.099964,NaN,-7.646321,-19.097216
2024-10-24 02:00:00-04:00,1.0,0.0,0.000480,-0.000480,0.002090,2024-10-24 02:15:00-04:00,2024-10-24 04:30:00-04:00,0.055092,NaN,4.249294,22.279936
2024-10-24 02:30:00-04:00,1.0,0.0,0.000892,-0.000892,0.001450,2024-10-24 02:45:00-04:00,2024-10-24 04:30:00-04:00,0.093422,NaN,5.684191,22.039088
2024-10-29 03:15:00-04:00,1.0,0.0,0.000557,-0.000557,0.000780,2024-10-29 03:30:00-04:00,2024-10-29 05:45:00-04:00,0.063736,NaN,-8.238452,-18.221679
2024-10-31 02:45:00-04:00,1.0,0.0,0.000716,-0.000716,0.000605,2024-10-31 03:00:00-04:00,2024-10-31 04:45:00-04:00,0.162195,NaN,-16.114302,-1.577619

## SMA Breakout

In [186]:
pd.options.display.max_rows = 100
data_end_date: str = "20250311"
path: str = f"./price_data/FE_GBPUSD_15mins_1yr_End_{data_end_date}.csv"
bull_sma_bo_df = get_fe_price_data(filename=path)
bear_sma_bo_df = get_fe_price_data(filename=path)

long_signal = "Bull_SMA_BO"
short_signal = "Bear_SMA_BO"

# long
bull_sma_bo_df[gains_cols] = bull_sma_bo_df.apply(
    trend_gains,
    axis=1,
    args=[bull_sma_bo_df["Close"], bull_sma_bo_df["SMA4"], long_signal, 1],
    result_type='expand'
)
# short
bear_sma_bo_df[gains_cols] = bear_sma_bo_df.apply(
    trend_gains,
    axis=1,
    args=[bear_sma_bo_df["Close"], bear_sma_bo_df["SMA4"], short_signal, -1],
    result_type='expand'
)

bull_sma_bo_gains_df = trade_stats(bull_sma_bo_df, long_signal)
bear_sma_bo_gains_df = trade_stats(bear_sma_bo_df, short_signal)

sma_bo_gains_df = pd.DataFrame(data=[bull_sma_bo_gains_df, bear_sma_bo_gains_df],
             index=[long_signal,short_signal]
             )

sma_bo_gains_df

/var/folders/zj/znqgk8kn6rqg7hbspq68r8_h0000gp/T/ipykernel_2283/850889442.py:9: DtypeWarning: Columns (34,45,46,48,49,50,51,56,57,58,59,60,61,62,63,65,66,67,68,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/zj/znqgk8kn6rqg7hbspq68r8_h0000gp/T/ipykernel_2283/850889442.py:9: DtypeWarning: Columns (34,45,46,48,49,50,51,56,57,58,59,60,61,62,63,65,66,67,68,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)

,Win_Count,Loss_Count,Total_Trades,Win_Rate,Avg_Win,Avg_Loss,Win_Pips,Loss_Pips,Total_Pips
Bull_SMA_BO,62,72,134,46.268657,0.001410,-0.000623,0.087405,-0.044855,0.04255
Bear_SMA_BO,57,95,152,37.500000,0.001299,-0.000639,0.074015,-0.060665,0.01335

## Bollinger Band Reversals

In [229]:
pd.options.display.max_rows = 100
data_end_date: str = "20250311"
path: str = f"./price_data/FE_GBPUSD_15mins_1yr_End_{data_end_date}.csv"
bull_bbr_df = get_fe_price_data(filename=path)
bear_bbr_df = get_fe_price_data(filename=path)

long_signal = "Bull_BBR_V2"
short_signal = "Bear_BBR_V2"

# long
bull_bbr_df[gains_cols] = bull_bbr_df.apply(
    range_long_gains,
    axis=1,
    args=[bull_bbr_df["High"],bull_bbr_df["Low"],bull_bbr_df["Close"], 
          long_signal, 1.5, 2.5],
    result_type='expand',
    range_type="ATR4"
)
# short
bear_bbr_df[gains_cols] = bear_bbr_df.apply(
    range_short_gains,
    axis=1,
    args=[bear_bbr_df["High"],bear_bbr_df["Low"],bear_bbr_df["Close"], 
          short_signal, 1.5, 2.5],
    result_type='expand',
    range_type="ATR4"
)

bull_bbr_gains_df = trade_stats(bull_bbr_df, long_signal)
bear_bbr_gains_df = trade_stats(bear_bbr_df, short_signal)

bbr_gains_df = pd.DataFrame(data=[bull_bbr_gains_df, bear_bbr_gains_df],
             index=[long_signal,short_signal]
             )

bbr_gains_df

/var/folders/zj/znqgk8kn6rqg7hbspq68r8_h0000gp/T/ipykernel_2283/850889442.py:9: DtypeWarning: Columns (34,45,46,48,49,50,51,56,57,58,59,60,61,62,63,65,66,67,68,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/zj/znqgk8kn6rqg7hbspq68r8_h0000gp/T/ipykernel_2283/850889442.py:9: DtypeWarning: Columns (34,45,46,48,49,50,51,56,57,58,59,60,61,62,63,65,66,67,68,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)

,Win_Count,Loss_Count,Total_Trades,Win_Rate,Avg_Win,Avg_Loss,Win_Pips,Loss_Pips,Total_Pips
Bull_BBR_V2,183,309,492,37.195122,0.002349,-0.001330,0.544886,-0.344341,0.200544
Bear_BBR_V2,150,354,504,29.761905,0.002351,-0.001313,0.458520,-0.404528,0.053992

In [215]:
bull_bbr_df[[*gains_cols, "Bull_BBR_C1","Bull_BBR_C2","Bull_BBR_C3","Bull_BBR_C4"]].nlargest(10, "Gain")

,Win,Loss,TP,SL,Gain,Trade_Start,Trade_End,Bull_BBR_C1,Bull_BBR_C2,Bull_BBR_C3,Bull_BBR_C4
Date,,,,,,,,,,,
2025-02-06 07:45:00-05:00,1.0,0.0,0.007922,-0.004753,0.007922,2025-02-06 08:00:00-05:00,2025-02-06 16:45:00-05:00,NaN,NaN,NaN,True
2024-08-05 02:15:00-04:00,1.0,0.0,0.007772,-0.004663,0.007772,2024-08-05 02:30:00-04:00,2024-08-05 16:45:00-04:00,NaN,NaN,True,NaN
2025-01-20 20:00:00-05:00,0.0,1.0,0.009031,-0.005419,0.007675,2025-01-20 20:15:00-05:00,2025-01-21 16:45:00-05:00,NaN,NaN,True,NaN
2025-02-06 07:30:00-05:00,1.0,0.0,0.007637,-0.004582,0.007637,2025-02-06 07:45:00-05:00,2025-02-06 16:45:00-05:00,NaN,NaN,NaN,True
2025-02-12 09:00:00-05:00,1.0,0.0,0.007403,-0.004442,0.007403,2025-02-12 09:15:00-05:00,2025-02-12 16:45:00-05:00,NaN,NaN,True,NaN
2025-02-12 08:45:00-05:00,1.0,0.0,0.007147,-0.004288,0.007147,2025-02-12 09:00:00-05:00,2025-02-12 16:45:00-05:00,NaN,NaN,True,NaN
2024-08-05 02:00:00-04:00,1.0,0.0,0.006412,-0.003847,0.006412,2024-08-05 02:15:00-04:00,2024-08-05 16:45:00-04:00,NaN,NaN,True,NaN
2024-11-25 19:15:00-05:00,1.0,0.0,0.005909,-0.003546,0.005909,2024-11-25 19:30:00-05:00,2024-11-26 16:45:00-05:00,True,NaN,NaN,True
2025-01-15 02:15:00-05:00,1.0,0.0,0.005906,-0.003544,0.005906,2025-01-15 02:30:00-05:00,2025-01-15 16:45:00-05:00,True,NaN,NaN,NaN
2025-01-13 04:45:00-05:00,1.0,0.0,0.005716,-0.003429,0.005716,2025-01-13 05:00:00-05:00,2025-01-13 16:45:00-05:00,NaN,NaN,NaN,True

## Breakout Momentum

In [365]:
pd.options.display.max_rows = 100
data_end_date: str = "20250311"
path: str = f"./price_data/FE_GBPUSD_15mins_1yr_End_{data_end_date}.csv"
bull_bm_df = get_fe_price_data(filename=path)
bear_bm_df = get_fe_price_data(filename=path)

long_signal = "Bull_BM"
short_signal = "Bear_BM"

# long
bull_bm_df[gains_cols] = bull_bm_df.apply(
    range_long_gains,
    axis=1,
    args=[bull_bm_df["High"],bull_bm_df["Low"],bull_bm_df["Close"], 
          long_signal, 1, 1.25],
    result_type='expand',
    range_type="ATR4"
)
# short
bear_bm_df[gains_cols] = bear_bm_df.apply(
    range_short_gains,
    axis=1,
    args=[bear_bm_df["High"],bear_bm_df["Low"],bear_bm_df["Close"], 
          short_signal, 1, 1.25],
    result_type='expand',
    range_type="ATR4"
)

bull_bm_gains_df = trade_stats(bull_bm_df.query("Iday_Range < (Yday_High - Yday_Low) * 1.25"), long_signal)
bear_bm_gains_df = trade_stats(bear_bm_df.query("Iday_Range < (Yday_High - Yday_Low) * 1.25"), short_signal)

bo_momentum_gains_df = pd.DataFrame(data=[bull_bm_gains_df, bear_bm_gains_df],
             index=[long_signal,short_signal]
             )

bo_momentum_gains_df

/var/folders/zj/znqgk8kn6rqg7hbspq68r8_h0000gp/T/ipykernel_2283/850889442.py:9: DtypeWarning: Columns (34,45,46,48,49,50,51,56,57,58,59,60,61,62,63,65,66,67,68,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)
/var/folders/zj/znqgk8kn6rqg7hbspq68r8_h0000gp/T/ipykernel_2283/850889442.py:9: DtypeWarning: Columns (34,45,46,48,49,50,51,56,57,58,59,60,61,62,63,65,66,67,68,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)

,Win_Count,Loss_Count,Total_Trades,Win_Rate,Avg_Win,Avg_Loss,Win_Pips,Loss_Pips,Total_Pips
Bull_BM,510,625,1135,44.933921,0.001109,-0.000937,0.595353,-0.559687,0.035665
Bear_BM,379,474,853,44.431419,0.001188,-0.000958,0.472972,-0.433770,0.039202