# Bull BBR Reversal - Stats

## Import Libs

In [2]:
import pandas as pd 
import numpy as np
import os
from pandas import DataFrame, Series
import plotly.graph_objects as go

## Get Price Data

In [237]:
PATH = os.getcwd()
FILE = "../output/FE_V2_GBPUSD_15mins_1yr_End_20260311.csv"
df = pd.read_csv(FILE)
df["Date"] = pd.DatetimeIndex(df["Date"], tz="US/Eastern")
df.set_index("Date", inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 24580 entries, 2025-03-11 17:15:00-04:00 to 2026-03-11 16:45:00-04:00
Data columns (total 49 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Open           24580 non-null  float64
 1   High           24580 non-null  float64
 2   Low            24580 non-null  float64
 3   Close          24580 non-null  float64
 4   Idx            24580 non-null  int64
 5   Body           24580 non-null  float64
 6   Range          24580 non-null  float64
 7   UWick          24580 non-null  float64
 8   LWick          24580 non-null  float64
 9   Close_%High    24580 non-null  float64
 10  Open_%High     24580 non-null  float64
 11  Iday_Idx       24580 non-null  int64
 12  Iday_High      24580 non-null  float64
 13  Iday_Low       24580 non-null  float64
 14  Iday_Range     24580 non-null  float64
 15  Close_%DHigh   24580 non-null  float64
 16  Open_%DHigh    24580 non-null  float64
 17  Yday_High      24485 non-null  float64
 18  Yday_Low       24485 non-null  float64
 19  Day_Idx        24580 non-null  int64
 20  ADR            21646 non-null  float64
 21  ATR            24568 non-null  float64
 22  SMA4           24576 non-null  float64
 23  SMA16          24580 non-null  float64
 24  SMA32          24580 non-null  float64
 25  BB_Upper_16_2  24580 non-null  float64
 26  BB_Lower_16_2  24580 non-null  float64
 27  Close_%SMA     24580 non-null  float64
 28  RSI            24564 non-null  float64
 29  RSI_DVG        1233 non-null   object
 30  Sig_High       20360 non-null  float64
 31  Sig_Low        20726 non-null  float64
 32  SMA_Trend      24580 non-null  int64
 33  SMA4_Slope     24574 non-null  float64
 34  SMA16_Slope    24578 non-null  float64
 35  SMA32_Slope    24578 non-null  float64
 36  Hammer         957 non-null    object
 37  Shooting_Star  927 non-null    object
 38  Bull_Engulf    520 non-null    object
 39  Bear_Engulf    506 non-null    object
 40  Dark_Cloud     192 non-null    object
 41  Piercing       213 non-null    object
 42  ILR            277 non-null    object
 43  IHR            305 non-null    object
 44  S_R            3168 non-null   float64
 45  BBU_BO         554 non-null    object
 46  BBL_BO         183 non-null    object
 47  Bull_BBR       416 non-null    object
 48  Bear_BBR       389 non-null    object
dtypes: float64(32), int64(4), object(13)
memory usage: 9.4+ MB

## Low vs ADR% Stop Loss - 38.2% ADR Target

In [238]:
def get_bull_bbr_pip_gain(
        df: Series, 
        high: Series, 
        low: Series,
        close: Series  
        ):
    """Get the pip gain and apply to df"""

    low_win = 0
    low_loss = 0
    adr_win = 0
    adr_loss = 0
    low_target_pips = 0 
    adr_target_pips = 0 
    low_sl_pips = 0
    adr_sl_pips = 0
    low_gain = 0
    adr_gain = 0
    low_trade_start =  None
    low_trade_end = None
    adr_trade_start =  None
    adr_trade_end = None
    
    if df["Bull_BBR"] is True:
        idx = int(df["Idx"])
        iday_idx = int(df["Iday_Idx"])
        # get signal start of fx day timestamp
        day_start_ts = low.iloc[idx-iday_idx:idx-iday_idx+1].index[0]
        OFFSET = day_start_ts + pd.DateOffset(days=1) # end of signal's fx day
        START = df.name # signal start time
        TD = pd.Timedelta(minutes=15)
        END = OFFSET - TD # 17:00 on the signals fx day

        # get stop loss time:
        sl_window = low.loc[START+TD:END] # from signal idx+1 to EOD
        close_window = close.loc[START+TD:END] # from signal idx+1 to EOD
        low_stop = False 
        low_sl_ts = None # get timestamp when stopped out
        adr_stop = False # update if stopped 
        adr_sl_ts = None # get timestamp when stopped out
        stoploss_low = max(low.iloc[idx-1], low.iloc[idx])

        for i in range(len(sl_window)):
            if sl_window.iloc[i] <= stoploss_low : #stoploss_high:
                low_stop = True # trade hit stop loss
                # get stop loss timestamp
                low_sl_ts = sl_window.iloc[i:i+1].index[0]
                break 
        for i in range(len(sl_window)): 
            if sl_window.iloc[i] <= (df["Close"] - df["ADR"] * 0.25 ): #(stoploss_high + df["ATR"]):
                adr_stop = True # trade hit stop loss
                # get stop loss timestamp
                adr_sl_ts = sl_window.iloc[i:i+1].index[0] 
                break
        # if not stopped out then the stop window is signal:EOD
        # don't include trade if it is the last candle of the day
        if low_stop is False:
            if close_window.empty is False:
                low_sl_ts = close_window.iloc[-1:].index[0]
            else:
                low_sl_ts = START+TD
        if adr_stop is False:
            if close_window.empty is False:
                adr_sl_ts = close_window.iloc[-1:].index[0]
            else:
                adr_sl_ts = START+TD

        # Take profit price
        tp = df["Close"] + (df["ADR"] * 0.382)

        # High trade window
        low_tp_window = high[START+TD:low_sl_ts+TD]
        low_trade_start = START+TD
        low_trade_end = low_sl_ts
        low_target_pips = tp - df["Close"]
        low_sl_pips = stoploss_low - df["Close"]
        if low_tp_window.max() >= tp:
            low_win = 1
            low_gain = low_target_pips
        else:
            low_loss = 1
            if low_stop is True:
                low_gain = low_sl_pips
            else:
                low_gain = close_window.iloc[-1] - df["Close"] if close_window.empty is False else 0           
        # ATR trade window
        adr_tp_window = high[START+TD:adr_sl_ts+TD]
        adr_trade_start = START+TD
        adr_trade_end = adr_sl_ts
        adr_target_pips = tp - df["Close"]
        adr_sl_pips = (df["Close"] - df["ADR"] * 0.25) - df["Close"] 
        if adr_tp_window.max() >= tp:
            adr_win = 1
            adr_gain = tp - df["Close"]
        else:
            adr_loss = 1
            if adr_stop is True:
                adr_gain = adr_sl_pips
            else:
                adr_gain = close_window.iloc[-1] - df["Close"] if close_window.empty is False else 0
    
    data = low_win, low_loss, \
        adr_win, adr_loss, \
        low_target_pips, adr_target_pips, \
        low_sl_pips, adr_sl_pips, \
        low_gain, adr_gain, \
        adr_trade_start, adr_trade_end, \
        low_trade_start, low_trade_end
    
    return data

# Set new columns 
pct_50_idr_cols = [
    "Low_Win", "Low_Loss", 
    "ADR_Win", "ADR_Loss", 
    "Low_TP", "ADR_TP", 
    "Low_SL", "ADR_SL", 
    "Low_Gain", "ADR_Gain",
    "ADR_Trade_Start", "ADR_Trade_End",
    "Low_Trade_Start", "Low_Trade_End"
    ]

df[pct_50_idr_cols] = df.apply(get_bull_bbr_pip_gain, axis=1, args=[df["High"], df["Low"], df["Close"]], result_type='expand')

In [239]:
df2 = df.query("Bull_BBR == True").between_time("02:00", "11:00")

In [240]:
# Stats - High as SL
low_win_count = df2.query("Bull_BBR == True and Low_Win > 0")["Bull_BBR"].count()
low_loss_count = df2.query("Bull_BBR == True and Low_Loss > 0")["Bull_BBR"].count()
low_total_trades = low_win_count + low_loss_count
low_win_rate = low_win_count/low_total_trades * 100
low_win = df2.query("Bull_BBR == True and Low_Gain > 0")["Low_Gain"]
low_loss = df2.query("Bull_BBR == True and Low_Gain < 0")["Low_Gain"]
low_win_avg_pips = low_win.mean()
low_loss_avg_pips = low_loss.mean()
low_win_pips = low_win.sum()
low_loss_pips = low_loss.sum()
low_total_pips = low_win_pips + low_loss_pips

low_pct_50_idr = {
    "Win_Count": low_win_count,
    "Loss_Count": low_loss_count,
    "Total_Trades": low_total_trades,
    "Win_Rate": low_win_rate,
    "Avg_Win": low_win_avg_pips,
    "Avg_Loss": low_loss_avg_pips,
    "Win_Pips": low_win_pips,
    "Loss_Pips": low_loss_pips,
    "Total_Pips": low_total_pips
}

# Stats - High + ATR as SL
adr_win_count = df2.query("Bull_BBR == True and ADR_Win > 0")["Bull_BBR"].count()
adr_loss_count = df2.query("Bull_BBR == True and ADR_Loss > 0")["Bull_BBR"].count()
adr_total_trades = adr_win_count + adr_loss_count
adr_win_rate = adr_win_count/adr_total_trades * 100
adr_win = df2.query("Bull_BBR == True and ADR_Gain > 0")["ADR_Gain"]
adr_loss = df2.query("Bull_BBR == True and ADR_Gain < 0")["ADR_Gain"]
adr_win_avg_pips = adr_win.mean()
adr_loss_avg_pips = adr_loss.mean()
adr_win_pips = adr_win.sum()
adr_loss_pips = adr_loss.sum()
adr_total_pips = adr_win_pips + adr_loss_pips

adr_pct_50_idr = {
    "Win_Count": adr_win_count,
    "Loss_Count": adr_loss_count,
    "Total_Trades": adr_total_trades,
    "Win_Rate": adr_win_rate,
    "Avg_Win": adr_win_avg_pips,
    "Avg_Loss": adr_loss_avg_pips,
    "Win_Pips": adr_win_pips,
    "Loss_Pips": adr_loss_pips,
    "Total_Pips": adr_total_pips
}

pd.DataFrame([low_pct_50_idr, adr_pct_50_idr])

,Win_Count,Loss_Count,Total_Trades,Win_Rate,Avg_Win,Avg_Loss,Win_Pips,Loss_Pips,Total_Pips
0,40,181,221,18.099548,0.002840,-0.000789,0.139152,-0.135720,0.003432
1,72,149,221,32.579186,0.002617,-0.002088,0.266932,-0.248427,0.018505

In [116]:
df2[["RSI", "Iday_Range", "RSI_DVG", "SMA32_Slope", "SMA16_Slope",*pct_50_idr_cols]].iloc[0:100].query("ADR_Gain > 0")

,RSI,Iday_Range,RSI_DVG,SMA32_Slope,SMA16_Slope,Low_Win,Low_Loss,ADR_Win,ADR_Loss,Low_TP,ADR_TP,Low_SL,ADR_SL,Low_Gain,ADR_Gain,ADR_Trade_Start,ADR_Trade_End,Low_Trade_Start,Low_Trade_End
Date,,,,,,,,,,,,,,,,,,,
2024-04-24 21:15:00-04:00,57.262904,0.001045,NaN,13.105718,-5.414982,1.0,0.0,1.0,0.0,0.002921,0.002921,-0.000890,-0.001912,0.002921,0.002921,2024-04-24 21:30:00-04:00,2024-04-25 16:45:00-04:00,2024-04-24 21:30:00-04:00,2024-04-25 16:45:00-04:00
2024-04-25 23:45:00-04:00,43.700859,0.002095,NaN,-24.697504,-23.227397,1.0,0.0,1.0,0.0,0.002894,0.002894,-0.000515,-0.001894,0.002894,0.002894,2024-04-26 00:00:00-04:00,2024-04-26 10:30:00-04:00,2024-04-26 00:00:00-04:00,2024-04-26 10:15:00-04:00
2024-04-26 11:15:00-04:00,24.957451,0.009210,NaN,-46.025646,-69.077255,1.0,0.0,1.0,0.0,0.002894,0.002894,-0.000625,-0.001894,0.002894,0.002894,2024-04-26 11:30:00-04:00,2024-04-26 16:45:00-04:00,2024-04-26 11:30:00-04:00,2024-04-26 16:45:00-04:00
2024-04-29 05:15:00-04:00,45.307248,0.006770,NaN,-2.356154,-52.320193,1.0,0.0,1.0,0.0,0.002969,0.002969,-0.000990,-0.001943,0.002969,0.002969,2024-04-29 05:30:00-04:00,2024-04-29 16:45:00-04:00,2024-04-29 05:30:00-04:00,2024-04-29 16:45:00-04:00
2024-04-29 09:45:00-04:00,44.215298,0.006770,NaN,-21.129440,-26.421633,1.0,0.0,1.0,0.0,0.002969,0.002969,-0.000500,-0.001943,0.002969,0.002969,2024-04-29 10:00:00-04:00,2024-04-29 16:45:00-04:00,2024-04-29 10:00:00-04:00,2024-04-29 16:45:00-04:00
2024-04-30 20:30:00-04:00,34.495065,0.001600,NaN,-26.085600,-20.869348,0.0,1.0,1.0,0.0,0.003056,0.003056,-0.000245,-0.002000,-0.000245,0.003056,2024-04-30 20:45:00-04:00,2024-05-01 16:45:00-04:00,2024-04-30 20:45:00-04:00,2024-04-30 21:30:00-04:00
2024-04-30 22:15:00-04:00,37.497094,0.001890,NaN,-29.561365,-21.285059,0.0,1.0,1.0,0.0,0.003056,0.003056,-0.000345,-0.002000,-0.000345,0.003056,2024-04-30 22:30:00-04:00,2024-05-01 16:45:00-04:00,2024-04-30 22:30:00-04:00,2024-04-30 23:00:00-04:00
2024-05-01 03:00:00-04:00,49.917572,0.003105,NaN,-18.756631,-13.642368,1.0,0.0,1.0,0.0,0.003056,0.003056,-0.001280,-0.002000,0.003056,0.003056,2024-05-01 03:15:00-04:00,2024-05-01 16:45:00-04:00,2024-05-01 03:15:00-04:00,2024-05-01 16:45:00-04:00
2024-05-01 07:30:00-04:00,46.290604,0.003195,NaN,4.704365,-9.578423,1.0,0.0,1.0,0.0,0.003056,0.003056,-0.000485,-0.002000,0.003056,0.003056,2024-05-01 07:45:00-04:00,2024-05-01 16:45:00-04:00,2024-05-01 07:45:00-04:00,2024-05-01 16:45:00-04:00
2024-05-02 10:15:00-04:00,36.507088,0.007260,True,-51.258528,-53.343892,1.0,0.0,1.0,0.0,0.003032,0.003032,-0.001405,-0.001985,0.003032,0.003032,2024-05-02 10:30:00-04:00,2024-05-02 16:45:00-04:00,2024-05-02 10:30:00-04:00,2024-05-02 16:45:00-04:00
2024-05-03 03:00:00-04:00,49.306775,0.002690,NaN,6.389316,-11.825477,0.0,1.0,1.0,0.0,0.002930,0.002930,-0.000285,-0.001918,-0.000285,0.002930,2024-05-03 03:15:00-04:00,2024-05-03 16:45:00-04:00,2024-05-03 03:15:00-04:00,2024-05-03 03:15:00-04:00
2024-05-05 20:00:00-04:00,44.031430,0.001545,NaN,-12.225123,-16.370151,1.0,0.0,1.0,0.0,0.002938,0.002938,-0.000350,-0.001923,0.002938,0.002938,2024-05-05 20:15:00-04:00,2024-05-06 16:45:00-04:00,2024-05-05 20:15:00-04:00,2024-05-06 16:45:00-04:00
2024-05-08 03:30:00-04:00,37.488550,0.003735,NaN,-20.425121,-13.529588,0.0,1.0,0.0,1.0,0.002962,0.002962,-0.000345,-0.001939,-0.000345,0.001420,2024-05-08 03:45:00-04:00,2024-05-08 16:45:00-04:00,2024-05-08 03:45:00-04:00,2024-05-08 03:45:00-04:00
2024-05-08 04:00:00-04:00,27.240572,0.004650,True,-30.699723,-29.538782,0.0,1.0,1.0,0.0,0.002962,0.002962,-0.000130,-0.001939,-0.000130,0.002962,2024-05-08 04:15:00-04:00,2024-05-08 16:45:00-04:00,2024-05-08 04:15:00-04:00,2024-05-08 04:15:00-04:00
2024-05-10 10:30:00-04:00,40.222721,0.003770,NaN,-31.117106,-43.531199,0.0,1.0,0.0,1.0,0.002993,0.002993,-0.000795,-0.001959,-0.000795,0.001300,2024-05-10 10:45:00-04:00,2024-05-10 16:45:00-04:00,2024-05-10 10:45:00-04:00,2024-05-10 11:00:00-04:00
2024-05-13 03:15:00-04:00,45.830015,0.001840,NaN,-7.389304,-11.195111,1.0,0.0,1.0,0.0,0.002997,0.002997,-0.000325,-0.001961,0.002997,0.002997,2024-05-13 03:30:00-04:00,2024-05-13 16:45:00-04:00,2024-05-13 03:30:00-04:00,2024-05-13 16:45:00-04:00
2024-05-14 04:30:00-04:00,28.556023,0.005400,NaN,-37.419753,-58.277368,1.0,0.0,1.0,0.0,0.002932,0.002932,-0.001035,-0.001919,0.002932,0.002932,2024-05-14 04:45:00-04:00,2024-05-14 16:45:00-04:00,2024-05-14 04:45:00-04:00,2024-05-14 16:45:00-04:00
2024-05-14 20:00:00-04:00,52.569442,0.000775,NaN,-3.130245,-12.053992,1.0,0.0,1.0,0.0,0.002988,0.002988,-0.000305,-0.001955,0.002988,0.002988,2024-05-14 20:15:00-04:00,2024-05-15 16:45:00-04:00,2024-05-14 20:15:00-04:00,2024-05-15 16:45:00-04:00
2024-05-15 02:45:00-04:00,51.627954,0.001650,NaN,1.670653,-10.504300,1.0,0.0,1.0,0.0,0.002988,0.002988,-0.000540,-0.001955,0.002988,0.002988,2024-05-15 03:00:00-04:00,2024-05-15 16:45:00-04:00,2024-05-15 03:00:00-04:00,2024-05-15 16:45:00-04:00
2024-05-16 08:00:00-04:00,35.248893,0.004660,NaN,-33.752001,-40.433764,0.0,1.0,0.0,1.0,0.003000,0.003000,-0.000435,-0.001964,-0.000435,0.001085,2024-05-16 08:15:00-04:00,2024-05-16 16:45:00-04:00,2024-05-16 08:15:00-04:00,2024-05-16 08:30:00-04:00
2024-05-16 09:45:00-04:00,33.875578,0.005655,NaN,-37.588777,-42.347868,0.0,1.0,1.0,0.0,0.003000,0.003000,-0.000350,-0.001964,-0.000350,0.003000,2024-05-16 10:00:00-04:00,2024-05-16 16:45:00-04:00,2024-05-16 10:00:00-04:00,2024-05-16 10:00:00-04:00
2024-05-16 21:30:00-04:00,41.853577,0.001845,NaN,-14.736218,-21.285059,0.0,1.0,1.0,0.0,0.003012,0.003012,-0.000520,-0.001971,-0.000520,0.003012,2024-05-16 21:45:00-04:00,2024-05-17 16:45:00-04:00,2024-05-16 21:45:00-04:00,2024-05-16 22:00:00-04:00
2024-05-17 04:15:00-04:00,39.356383,0.002415,NaN,-17.571259,-14.819918,0.0,1.0,1.0,0.0,0.003012,0.003012,-0.000260,-0.001971,-0.000260,0.003012,2024-05-17 04:30:00-04:00,2024-05-17 16:45:00-04:00,2024-05-17 04:30:00-04:00,2024-05-17 04:30:00-04:00
2024-05-17 04:45:00-04:00,38.038554,0.002790,NaN,-18.192893,-16.699244,0.0,1.0,1.0,0.0,0.003012,0.003012,-0.000270,-0.001971,-0.000270,0.003012,2024-05-17 05:00:00-04:00,2024-05-17 16:45:00-04:00,2024-05-17 05:00:00-04:00,2024-05-17 07:15:00-04:00
2024-05-19 17:45:00-04:00,52.372022,0.000590,NaN,32.813586,-22.974921,0.0,1.0,0.0,1.0,0.003002,0.003002,-0.000345,-0.001964,-0.000345,0.000800,2024-05-19 18:00:00-04:00,2024-05-20 16:45:00-04:00,2024-05-19 18:00:00-04:00,2024-05-20 03:15:00-04:00
2024-05-20 03:30:00-04:00,42.998226,0.002185,NaN,-14.064326,-21.285059,0.0,1.0,0.0,1.0,0.003002,0.003002,-0.000505,-0.001964,-0.000505,0.000880,2024-05-20 03:45:00-04:00,2024-05-20 16:45:00-04:00,2024-05-20 03:45:00-04:00,2024-05-20 03:45:00-04:00
2024-05-20 22:15:00-04:00,42.979084,0.001450,NaN,-9.897288,-17.733843,0.0,1.0,0.0,1.0,0.002983,0.002983,-0.000570,-0.001952,-0.000570,0.000590,2024-05-20 22:30:00-04:00,2024-05-21 16:45:00-04:00,2024-05-20 22:30:00-04:00,2024-05-21 09:00:00-04:00
2024-05-22 07:45:00-04:00,40.946229,0.006110,NaN,-7.535995,-60.775581,1.0,0.0,1.0,0.0,0.002957,0.002957,-0.000660,-0.001936,0.002957,0.002957,2024-05-22 08:00:00-04:00,2024-05-22 16:45:00-04:00,2024-05-22 08:00:00-04:00,2024-05-22 16:45:00-04:00
2024-05-23 05:15:00-04:00,40.246057,0.003355,NaN,-10.099882,-29.221558,1.0,0.0,1.0,0.0,0.002796,0.002796,-0.000185,-0.001830,0.002796,0.002796,2024-05-23 05:30:00-04:00,2024-05-23 13:45:00-04:00,2024-05-23 05:30:00-04:00,2024-05-23 09:45:00-04:00
2024-05-23 14:00:00-04:00,34.882128,0.005540,NaN,-30.919852,-39.451534,0.0,1.0,0.0,1.0,0.002796,0.002796,-0.000565,-0.001830,-0.000565,0.000105,2024-05-23 14:15:00-04:00,2024-05-23 16:45:00-04:00,2024-05-23 14:15:00-04:00,2024-05-23 14:15:00-04:00
2024-05-23 20:15:00-04:00,40.551748,0.001090,NaN,-24.845120,-3.457417,0.0,1.0,1.0,0.0,0.002788,0.002788,-0.000220,-0.001824,-0.000220,0.002788,2024-05-23 20:30:00-04:00,2024-05-24 16:45:00-04:00,2024-05-23 20:30:00-04:00,2024-05-23 20:30:00-04:00
2024-05-27 02:15:00-04:00,55.189487,0.000965,NaN,-3.159997,-3.635781,0.0,1.0,1.0,0.0,0.002715,0.002715,-0.000650,-0.001777,-0.000650,0.002715,2024-05-27 02:30:00-04:00,2024-05-27 16:45:00-04:00,2024-05-27 02:30:00-04:00,2024-05-27 04:00:00-04:00
2024-05-28 04:45:00-04:00,43.146932,0.002095,NaN,-7.359954,-25.310247,1.0,0.0,1.0,0.0,0.002692,0.002692,-0.000625,-0.001761,0.002692,0.002692,2024-05-28 05:00:00-04:00,2024-05-28 16:45:00-04:00,2024-05-28 05:00:00-04:00,2024-05-28 13:45:00-04:00
2024-05-29 19:30:00-04:00,34.274644,0.000950,NaN,-16.808692,-11.137667,0.0,1.0,1.0,0.0,0.002676,0.002676,-0.000130,-0.001751,-0.000130,0.002676,2024-05-29 19:45:00-04:00,2024-05-30 16:45:00-04:00,2024-05-29 19:45:00-04:00,2024-05-29 19:45:00-04:00
2024-05-29 20:45:00-04:00,33.342245,0.001515,NaN,-22.974921,-20.241452,0.0,1.0,1.0,0.0,0.002676,0.002676,-0.000235,-0.001751,-0.000235,0.002676,2024-05-29 21:00:00-04:00,2024-05-30 16:45:00-04:00,2024-05-29 21:00:00-04:00,2024-05-29 22:45:00-04:00
2024-05-30 02:00:00-04:00,42.852949,0.002145,NaN,-15.181867,-20.293974,0.0,1.0,1.0,0.0,0.002676,0.002676,-0.000590,-0.001751,-0.000590,0.002676,2024-05-30 02:15:00-04:00,2024-05-30 16:45:00-04:00,2024-05-30 02:15:00-04:00,2024-05-30 02:30:00-04:00
2024-05-30 15:45:00-04:00,49.248560,0.006620,NaN,20.293974,-19.978314,0.0,1.0,0.0,1.0,0.002676,0.002676,-0.000235,-0.001751,-0.000235,0.000085,2024-05-30 16:00:00-04:00,2024-05-30 16:45:00-04:00,2024-05-30 16:00:00-04:00,2024-05-30 16:00:00-04:00
2024-05-31 02:15:00-04:00,40.788699,0.002145,True,-19.978314,-17.027207,0.0,1.0,1.0,0.0,0.002695,0.002695,-0.000230,-0.001764,-0.000230,0.002695,2024-05-31 02:30:00-04:00,2024-05-31 16:45:00-04:00,2024-05-31 02:30:00-04:00,2024-05-31 03:00:00-04:00
2024-05-31 03:30:00-04:00,33.403026,0.003420,True,-27.323891,-31.269961,0.0,1.0,1.0,0.0,0.002695,0.002695,-0.000310,-0.001764,-0.000310,0.002695,2024-05-31 03:45:00-04:00,2024-05-31 16:45:00-04:00,2024-05-31 03:45:00-04:00,2024-05-31 03:45:00-04:00
2024-06-03 05:15:00-04:00,27.104875,0.006190,True,-47.400214,-60.488501,1.0,0.0,1.0,0.0,0.002650,0.002650,-0.000665,-0.001734,0.002650,0.002650,2024-06-03 05:30:00-04:00,2024-06-03 16:45:00-04:00,2024-06-03 05:30:00-04:00,2024-06-03 16:45:00-04:00
2024-06-05 07:15:00-04:00,49.256677,0.001800,NaN,-7.506665,-10.446589,0.0,1.0,0.0,1.0,0.002612,0.002612,-0.000485,-0.001710,-0.000485,0.001515,2024-06-05 07:30:00-04:00,2024-06-05 16:45:00-04:00,2024-06-05 07:30:00-04:00,2024-06-05 10:00:00-04:00
2024-06-06 21:30:00-04:00,49.610256,0.001175,NaN,2.921936,-10.677301,0.0,1.0,1.0,0.0,0.002571,0.002571,-0.000490,-0.001683,-0.000490,0.002571,2024-06-06 21:45:00-04:00,2024-06-07 08:30:00-04:00,2024-06-06 21:45:00-04:00,2024-06-07 02:00:00-04:00
2024-06-07 02:15:00-04:00,52.397244,0.001360,NaN,-7.770493,-6.123933,0.0,1.0,1.0,0.0,0.002571,0.002571,-0.000680,-0.001683,-0.000680,0.002571,2024-06-07 02:30:00-04:00,2024-06-07 08:30:00-04:00,2024-06-07 02:30:00-04:00,2024-06-07 04:45:00-04:00
2024-06-11 10:00:00-04:00,39.233715,0.004365,NaN,-15.459448,-43.656422,0.0,1.0,1.0,0.0,0.002532,0.002532,-0.000865,-0.001657,-0.000865,0.002532,2024-06-11 10:15:00-04:00,2024-06-11 16:45:00-04:00,2024-06-11 10:15:00-04:00,2024-06-11 10:45:00-04:00
2024-06-11 20:15:00-04:00,50.684485,0.000610,NaN,16.370151,-8.705794,0.0,1.0,1.0,0.0,0.002496,0.002496,-0.000110,-0.001634,-0.000110,0.002496,2024-06-11 20:30:00-04:00,2024-06-12 16:45:00-04:00,2024-06-11 20:30:00-04:00,2024-06-11 20:30:00-04:00
2024-06-11 21:00:00-04:00,46.086978,0.000970,NaN,6.772160,-11.882642,1.0,0.0,1.0,0.0,0.002496,0.002496,-0.000175,-0.001634,0.002496,0.002496,2024-06-11 21:15:00-04:00,2024-06-12 16:45:00-04:00,2024-06-11 21:15:00-04:00,2024-06-12 16:45:00-04:00
2024-06-13 08:00:00-04:00,33.294664,0.003980,True,-22.211831,-45.326384,1.0,0.0,1.0,0.0,0.002551,0.002551,-0.000195,-0.001670,0.002551,0.002551,2024-06-13 08:15:00-04:00,2024-06-13 12:00:00-04:00,2024-06-13 08:15:00-04:00,2024-06-13 10:30:00-04:00
2024-06-14 09:30:00-04:00,27.445143,0.010560,True,-61.001601,-59.883676,0.0,1.0,1.0,0.0,0.002547,0.002547,-0.000275,-0.001667,-0.000275,0.002547,2024-06-14 09:45:00-04:00,2024-06-14 16:45:00-04:00,2024-06-14 09:45:00-04:00,2024-06-14 09:45:00-04:00
2024-06-17 02:15:00-04:00,35.402929,0.002485,NaN,-14.708304,-27.087852,0.0,1.0,1.0,0.0,0.002548,0.002548,-0.000750,-0.001667,-0.000750,0.002548,2024-06-17 02:30:00-04:00,2024-06-17 16:45:00-04:00,2024-06-17 02:30:00-04:00,2024-06-17 03:30:00-04:00
2024-06-17 03:00:00-04:00,38.389671,0.002485,NaN,-17.815025,-27.182388,0.0,1.0,1.0,0.0,0.002548,0.002548,-0.000375,-0.001667,-0.000375,0.002548,2024-06-17 03:15:00-04:00,2024-06-17 16:45:00-04:00,2024-06-17 03:15:00-04:00,2024-06-17 03:30:00-04:00
2024-06-17 03:45:00-04:00,38.905047,0.002780,NaN,-17.733843,-32.729193,0.0,1.0,1.0,0.0,0.002548,0.002548,-0.000660,-0.001667,-0.000660,0.002548,2024-06-17 04:00:00-04:00,2024-06-17 16:45:00-04:00,2024-06-17 04:00:00-04:00,2024-06-17 06:15:00-04:00
2024-06-18 04:00:00-04:00,33.349708,0.003935,NaN,-33.607350,-35.430266,0.0,1.0,1.0,0.0,0.002541,0.002541,-0.000445,-0.001663,-0.000445,0.002541,2024-06-18 04:15:00-04:00,2024-06-18 16:45:00-04:00,2024-06-18 04:15:00-04:00,2024-06-18 04:30:00-04:00
2024-06-19 02:00:00-04:00,63.217885,0.002665,NaN,0.238731,0.119366,0.0,1.0,0.0,1.0,0.002519,0.002519,-0.001620,-0.001648,0.000195,0.000195,2024-06-19 02:15:00-04:00,2024-06-19 16:45:00-04:00,2024-06-19 02:15:00-04:00,2024-06-19 16:45:00-04:00
2024-06-21 11:00:00-04:00,42.161612,0.005380,NaN,-27.135140,-14.372779,0.0,1.0,0.0,1.0,0.002494,0.002494,-0.000580,-0.001632,-0.000580,0.001165,2024-06-21 11:15:00-04:00,2024-06-21 16:45:00-04:00,2024-06-21 11:15:00-04:00,2024-06-21 11:15:00-04:00
2024-06-23 22:15:00-04:00,44.505690,0.001275,NaN,-8.647469,-20.398909,1.0,0.0,1.0,0.0,0.002513,0.002513,-0.000320,-0.001645,0.002513,0.002513,2024-06-23 22:30:00-04:00,2024-06-24 16:45:00-04:00,2024-06-23 22:30:00-04:00,2024-06-24 16:45:00-04:00
2024-06-25 07:45:00-04:00,41.119947,0.002660,NaN,-16.315193,-18.542311,0.0,1.0,0.0,1.0,0.002531,0.002531,-0.000490,-0.001656,-0.000490,0.000375,2024-06-25 08:00:00-04:00,2024-06-25 16:45:00-04:00,2024-06-25 08:00:00-04:00,2024-06-25 08:30:00-04:00