In [353]:
import pandas as pd 
import numpy as np
import os
from pandas import DataFrame

PATH = os.getcwd()
FILE = "../output/FE_GBPUSD_15mins_1yr_End_20260311.csv"
df = pd.read_csv(FILE)
df["Date"] = pd.DatetimeIndex(df["Date"], tz="US/Eastern")
df.set_index("Date", inplace=True)
df

,Open,High,Low,Close,Idx,Body,Range,UWick,LWick,Close_%High,Open_%High,Iday_Idx,Iday_High,Iday_Low,Iday_Range,Close_%DHigh,Open_%DHigh,Yday_High,Yday_Low,Day_Idx,ADR,...,BB_Upper_16_2,BB_Lower_16_2,RSI,Sig_High,Sig_Low,SMA_Trend,SMA16_Slope,SMA32_Slope,Hammer,Shooting_Star,Bull_Engulf,Bear_Engulf,Dark_Cloud,Piercing,Bull_BBR,Bear_BBR,ILR,IHR,S_R,BBU_BO,BBL_BO
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2025-03-11 17:15:00-04:00,1.295630,1.295685,1.295180,1.295335,0,0.000295,0.000505,0.000055,0.000155,0.693069,0.108911,0,1.295685,1.295180,0.000505,0.693069,0.108911,NaN,NaN,0,NaN,...,1.338512,1.338512,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-11 17:30:00-04:00,1.295335,1.295360,1.294550,1.294780,1,0.000555,0.000810,0.000025,0.000230,0.716049,0.030864,1,1.295685,1.294550,0.001135,0.797357,0.308370,NaN,NaN,0,NaN,...,1.335580,1.335580,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-11 17:45:00-04:00,1.294780,1.294800,1.294590,1.294655,2,0.000125,0.000210,0.000020,0.000065,0.690476,0.095238,2,1.295685,1.294550,0.001135,0.907489,0.797357,NaN,NaN,0,NaN,...,1.332706,1.332706,NaN,NaN,NaN,0,-87.042245,-84.097964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-11 18:00:00-04:00,1.294655,1.295075,1.294470,1.294995,3,0.000340,0.000605,0.000080,0.000185,0.132231,0.694215,3,1.295685,1.294470,0.001215,0.567901,0.847737,NaN,NaN,0,NaN,...,1.329829,1.329829,NaN,NaN,NaN,0,-87.014011,-84.089748,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-11 18:15:00-04:00,1.294995,1.295000,1.294595,1.294665,4,0.000330,0.000405,0.000005,0.000070,0.827160,0.012346,4,1.295685,1.294470,0.001215,0.839506,0.567901,NaN,NaN,0,NaN,...,1.326948,1.326948,NaN,NaN,NaN,-2,-87.017085,-84.255226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-11 15:45:00-04:00,1.341870,1.342230,1.341675,1.341855,24575,0.000015,0.000555,0.000360,0.000180,0.675676,0.648649,90,1.345760,1.339345,0.006415,0.608730,0.606391,1.34834,1.341225,255,0.009747,...,1.342075,1.340328,51.591073,1.34576,1.339345,1,38.477385,-13.473158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-11 16:00:00-04:00,1.341855,1.341855,1.341475,1.341765,24576,0.000090,0.000380,0.000000,0.000290,0.236842,0.000000,91,1.345760,1.339345,0.006415,0.622759,0.608730,1.34834,1.341225,255,0.009747,...,1.342156,1.340346,50.971669,1.34576,1.339345,1,31.007621,-10.331105,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-11 16:15:00-04:00,1.341765,1.341770,1.341560,1.341580,24577,0.000185,0.000210,0.000005,0.000020,0.904762,0.023810,92,1.345760,1.339345,0.006415,0.651598,0.622759,1.34834,1.341225,255,0.009747,...,1.342123,1.340529,49.664290,1.34576,1.339345,2,22.568992,-12.992437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-11 16:30:00-04:00,1.341580,1.341665,1.341260,1.341265,24578,0.000315,0.000405,0.000085,0.000005,0.987654,0.209877,93,1.345760,1.339345,0.006415,0.700701,0.651598,1.34834,1.341225,255,0.009747,...,1.342090,1.340634,47.453690,1.34576,1.339345,2,20.241452,-9.229886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-11 16:45:00-04:00,1.341265,1.341340,1.341000,1.341185,24579,0.000080,0.000340,0.000075,0.000185,0.455882,0.220588,94,1.345760,1.339345,0.006415,0.713172,0.700701,1.34834,1.341225,255,0.009747,...,1.342086,1.340656,46.888313,1.34576,1.339345,2,8.589126,6.624982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Get al columns

In [305]:
df.columns

Index(['Open', 'High', 'Low', 'Close', 'Idx', 'Body', 'Range', 'UWick',
       'LWick', 'Close_%High', 'Open_%High', 'Iday_Idx', 'Iday_High',
       'Iday_Low', 'Iday_Range', 'Close_%DHigh', 'Open_%DHigh', 'Yday_High',
       'Yday_Low', 'Day_Idx', 'ADR', 'ATR', 'SMA4', 'SMA16', 'SMA32',
       'BB_Upper_16_2', 'BB_Lower_16_2', 'RSI', 'Sig_High', 'Sig_Low',
       'SMA_Trend', 'SMA16_Slope', 'SMA32_Slope', 'Hammer', 'Shooting_Star',
       'Bull_Engulf', 'Bear_Engulf', 'Dark_Cloud', 'Piercing', 'Bull_BBR',
       'Bear_BBR', 'ILR', 'IHR', 'S_R', 'BBU_BO', 'BBL_BO'],
      dtype='object')

Get all rows that have `Bear_BBR` as True

In [342]:
pd.options.display.max_rows = 100
cols = ['Idx','Day_Idx', 'Open', 'High', 'Low', 'Close', 'Body', 'Range', 'ATR',
        'Close_%High', 'Open_%High', 'Iday_High', 'Iday_Low', 
        'Iday_Range', 'ADR', 'Close_%DHigh', 'Open_%DHigh', 
        'Yday_High', 'Yday_Low', 'SMA4', 'SMA16', 'SMA32',
       'BB_Upper_16_2', 'BB_Lower_16_2', 'RSI', 'Sig_High', 'Sig_Low',
       'SMA_Trend', 'SMA16_Slope', 'SMA32_Slope', 'Bear_BBR', 'Shooting_Star',
       'Bear_Engulf', 'Dark_Cloud', 'IHR', 'S_R', 'BBU_BO', 
       'ILR', 'Bull_BBR', 'Hammer', 'Bull_Engulf', 'BBL_BO']
pd.options.display.max_columns = len(cols)
bbu_reversal = df[cols]#.query("Bear_BBR == True")
bbu_reversal.query("Bear_BBR == True")

,Idx,Day_Idx,Open,High,Low,Close,Body,Range,ATR,Close_%High,Open_%High,Iday_High,Iday_Low,Iday_Range,ADR,Close_%DHigh,Open_%DHigh,Yday_High,Yday_Low,SMA4,SMA16,SMA32,BB_Upper_16_2,BB_Lower_16_2,RSI,Sig_High,Sig_Low,SMA_Trend,SMA16_Slope,SMA32_Slope,Bear_BBR,Shooting_Star,Bear_Engulf,Dark_Cloud,IHR,S_R,BBU_BO,ILR,Bull_BBR,Hammer,Bull_Engulf,BBL_BO
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2025-03-12 05:00:00-04:00,47,0,1.294210,1.294530,1.293750,1.293895,0.000315,0.000780,0.000939,0.814103,0.410256,1.295685,1.291365,0.004320,NaN,0.414352,0.341435,NaN,NaN,1.293565,1.292857,1.292971,1.294028,1.291687,57.242400,1.295685,1.291365,1,35.509439,6.123933,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-12 07:30:00-04:00,57,0,1.295655,1.296145,1.295100,1.295430,0.000225,0.001045,0.000943,0.684211,0.468900,1.296145,1.291365,0.004780,NaN,0.149582,0.102510,NaN,NaN,1.294770,1.293912,1.293191,1.295513,1.292310,63.957243,1.295685,1.291365,2,50.534430,28.026001,True,NaN,NaN,NaN,True,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-12 12:15:00-04:00,76,0,1.298070,1.298265,1.297430,1.297660,0.000410,0.000835,0.001290,0.724551,0.233533,1.299000,1.291365,0.007635,NaN,0.175508,0.121807,NaN,NaN,1.297094,1.295018,1.294655,1.297964,1.292071,65.991526,1.299000,1.291365,2,48.524029,46.140500,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-12 22:15:00-04:00,115,1,1.297265,1.297350,1.296885,1.297010,0.000255,0.000465,0.000436,0.731183,0.182796,1.297350,1.296075,0.001275,NaN,0.266667,0.066667,1.299000,1.291365,1.296846,1.296547,1.296601,1.297143,1.295951,57.141452,NaN,NaN,1,13.473158,1.909152,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-13 04:30:00-04:00,140,1,1.296485,1.296485,1.295535,1.295910,0.000575,0.000950,0.000938,0.605263,0.000000,1.297350,1.294155,0.003195,NaN,0.450704,0.270736,1.299000,1.291365,1.295755,1.295502,1.295990,1.296433,1.294571,50.937783,1.297350,1.296075,0,4.051684,-0.029842,True,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-06 16:15:00-05:00,24292,252,1.340140,1.340270,1.339910,1.339925,0.000215,0.000360,0.001030,0.958333,0.361111,1.340980,1.331155,0.009825,0.010079,0.107379,0.085496,1.338710,1.329750,1.339426,1.339091,1.337920,1.340132,1.338050,58.904509,1.340980,1.331155,2,19.978314,46.297646,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-09 02:00:00-04:00,24330,253,1.333365,1.334075,1.332485,1.332730,0.000635,0.001590,0.001371,0.845912,0.446541,1.335175,1.328310,0.006865,0.009884,0.356154,0.263656,1.341630,1.331155,1.332796,1.330734,1.330619,1.333298,1.328170,55.186083,1.335175,1.328310,2,59.302734,0.835504,True,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-09 09:30:00-04:00,24360,253,1.337745,1.338270,1.336690,1.337575,0.000170,0.001580,0.001383,0.439873,0.332278,1.338270,1.328310,0.009960,0.009884,0.069779,0.052711,1.341630,1.331155,1.336907,1.335188,1.333955,1.337667,1.332710,66.050386,1.336365,1.328310,2,56.383248,46.819677,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-09 11:15:00-04:00,24367,253,1.339725,1.339780,1.338540,1.339030,0.000695,0.001240,0.001635,0.604839,0.044355,1.340070,1.328310,0.011760,0.009884,0.088435,0.029337,1.341630,1.331155,1.338403,1.336594,1.335089,1.339627,1.333561,65.245502,1.336365,1.328310,2,60.917219,56.519957,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-10 02:45:00-04:00,24428,254,1.345660,1.345775,1.344640,1.345030,0.000630,0.001135,0.000777,0.656388,0.101322,1.345775,1.341360,0.004415,0.010196,0.168743,0.026048,1.344715,1.328310,1.344819,1.343000,1.343020,1.345412,1.340588,63.597555,1.344860,1.341360,1,49.774958,26.133723,True,NaN,NaN,True,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN

- Create new signal dataframe
- index is the signal id e.g. 0,1,2...
- columns = 
    - datetime of signal
    - max price up from start of signal until end of day
    - max price down from signal until start of day
    - lowest low from signal until EOD
    - lowest close from signal until EOD
    - highest high from signal until EOD
    - highest close from signal until EOD
    - Close at EOD

In [410]:

def bearish_bbr_metrics(df: DataFrame, bear_bbr_signal_idx: list):
    """Return a new dataframe with signal metrics"""

    signal = []
    for signal_idx in bear_bbr_signal_idx:
        row = df.iloc[signal_idx]
        s = {}
        START = row.name
        TD = pd.Timedelta(minutes=15)
        s["Date"] = START
        s["Entry_Price"] = row["Close"] # signal price
        day = row["Day_Idx"]
        window = df.query(f"Day_Idx == {day}") # only get df data from the same day as signal
        signal_window = window[START:]
        Max_High = signal_window[START+TD:]["High"].max() # Max high from signal until EOD
        Min_Low = signal_window[START+TD:]["Low"].min() # Min low from signal until EOD
        s["D_Max_Up"] = s["Entry_Price"] - Max_High # Max price gain from signal until EOD
        s["D_Max_Down"] = s["Entry_Price"] - Min_Low # Max price loss from signal until EOD
        D_Close = signal_window.iloc[-1]["Close"] # Closing price at EOD
        s["D_Gain"] = s["Entry_Price"] - D_Close # Gain at EOD from signal price


        if signal_window.query(f"Close > {row["High"]}").empty is False:
            # If price closed above signal price within the day, 
            # get the dataframe between start and failure time
            EXIT = signal_window[START:].query(f"Close > {row["High"]}").iloc[0].name
            entry_window = signal_window[START:EXIT]
        else:
            # If price didn't close above signal price within the day
            # get the dataframe from signal time until EOD
            entry_window = signal_window

        # If the price fell to the SMA16 after the signal
        # calcuate the gain
        below_sma16 = entry_window.query("Low < SMA16")
        if below_sma16.empty is False:
            s["To_SMA16"] = s["Entry_Price"] - below_sma16.iloc[0]["SMA16"] 
        else: 
            s["To_SMA16"] = 0

        # If the price fell to the SMA32 after the signal
        # calcuate the gain
        below_sma32 = entry_window.query("Low < SMA32")
        if below_sma32.empty is False:
            s["To_SMA32"] = s["Entry_Price"] - below_sma32.iloc[0]["SMA32"]
        else:
            s["To_SMA32"] = 0

        # If the price fell to the BB_Lower_16_2 after the signal
        # calcuate the gain
        below_bbl = entry_window.query("Low < BB_Lower_16_2")
        if below_bbl.empty is False:
            s["To_BBL_16_2"] = s["Entry_Price"] - below_bbl.iloc[0]["BB_Lower_16_2"]
        else:
            s["To_BBL_16_2"] = 0

        # If the price fell to the Sig_Low after the signal
        # calcuate the gain
        below_sig_low = entry_window.query("Low < Sig_Low")
        if below_sig_low.empty is False:
            s["To_Sig_Low"] = s["Entry_Price"] - below_sig_low.iloc[0]["Sig_Low"]
        else:
            s["To_Sig_Low"] = 0

        below_sr = entry_window.query("S_R > 3")["Sig_Low"].unique()
        for i in range(len(below_sr)):
            s[f"To_S_{i}"] = s["Entry_Price"] - below_sr[i]


        # Check if bullish signals occured during winddow
        NULL_Timestamp = pd.Timestamp(0, tz="US/Eastern")
        to_bull_bbr = entry_window.query("Bull_BBR == True")
        if to_bull_bbr.empty is False:
            s["To_Bull_BBR"] = s["Entry_Price"] - to_bull_bbr.iloc[0]["Close"]
            to_bull_bbr_time_stamp = to_bull_bbr.iloc[0].name
        else:
            s["To_Bull_BBR"] = 0
            to_bull_bbr_time_stamp = NULL_Timestamp

        to_bull_engulf = entry_window.query("Bull_Engulf == True")
        if to_bull_engulf.empty is False:
            s["To_Bull_Engulf"] = s["Entry_Price"] - to_bull_engulf.iloc[0]["Close"]
            to_bull_engulf_time_stamp = to_bull_engulf.iloc[0].name
        else:
            s["To_Bull_Engulf"] = 0
            to_bull_engulf_time_stamp = NULL_Timestamp

        to_ilr = entry_window.query("ILR == True")
        if to_ilr.empty is False:
            s["To_ILR"] = s["Entry_Price"] - to_ilr.iloc[0]["Close"]
            to_ilr_time_stamp = to_ilr.iloc[0].name
        else:
            s["To_ILR"] = 0
            to_ilr_time_stamp = NULL_Timestamp

        first_bullish_signal = min([to_bull_bbr_time_stamp, to_bull_engulf_time_stamp, to_ilr_time_stamp])
        if first_bullish_signal > NULL_Timestamp:
            s["To_Bull_0"] = s["Entry_Price"] - entry_window.loc[first_bullish_signal]["Close"]
        else:
            s["To_Bull_0"] = 0

        # append other useful df metrics to new df
        s["SMA_Trend"] = row["SMA_Trend"]
        s["SMA16_Slope"] = row["SMA16_Slope"]
        s["SMA32_Slope"] = row["SMA32_Slope"]
        s["RSI"] = row["RSI"]
        s["IHR"] = row["IHR"]
        s["Dark_Cloud"] = row["Dark_Cloud"]
        s["Shooting_Star"] = row["Shooting_Star"]
        s["Bear_Engulf"] = row["Bear_Engulf"]
        s["Iday_Range"] = row["Iday_Range"]
        s["ADR"] = row["ADR"]
        s["Close_%DHigh"] = row["Close_%DHigh"]

        signal.append(s)
    sdf = pd.DataFrame(signal)
    return sdf

signal_idx_list = bbu_reversal.query("Bear_BBR == True")["Idx"].to_list()
bearish_bbr_df = bearish_bbr_metrics(bbu_reversal, signal_idx_list)
bearish_bbr_df

,Date,Entry_Price,D_Max_Up,D_Max_Down,D_Gain,To_SMA16,To_SMA32,To_BBL_16_2,To_Sig_Low,To_Bull_BBR,To_Bull_Engulf,To_ILR,To_Bull_0,SMA_Trend,SMA16_Slope,SMA32_Slope,RSI,IHR,Dark_Cloud,Shooting_Star,Bear_Engulf,Iday_Range,ADR,Close_%DHigh,To_S_0,To_S_1,To_S_2
0,2025-03-12 05:00:00-04:00,1.293895,-0.005105,0.001435,-0.002435,0.000602,0.000906,0.000000,0.000000,0.000000,-0.000305,0.000000,0.000000,1,35.509439,6.123933,57.242400,NaN,NaN,NaN,NaN,0.004320,NaN,0.414352,NaN,NaN,NaN
1,2025-03-12 07:30:00-04:00,1.295430,-0.003570,0.002970,-0.000900,0.001065,0.001654,0.002231,0.000000,0.000000,0.000000,0.000000,0.000000,2,50.534430,28.026001,63.957243,True,NaN,NaN,NaN,0.004780,NaN,0.149582,NaN,NaN,NaN
2,2025-03-12 12:15:00-04:00,1.297660,-0.000450,0.001675,0.001330,0.000862,0.001504,0.001517,0.000000,0.000000,0.000000,0.000000,0.000000,2,48.524029,46.140500,65.991526,NaN,NaN,NaN,NaN,0.007635,NaN,0.175508,NaN,NaN,NaN
3,2025-03-12 22:15:00-04:00,1.297010,-0.000120,0.004910,0.001915,0.000418,0.000410,0.001155,0.000935,0.001905,0.001055,0.000525,0.001905,1,13.473158,1.909152,57.141452,NaN,NaN,NaN,NaN,0.001275,NaN,0.266667,0.000935,0.002855,NaN
4,2025-03-13 04:30:00-04:00,1.295910,-0.000980,0.003810,0.000815,0.000498,-0.000080,0.001447,-0.000165,0.001785,-0.000045,0.000000,0.000000,0,4.051684,-0.029842,50.937783,NaN,NaN,NaN,NaN,0.003195,NaN,0.450704,-0.000165,0.001755,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,2026-03-06 16:15:00-05:00,1.339925,-0.001705,0.000855,-0.000155,0.000737,0.000000,0.000000,0.000000,0.000000,-0.000155,0.000000,0.000000,2,19.978314,46.297646,58.904509,NaN,NaN,NaN,NaN,0.009825,0.010079,0.107379,NaN,NaN,NaN
355,2026-03-09 02:00:00-04:00,1.332730,-0.011985,0.002475,-0.010660,0.001554,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,59.302734,0.835504,55.186083,NaN,True,NaN,NaN,0.006865,0.009884,0.356154,NaN,NaN,NaN
356,2026-03-09 09:30:00-04:00,1.337575,-0.007140,0.002990,-0.005815,0.002020,0.000000,0.000000,0.000000,0.000000,0.000460,0.000000,0.000000,2,56.383248,46.819677,66.050386,NaN,NaN,NaN,NaN,0.009960,0.009884,0.069779,0.009265,NaN,NaN
357,2026-03-09 11:15:00-04:00,1.339030,-0.005685,0.000830,-0.004360,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,60.917219,56.519957,65.245502,NaN,NaN,NaN,NaN,0.011760,0.009884,0.088435,NaN,NaN,NaN
358,2026-03-10 02:45:00-04:00,1.345030,-0.003310,0.003805,0.003225,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1,49.774958,26.133723,63.597555,NaN,True,NaN,NaN,0.004415,0.010196,0.168743,NaN,NaN,NaN

## Signal Stats

In [402]:
total_signals_count = bearish_bbr_df[bearish_bbr_df.columns[0]].count()
day_closed_lower = bearish_bbr_df.query("D_Max_Up.abs() < D_Max_Down")
day_closed_lower_count =  day_closed_lower[day_closed_lower.columns[0]].count()
# percentage of where price fell further than the max it went against the entry price
day_closed_lower_pct = round(day_closed_lower_count / total_signals_count * 100, 2)
day_closed_lower_pct

np.float64(47.63)

In [414]:

pd.options.display.max_rows = 500
bearish_bbr_df

,Date,Entry_Price,D_Max_Up,D_Max_Down,D_Gain,To_SMA16,To_SMA32,To_BBL_16_2,To_Sig_Low,To_Bull_BBR,To_Bull_Engulf,To_ILR,To_Bull_0,SMA_Trend,SMA16_Slope,SMA32_Slope,RSI,IHR,Dark_Cloud,Shooting_Star,Bear_Engulf,Iday_Range,ADR,Close_%DHigh,To_S_0,To_S_1,To_S_2
0,2025-03-12 05:00:00-04:00,1.293895,-0.005105,0.001435,-0.002435,0.000602,0.000906,0.000000,0.000000,0.000000,-0.000305,0.000000,0.000000,1,3.550944e+01,6.123933,57.242400,NaN,NaN,NaN,NaN,0.004320,NaN,0.414352,NaN,NaN,NaN
1,2025-03-12 07:30:00-04:00,1.295430,-0.003570,0.002970,-0.000900,0.001065,0.001654,0.002231,0.000000,0.000000,0.000000,0.000000,0.000000,2,5.053443e+01,28.026001,63.957243,True,NaN,NaN,NaN,0.004780,NaN,0.149582,NaN,NaN,NaN
2,2025-03-12 12:15:00-04:00,1.297660,-0.000450,0.001675,0.001330,0.000862,0.001504,0.001517,0.000000,0.000000,0.000000,0.000000,0.000000,2,4.852403e+01,46.140500,65.991526,NaN,NaN,NaN,NaN,0.007635,NaN,0.175508,NaN,NaN,NaN
3,2025-03-12 22:15:00-04:00,1.297010,-0.000120,0.004910,0.001915,0.000418,0.000410,0.001155,0.000935,0.001905,0.001055,0.000525,0.001905,1,1.347316e+01,1.909152,57.141452,NaN,NaN,NaN,NaN,0.001275,NaN,0.266667,0.000935,0.002855,NaN
4,2025-03-13 04:30:00-04:00,1.295910,-0.000980,0.003810,0.000815,0.000498,-0.000080,0.001447,-0.000165,0.001785,-0.000045,0.000000,0.000000,0,4.051684e+00,-0.029842,50.937783,NaN,NaN,NaN,NaN,0.003195,NaN,0.450704,-0.000165,0.001755,NaN
5,2025-03-14 02:00:00-04:00,1.294740,-0.000665,0.003635,0.001490,0.000517,0.000158,0.001245,0.001140,0.002220,0.001420,0.000000,0.000000,0,1.576393e+01,-5.119082,53.310873,NaN,NaN,NaN,NaN,0.002300,NaN,0.504348,0.001140,0.003000,NaN
6,2025-03-16 21:45:00-04:00,1.293830,-0.006055,0.001000,-0.005325,0.000450,0.000511,0.000687,0.000000,0.000300,0.000000,0.000000,0.000000,2,1.680869e+01,12.793947,57.203286,NaN,True,NaN,NaN,0.002165,NaN,0.295612,0.001525,NaN,NaN
7,2025-03-17 05:45:00-04:00,1.295305,-0.004580,0.000240,-0.003850,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,3.966439e+01,16.562258,66.844460,NaN,NaN,NaN,NaN,0.003465,NaN,0.134199,NaN,NaN,NaN
8,2025-03-17 11:30:00-04:00,1.298580,-0.001305,0.000420,-0.000575,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,3.479125e+01,49.549903,64.646681,NaN,NaN,NaN,NaN,0.007220,NaN,0.130886,NaN,NaN,NaN
9,2025-03-18 11:45:00-04:00,1.298450,-0.002535,0.000715,-0.001740,0.000000,0.000345,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,2.689830e+01,-1.581201,54.686739,NaN,NaN,NaN,NaN,0.005320,NaN,0.383459,NaN,NaN,NaN
10,2025-03-19 14:15:00-04:00,1.298320,-0.002800,0.000140,-0.001980,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,3.140059e+01,17.787973,58.943992,NaN,NaN,NaN,NaN,0.005000,NaN,0.441000,NaN,NaN,NaN
11,2025-03-24 02:45:00-04:00,1.294300,-0.003115,0.004725,0.001990,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1,3.788738e+01,32.559927,65.065258,NaN,NaN,NaN,NaN,0.005600,NaN,0.111607,NaN,NaN,NaN
12,2025-03-27 07:15:00-04:00,1.293635,-0.005585,0.001360,-0.001250,0.000000,0.000000,0.000000,0.000000,0.000000,-0.000775,0.000000,0.000000,2,4.831372e+01,30.010909,63.141962,NaN,NaN,NaN,NaN,0.007090,NaN,0.082511,NaN,NaN,NaN
13,2025-03-27 11:45:00-04:00,1.296285,-0.000980,0.001705,0.001400,0.000907,0.001335,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,6.101562e+01,52.989989,59.292832,True,NaN,NaN,True,0.012090,NaN,0.242763,0.009155,NaN,NaN
14,2025-03-28 03:30:00-04:00,1.295595,-0.001220,0.003350,0.002060,0.000936,0.000968,0.001949,0.001820,0.000000,0.000000,0.000000,0.000000,1,2.971917e+01,13.105718,58.518267,True,NaN,NaN,NaN,0.003065,NaN,0.406199,0.001820,NaN,NaN
15,2025-03-31 03:00:00-04:00,1.296465,-0.000540,0.007830,0.004690,0.000512,0.000545,0.001398,0.004260,0.002010,0.005510,0.000000,0.000000,2,1.027333e+01,33.772626,58.243498,True,NaN,NaN,NaN,0.005070,NaN,0.159763,0.004260,0.004630,NaN
16,2025-03-31 21:00:00-04:00,1.292425,-0.001665,0.004480,0.000095,0.000308,0.000610,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,1.680869e+01,20.136303,56.734827,True,NaN,NaN,NaN,0.001460,NaN,0.205479,NaN,NaN,NaN
17,2025-04-02 16:15:00-04:00,1.299180,-0.002740,0.002120,-0.001070,0.001230,0.002462,0.003080,0.000000,0.000000,0.000000,0.000000,0.000000,2,4.868062e+01,47.359166,64.427401,NaN,NaN,NaN,NaN,0.012460,NaN,0.267255,NaN,NaN,NaN
18,2025-04-03 01:45:00-04:00,1.309090,-0.011685,0.001090,-0.000890,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,5.567521e+01,63.858309,69.499840,NaN,True,NaN,NaN,0.012745,NaN,0.077678,NaN,NaN,NaN
19,2025-04-09 14:00:00-04:00,1.275775,-0.008000,0.000250,-0.005845,-0.001099,-0.002527,0.000821,0.000640,0.000000,0.000000,0.000000,0.000000,0,8.997143e+00,-46.354568,42.337681,NaN,NaN,NaN,NaN,0.012045,NaN,0.884184,NaN,NaN,NaN
20,2025-04-09 14:45:00-04:00,1.280340,-0.003435,0.001050,-0.001280,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1,6.489591e+01,-15.209658,54.607369,NaN,NaN,NaN,NaN,0.012045,NaN,0.505189,NaN,NaN,NaN
21,2025-04-09 21:00:00-04:00,1.283415,-0.016195,0.001190,-0.013515,0.000683,0.000000,0.000000,0.000000,0.000000,-0.000405,0.000000,0.000000,2,3.909386e+01,56.291560,57.407337,NaN,NaN,NaN,NaN,0.003670,NaN,0.348774,NaN,NaN,NaN
22,2025-04-10 06:00:00-04:00,1.288955,-0.010655,0.000150,-0.007975,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,5.717146e+01,53.108606,63.136922,NaN,NaN,NaN,NaN,0.008520,NaN,0.069249,NaN,NaN,NaN
23,2025-04-10 11:00:00-04:00,1.295040,-0.004570,0.002505,-0.001890,0.001808,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,5.565622e+01,63.212407,63.860596,True,NaN,NaN,NaN,0.015935,NaN,0.120489,0.014015,NaN,NaN
24,2025-04-10 20:45:00-04:00,1.301705,-0.012825,0.003215,-0.006320,0.000000,0.000000,0.000000,0.000000,0.000000,-0.000135,0.000000,0.000000,2,6.906202e+01,59.755464,65.594171,NaN,NaN,NaN,NaN,0.008060,NaN,0.382134,NaN,NaN,NaN
25,2025-04-16 00:00:00-04:00,1.326005,-0.003210,0.004775,0.001400,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,4.399811e+01,36.273239,64.572821,NaN,NaN,NaN,NaN,0.004060,NaN,0.124384,NaN,NaN,NaN
26,2025-04-16 02:00:00-04:00,1.327210,-0.002005,0.005980,0.002605,0.000885,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,5.072654e+01,44.182841,62.471410,NaN,NaN,NaN,NaN,0.006720,NaN,0.291667,NaN,NaN,NaN
27,2025-04-17 03:15:00-04:00,1.323240,-0.004085,0.001280,-0.003310,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1,2.013630e+01,-4.971028,59.097768,NaN,NaN,NaN,NaN,0.004905,NaN,0.402650,NaN,NaN,NaN
28,2025-04-17 15:00:00-04:00,1.326280,-0.000815,0.000085,-0.000270,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,4.942397e+01,38.931711,56.697607,NaN,NaN,NaN,NaN,0.007015,NaN,0.148967,NaN,NaN,NaN
29,2025-04-18 10:45:00-04:00,1.328315,-0.013920,0.001080,-0.009535,0.000619,0.000978,0.000000,0.000000,0.000000,-0.000285,0.000000,0.000000,2,2.317698e+01,15.984802,62.640931,True,NaN,NaN,NaN,0.003055,NaN,0.098200,NaN,NaN,NaN
30,2025-04-18 15:45:00-04:00,1.329010,-0.013225,0.000555,-0.008840,0.000489,0.000000,0.000000,0.000000,0.000000,-0.000570,0.000000,0.000000,2,2.962905e+01,18.461802,66.477522,NaN,NaN,NaN,NaN,0.003700,NaN,0.067568,NaN,NaN,NaN
31,2025-04-18 16:30:00-04:00,1.329805,-0.012430,0.000445,-0.008045,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,3.352447e+01,22.288520,73.030579,NaN,NaN,NaN,NaN,0.004405,NaN,0.036322,NaN,NaN,NaN
32,2025-04-21 04:00:00-04:00,1.340105,-0.002130,0.003795,0.002255,0.000000,0.000000,0.000000,0.000000,0.000000,-0.000890,0.000000,0.000000,2,5.096449e+01,61.727964,66.648957,NaN,NaN,NaN,NaN,0.016085,NaN,0.095741,NaN,NaN,NaN
33,2025-04-22 10:45:00-04:00,1.338080,-0.000390,0.005475,0.005190,0.000743,0.000611,0.002233,0.002540,0.002110,0.000000,0.002260,0.000000,1,2.876495e+01,-11.968344,52.097159,NaN,NaN,NaN,NaN,0.006860,NaN,0.629738,0.002540,NaN,NaN
34,2025-04-23 21:30:00-04:00,1.328230,-0.006690,0.001755,-0.005955,0.000503,0.001215,0.001555,0.000000,0.000000,0.000000,0.000000,0.000000,2,4.965018e+01,17.054486,58.182351,NaN,NaN,NaN,NaN,0.003380,NaN,0.118343,0.002980,NaN,NaN
35,2025-04-24 10:45:00-04:00,1.331455,-0.003465,0.002410,-0.002730,0.000369,0.000695,0.002322,0.000000,0.000000,0.000940,0.000000,0.000000,2,3.281359e+01,43.389699,56.168380,True,NaN,NaN,True,0.008020,NaN,0.226309,0.006205,NaN,NaN
36,2025-04-24 15:45:00-04:00,1.333740,-0.001180,0.000125,-0.000445,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,6.015196e+01,30.787895,62.063477,NaN,NaN,NaN,NaN,0.009220,NaN,0.079176,NaN,NaN,NaN
37,2025-04-25 03:15:00-04:00,1.330305,-0.002945,0.001610,-0.001190,0.001048,0.000334,0.000926,0.000000,0.000000,0.000355,0.000000,0.000000,1,-2.326362e+00,-27.205996,51.626643,NaN,NaN,NaN,NaN,0.006820,0.010849,0.576979,NaN,NaN,NaN
38,2025-04-25 07:00:00-04:00,1.331310,-0.001940,0.001515,-0.000185,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,1.864954e+01,10.013087,57.941643,NaN,NaN,NaN,NaN,0.006820,0.010849,0.429619,NaN,NaN,NaN
39,2025-04-28 10:45:00-04:00,1.339295,-0.005145,0.001215,-0.004745,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,6.845902e+01,65.271940,68.220331,NaN,NaN,NaN,NaN,0.014010,0.010901,0.196645,NaN,NaN,NaN
40,2025-04-30 02:00:00-04:00,1.338890,-0.001740,0.007985,0.006070,-0.000229,-0.000990,0.000483,-0.000660,0.000000,0.000000,0.000000,0.000000,0,4.407833e+00,-15.902032,42.744251,NaN,NaN,NaN,NaN,0.003295,0.011248,0.781487,-0.000660,NaN,NaN
41,2025-05-01 22:30:00-04:00,1.329595,-0.003495,0.003670,0.003670,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,2.853514e+01,27.582379,59.389891,NaN,NaN,NaN,NaN,0.002595,0.011503,0.154143,NaN,NaN,NaN
42,2025-05-04 21:30:00-04:00,1.328295,-0.005360,0.001260,-0.001120,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1,4.424416e+01,9.752425,54.498888,NaN,NaN,NaN,True,0.003700,0.011480,0.381081,NaN,NaN,NaN
43,2025-05-05 06:00:00-04:00,1.329550,-0.004105,0.002515,0.000135,0.000000,0.000000,0.000000,0.000000,0.000000,-0.000925,0.000000,0.000000,1,1.403624e+01,13.642368,54.356164,NaN,NaN,NaN,True,0.004665,0.011480,0.240086,NaN,NaN,NaN
44,2025-05-05 07:15:00-04:00,1.331835,-0.001820,0.004800,0.002420,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,5.503880e+01,32.771409,64.752280,NaN,NaN,NaN,NaN,0.006550,0.011480,0.109924,NaN,NaN,NaN
45,2025-05-06 03:45:00-04:00,1.331990,-0.008305,0.001205,-0.004570,0.001108,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,5.115310e+01,32.262169,65.938012,NaN,True,NaN,NaN,0.006870,0.011452,0.133916,NaN,NaN,NaN
46,2025-05-07 09:00:00-04:00,1.336170,-0.001550,0.008145,0.006970,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1,5.243141e+01,20.004668,56.934287,NaN,NaN,NaN,NaN,0.005750,0.011657,0.326087,NaN,NaN,NaN
47,2025-05-07 10:45:00-04:00,1.336620,-0.000105,0.008595,0.007420,0.000614,0.001393,0.002423,0.004325,0.000000,0.000000,0.004075,0.000000,2,4.402898e+01,8.764101,55.441260,NaN,NaN,NaN,NaN,0.005750,0.011657,0.247826,0.004325,NaN,NaN
48,2025-05-07 21:15:00-04:00,1.330525,-0.005130,0.006870,0.005985,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,3.161749e+01,-38.714355,50.173638,NaN,NaN,NaN,NaN,0.002635,0.011776,0.267552,NaN,NaN,NaN
49,2025-05-08 06:45:00-04:00,1.326290,-0.008255,0.002635,0.001750,-0.001349,-0.003726,0.000955,-0.002305,0.000000,-0.005440,-0.005440,0.000000,0,-1.211106e+01,-53.087088,39.785562,NaN,NaN,NaN,NaN,0.009525,0.011776,0.983202,-0.002305,NaN,NaN
50,2025-05-09 02:45:00-04:00,1.324215,-0.008040,0.000060,-0.006290,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,2.704052e+01,-5.710593,52.638239,NaN,NaN,NaN,NaN,0.004100,0.011924,0.263415,NaN,NaN,NaN
51,2025-05-09 03:45:00-04:00,1.326230,-0.006025,0.000830,-0.004275,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,5.434098e+01,27.276763,61.785243,NaN,NaN,NaN,NaN,0.005745,0.011924,0.123586,NaN,NaN,NaN
52,2025-05-09 07:15:00-04:00,1.327785,-0.004470,0.001205,-0.002720,0.000767,0.000000,0.000000,0.000000,0.000000,-0.000755,0.000000,0.000000,2,4.896520e+01,43.562554,62.127836,NaN,NaN,NaN,NaN,0.007375,0.011924,0.106441,NaN,NaN,NaN
53,2025-05-09 09:30:00-04:00,1.329005,-0.003250,0.000575,-0.001500,0.000000,0.000000,0.000000,0.000000,0.000000,-0.000290,0.000000,0.000000,2,4.238045e+01,52.197208,63.453202,NaN,NaN,NaN,NaN,0.008545,0.011924,0.086015,NaN,NaN,NaN
54,2025-05-09 10:30:00-04:00,1.330455,-0.001800,0.001095,-0.000050,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,5.667371e+01,54.371386,65.801808,NaN,NaN,NaN,NaN,0.010560,0.011924,0.123106,NaN,NaN,NaN
55,2025-05-12 02:15:00-04:00,1.329320,-0.000620,0.015325,0.011800,0.000743,0.000717,0.003387,0.002720,0.000000,0.011875,0.000000,0.000000,1,1.680869e+01,8.559948,55.005953,NaN,NaN,NaN,NaN,0.003100,0.011889,0.122581,0.002720,0.013395,NaN
56,2025-05-12 20:15:00-04:00,1.317710,-0.013940,0.000325,-0.012870,0.000063,0.000037,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1,2.981461e+00,-12.367563,47.448811,NaN,NaN,NaN,NaN,0.001625,0.012268,0.510769,NaN,NaN,NaN
57,2025-05-13 00:00:00-04:00,1.319385,-0.012265,0.000430,-0.011195,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,3.285572e+01,19.369762,59.591769,NaN,NaN,NaN,NaN,0.003115,0.012268,0.207063,NaN,NaN,NaN
58,2025-05-13 19:00:00-04:00,1.330475,-0.005565,0.005145,0.004750,-0.000198,0.000394,0.000370,0.000000,0.000000,0.000000,0.000000,0.000000,2,2.231406e+01,50.582606,61.497093,NaN,NaN,NaN,NaN,0.001085,0.012471,0.889401,NaN,NaN,NaN
59,2025-05-13 21:30:00-04:00,1.330940,-0.005100,0.005610,0.005215,0.000068,0.000355,0.001090,0.000995,0.000345,0.000000,0.000725,0.000000,2,1.859594e+01,26.181808,56.964590,NaN,NaN,NaN,True,0.002060,0.012471,0.516990,0.001090,NaN,NaN
60,2025-05-14 04:30:00-04:00,1.334430,-0.001610,0.009100,0.008705,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,5.979328e+01,39.946174,68.943334,NaN,NaN,NaN,NaN,0.006760,0.012471,0.211538,NaN,NaN,NaN
61,2025-05-14 21:45:00-04:00,1.327585,-0.004390,0.001330,-0.002960,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,3.078790e+01,-4.822908,52.475371,NaN,NaN,NaN,NaN,0.002575,0.012623,0.335922,NaN,NaN,NaN
62,2025-05-15 03:00:00-04:00,1.329295,-0.002680,0.002975,-0.001250,0.001028,0.001396,0.002170,0.000000,0.001145,0.000000,0.000000,0.000000,2,3.762623e+01,34.019350,58.199910,NaN,NaN,NaN,NaN,0.004635,0.012623,0.262136,0.003420,NaN,NaN
63,2025-05-15 09:15:00-04:00,1.330540,-0.000350,0.004170,-0.000005,0.001288,0.001535,0.004151,0.000000,0.000000,0.000640,0.000000,0.000000,2,4.340545e+01,38.054284,58.306382,NaN,NaN,NaN,True,0.006100,0.012623,0.235246,0.004665,NaN,NaN
64,2025-05-16 01:15:00-04:00,1.332105,-0.001180,0.007035,0.005400,0.000000,0.000000,0.000000,0.000000,0.000000,-0.000500,0.000000,0.000000,2,2.024145e+01,22.135058,61.275290,NaN,NaN,NaN,NaN,0.002815,0.012411,0.234458,NaN,NaN,NaN
65,2025-05-19 21:30:00-04:00,1.336165,-0.003325,0.002675,-0.003145,0.000412,0.000484,0.001385,0.000000,0.000000,0.000000,0.000000,0.000000,2,1.364237e+01,17.081757,53.700086,NaN,NaN,NaN,NaN,0.002875,0.011463,0.424348,NaN,NaN,NaN
66,2025-05-20 01:30:00-04:00,1.337485,-0.002005,0.003995,-0.001825,0.000541,0.000000,0.000000,0.000000,0.000000,-0.000610,0.000000,0.000000,2,2.825803e+01,21.310964,59.143241,NaN,True,NaN,NaN,0.003760,0.011463,0.208777,0.002975,NaN,NaN
67,2025-05-21 02:30:00-04:00,1.345455,-0.000240,0.006575,0.003485,0.001843,0.003066,0.004242,0.000000,0.000000,0.000620,0.000000,0.000000,2,5.593909e+01,54.502609,74.946336,NaN,NaN,NaN,NaN,0.008495,0.010910,0.170100,NaN,NaN,NaN
68,2025-05-21 20:15:00-04:00,1.342420,-0.001685,0.003330,0.000520,0.000684,-0.000154,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,2.092144e+01,-20.398909,51.764520,NaN,NaN,NaN,NaN,0.002695,0.010885,0.280148,NaN,NaN,NaN
69,2025-05-21 22:45:00-04:00,1.343300,-0.000760,0.004210,0.001400,0.000515,0.001043,0.001173,0.002820,0.000530,0.002585,0.002585,0.000530,2,5.129356e+01,2.653998,55.922632,NaN,True,NaN,NaN,0.003625,0.010885,0.222069,0.002820,NaN,NaN
70,2025-05-22 04:15:00-04:00,1.342940,-0.000745,0.003850,0.001040,0.000347,0.000204,0.001472,0.002460,0.002225,0.002225,0.002225,0.002225,1,1.789613e+01,7.594643,52.191876,NaN,NaN,NaN,NaN,0.003625,0.010885,0.321379,0.002460,NaN,NaN
71,2025-05-23 08:45:00-04:00,1.351815,-0.002785,0.003745,-0.002260,0.001849,0.003065,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,5.731125e+01,56.236335,65.104911,NaN,NaN,NaN,NaN,0.011665,0.010651,0.132447,NaN,NaN,NaN
72,2025-05-25 21:00:00-04:00,1.355750,-0.003580,0.000635,-0.000585,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,4.032987e+01,38.586950,68.434146,NaN,NaN,NaN,NaN,0.003730,0.010462,0.100536,NaN,NaN,NaN
73,2025-05-26 10:00:00-04:00,1.355825,-0.000695,0.000095,-0.000510,-0.000039,-0.000571,0.000000,0.000000,0.000000,-0.000405,0.000000,0.000000,0,1.790487e-01,-29.221558,46.459233,NaN,NaN,NaN,True,0.006935,0.010462,0.505407,NaN,NaN,NaN
74,2025-05-26 18:15:00-04:00,1.356670,-0.002030,0.006635,0.005975,0.000293,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,9.462322e+00,5.207882,56.296013,NaN,NaN,NaN,NaN,0.001150,0.010099,0.143478,NaN,NaN,NaN
75,2025-05-28 03:15:00-04:00,1.348725,-0.003225,0.003740,0.002005,0.000000,-0.000301,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,2.432693e+01,-22.416147,49.494591,NaN,True,NaN,NaN,0.006110,0.009930,0.574468,NaN,NaN,NaN
76,2025-05-29 02:30:00-04:00,1.345270,-0.005450,0.000110,-0.003830,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,2.858118e+01,-16.863368,55.966677,NaN,NaN,NaN,NaN,0.005600,0.009879,0.336607,NaN,NaN,NaN
77,2025-05-29 03:15:00-04:00,1.346310,-0.004410,0.000860,-0.002790,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,5.127021e+01,13.557793,60.504675,NaN,NaN,NaN,NaN,0.005600,0.009879,0.150893,NaN,NaN,NaN
78,2025-05-29 20:30:00-04:00,1.349655,-0.001445,0.004840,0.003740,-0.000013,-0.000031,0.000881,0.000820,0.002395,0.002145,0.002395,0.002145,1,1.838122e+01,4.140752,50.975235,NaN,NaN,NaN,NaN,0.002135,0.009918,0.615925,0.000820,0.002820,0.004155
79,2025-05-30 08:45:00-04:00,1.349240,-0.000210,0.004425,0.003325,0.001275,0.001605,0.003615,0.003740,0.002690,0.002690,0.002690,0.002690,2,4.084615e+01,25.747626,58.474611,NaN,NaN,NaN,NaN,0.005600,0.009918,0.332143,0.003740,NaN,NaN
80,2025-06-02 19:15:00-04:00,1.355235,-0.000695,0.006060,0.003500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2,2.516375e+01,-0.328253,62.237255,NaN,NaN,NaN,NaN,0.001720,0.009692,0.116279,NaN,NaN,NaN
81,2025-06-02 19:45:00-04:00,1.355725,-0.000020,0.006550,0.003990,0.000922,0.001548,0.002235,0.002010,0.002025,0.003515,0.005155,0.002025,2,2.825803e+01,6.064922,65.267000,NaN,NaN,NaN,NaN,0.002215,0.009692,0.092551,0.002010,0.004530,0.005175
82,2025-06-03 02:30:00-04:00,1.352550,-0.001160,0.003375,0.000815,0.000319,-0.000665,0.001470,-0.001165,0.002450,0.000340,0.001980,0.001980,0,1.268038e+01,-17.109020,47.747007,NaN,NaN,NaN,NaN,0.004735,0.009692,0.713833,0.001355,0.002000,NaN
83,2025-06-03 09:45:00-04:00,1.351285,-0.002070,0.001640,-0.000450,0.000633,-0.000091,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1,-1.014507e+00,-3.576334,50.080716,NaN,NaN,NaN,NaN,0.006755,0.009692,0.687639,NaN,NaN,NaN
84,2025-06-03 10:45:00-04:00,1.352885,-0.000315,0.001855,0.001150,0.001000,0.001512,0.001506,0.000000,0.000000,0.000000,0.000000,0.000000,1,3.930890e+01,2.445521,57.583347,NaN,NaN,NaN,NaN,0.006755,0.009692,0.450777,NaN,NaN,NaN
85,2025-06-03 19:15:00-04:00,1.352460,-0.005540,0.002325,-0.002865,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1,2.445521e+00,-1.700469,54.525983,NaN,NaN,NaN,NaN,0.000885,0.009591,0.118644,NaN,NaN,NaN