# Bear_BBR Signal - Data Prep

## Import Libs

In [1100]:
import pandas as pd 
import numpy as np
import os
from pandas import DataFrame, Series
import plotly.graph_objects as go

## Read CSV price data and get DataFrame

In [2804]:
PATH = os.getcwd()
FILE = "../output/FE_V2_GBPUSD_15mins_1yr_End_20260311.csv"
df = pd.read_csv(FILE)
df["Date"] = pd.DatetimeIndex(df["Date"], tz="US/Eastern")
df.set_index("Date", inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 24580 entries, 2025-03-11 17:15:00-04:00 to 2026-03-11 16:45:00-04:00
Data columns (total 49 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Open           24580 non-null  float64
 1   High           24580 non-null  float64
 2   Low            24580 non-null  float64
 3   Close          24580 non-null  float64
 4   Idx            24580 non-null  int64
 5   Body           24580 non-null  float64
 6   Range          24580 non-null  float64
 7   UWick          24580 non-null  float64
 8   LWick          24580 non-null  float64
 9   Close_%High    24580 non-null  float64
 10  Open_%High     24580 non-null  float64
 11  Iday_Idx       24580 non-null  int64
 12  Iday_High      24580 non-null  float64
 13  Iday_Low       24580 non-null  float64
 14  Iday_Range     24580 non-null  float64
 15  Close_%DHigh   24580 non-null  float64
 16  Open_%DHigh    24580 non-null  float64
 17  Yday_High      24485 non-null  float64
 18  Yday_Low       24485 non-null  float64
 19  Day_Idx        24580 non-null  int64
 20  ADR            21646 non-null  float64
 21  ATR            24568 non-null  float64
 22  SMA4           24576 non-null  float64
 23  SMA16          24580 non-null  float64
 24  SMA32          24580 non-null  float64
 25  BB_Upper_16_2  24580 non-null  float64
 26  BB_Lower_16_2  24580 non-null  float64
 27  Close_%SMA     24580 non-null  float64
 28  RSI            24564 non-null  float64
 29  RSI_DVG        1233 non-null   object
 30  Sig_High       20360 non-null  float64
 31  Sig_Low        20726 non-null  float64
 32  SMA_Trend      24580 non-null  int64
 33  SMA4_Slope     24574 non-null  float64
 34  SMA16_Slope    24578 non-null  float64
 35  SMA32_Slope    24578 non-null  float64
 36  Hammer         957 non-null    object
 37  Shooting_Star  927 non-null    object
 38  Bull_Engulf    520 non-null    object
 39  Bear_Engulf    506 non-null    object
 40  Dark_Cloud     192 non-null    object
 41  Piercing       213 non-null    object
 42  ILR            277 non-null    object
 43  IHR            305 non-null    object
 44  S_R            3168 non-null   float64
 45  BBU_BO         554 non-null    object
 46  BBL_BO         183 non-null    object
 47  Bull_BBR       416 non-null    object
 48  Bear_BBR       389 non-null    object
dtypes: float64(32), int64(4), object(13)
memory usage: 9.4+ MB

## Add extra features

In [548]:
def get_yra_std(row: Series, df: DataFrame, n: int):
    std = df["YRA_Diff"].at_time("17:15").iloc[row["Day_Idx"]-n+1:row["Day_Idx"]+1].std()
    return std

pd.options.display.max_rows = 100
pd.options.display.max_columns = 100
df["Yday_Range"] = df.eval("Yday_High - Yday_Low")
df["YRA_Diff"] = df.apply(lambda x: x["Yday_Range"] - x["ADR"], axis=1)
df["YRA_STD"] = df.apply(get_yra_std, axis=1, args=[df.copy(), 30])

In [549]:
bbu_reversal = df
bbu_reversal.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 24580 entries, 2025-03-11 17:15:00-04:00 to 2026-03-11 16:45:00-04:00
Data columns (total 51 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Open           24580 non-null  float64
 1   High           24580 non-null  float64
 2   Low            24580 non-null  float64
 3   Close          24580 non-null  float64
 4   Idx            24580 non-null  int64
 5   Body           24580 non-null  float64
 6   Range          24580 non-null  float64
 7   UWick          24580 non-null  float64
 8   LWick          24580 non-null  float64
 9   Close_%High    24580 non-null  float64
 10  Open_%High     24580 non-null  float64
 11  Iday_Idx       24580 non-null  int64
 12  Iday_High      24580 non-null  float64
 13  Iday_Low       24580 non-null  float64
 14  Iday_Range     24580 non-null  float64
 15  Close_%DHigh   24580 non-null  float64
 16  Open_%DHigh    24580 non-null  float64
 17  Yday_High      24485 non-null  float64
 18  Yday_Low       24485 non-null  float64
 19  Day_Idx        24580 non-null  int64
 20  ADR            21646 non-null  float64
 21  ATR            24568 non-null  float64
 22  SMA4           24576 non-null  float64
 23  SMA16          24580 non-null  float64
 24  SMA32          24580 non-null  float64
 25  BB_Upper_16_2  24580 non-null  float64
 26  BB_Lower_16_2  24580 non-null  float64
 27  Close_%SMA     24580 non-null  float64
 28  RSI            24564 non-null  float64
 29  RSI_DVG        1233 non-null   object
 30  Sig_High       20360 non-null  float64
 31  Sig_Low        20726 non-null  float64
 32  SMA_Trend      24580 non-null  int64
 33  SMA16_Slope    24578 non-null  float64
 34  SMA32_Slope    24578 non-null  float64
 35  Hammer         957 non-null    object
 36  Shooting_Star  927 non-null    object
 37  Bull_Engulf    520 non-null    object
 38  Bear_Engulf    506 non-null    object
 39  Dark_Cloud     192 non-null    object
 40  Piercing       213 non-null    object
 41  ILR            277 non-null    object
 42  IHR            305 non-null    object
 43  S_R            3168 non-null   float64
 44  BBU_BO         455 non-null    object
 45  BBL_BO         183 non-null    object
 46  Bull_BBR       117 non-null    object
 47  Bear_BBR       494 non-null    object
 48  Yday_Range     24485 non-null  float64
 49  YRA_Diff       21646 non-null  float64
 50  YRA_STD        21646 non-null  float64
dtypes: float64(34), int64(4), object(13)
memory usage: 9.8+ MB

# Bear_BBR Signal Analysis

## Bearish BBR Metrics Function

Return a new dataframe with all occrrences of Bear_BBR signal and get additional metrics such as:
- Entry Price
- Max Gain / Loss
- Gain/Loss to:
    - SMA16,
    - SMA32,
    - BB_Lower,
    - SigLow,
    - First_Bullish_Signal (Bull_0)
    - Bull_Engulf
    - Intraday_Low_Reversal (ILR)
- Whether S/R was tested or broken
- Whether other bearish pattern occurred at the same time

In [550]:

def bearish_bbr_metrics(df: DataFrame, bear_bbr_signal_idx: list):
    """Return a new dataframe with signal metrics"""

    signal = []
    for signal_idx in bear_bbr_signal_idx:
        row = df.iloc[signal_idx]
        s = {}
        START = row.name
        TD = pd.Timedelta(minutes=15)
        s["Date"] = START
        s["Entry_Price"] = row["Close"] # signal price
        
        day = row["Day_Idx"]
        window = df.query(f"Day_Idx == {day}") # only get df data from the same FX day as signal
        before_signal_window = window[:START-TD] # get df data from start of day until just before signal
        signal_window = window[START:] # get df from signal until end of day (EOD)
        
        Max_High = signal_window[START+TD:]["High"].max() # Max high from signal until EOD
        Min_Low = signal_window[START+TD:]["Low"].min() # Min low from signal until EOD
        s["D_Max_Up"] = s["Entry_Price"] - Max_High # Max price gain from signal until EOD
        s["D_Max_Down"] = s["Entry_Price"] - Min_Low # Max price loss from signal until EOD
        D_Close = signal_window.iloc[-1]["Close"] # Closing price at EOD
        s["D_Gain"] = s["Entry_Price"] - D_Close # Gain at EOD from signal 


        if signal_window.query(f"Close > {row["High"]}").empty is False:
            # If price closed above signal price within the day, 
            # get the dataframe between start and failure time
            EXIT = signal_window[START:].query(f"Close > {row["High"]}").iloc[0].name
            entry_window = signal_window[START:EXIT]
        else:
            # If price didn't close above signal price within the day
            # get the dataframe from signal time until EOD
            entry_window = signal_window

        # Did the price go higher than the signal candle high
        if entry_window[START+TD:].query(f"High >= {row["High"]}").empty is False:
            s["Stop_Pips"] = s["Entry_Price"] - row["High"]
        else:
            s["Stop_Pips"] = 0
        
        s["Max_Up"] = s["Entry_Price"] - entry_window[START+TD:]["Close"].max()
        s["Max_Down"] = s["Entry_Price"] - entry_window[START+TD:]["Low"].min()
        

        # If the price fell to the SMA16 after the signal
        # calcuate the gain
        below_sma16 = entry_window.query("Low < SMA16")
        if below_sma16.empty is False:
            s["To_SMA16"] = s["Entry_Price"] - below_sma16.iloc[0]["SMA16"] 
        else: 
            s["To_SMA16"] = 0

        # If the price fell to the SMA32 after the signal
        # calcuate the gain
        below_sma32 = entry_window.query("Low < SMA32")
        if below_sma32.empty is False:
            s["To_SMA32"] = s["Entry_Price"] - below_sma32.iloc[0]["SMA32"]
        else:
            s["To_SMA32"] = 0

        # If the price fell to the BB_Lower_16_2 after the signal
        # calcuate the gain
        below_bbl = entry_window.query("Low < BB_Lower_16_2")
        if below_bbl.empty is False:
            s["To_BBL_16_2"] = s["Entry_Price"] - below_bbl.iloc[0]["BB_Lower_16_2"]
        else:
            s["To_BBL_16_2"] = 0

        # If the price fell to the Sig_Low after the signal
        # calcuate the gain
        below_sig_low = entry_window.query("Low < Sig_Low")
        if below_sig_low.empty is False:
            s["To_Sig_Low"] = s["Entry_Price"] - below_sig_low.iloc[0]["Sig_Low"]
        else:
            s["To_Sig_Low"] = 0

        below_sr = entry_window.query("S_R > 3")["Sig_Low"].unique()
        for i in range(len(below_sr)):
            s[f"To_S_{i}"] = s["Entry_Price"] - below_sr[i]


        # Check if bullish signals occured during winddow
        NULL_Timestamp = pd.Timestamp(0, tz="US/Eastern")
        to_bull_bbr = entry_window.query("Bull_BBR == True")
        if to_bull_bbr.empty is False:
            s["To_Bull_BBR"] = s["Entry_Price"] - to_bull_bbr.iloc[0]["Close"]
            to_bull_bbr_time_stamp = to_bull_bbr.iloc[0].name
        else:
            s["To_Bull_BBR"] = 0
            to_bull_bbr_time_stamp = NULL_Timestamp

        to_bull_engulf = entry_window.query("Bull_Engulf == True")
        if to_bull_engulf.empty is False:
            s["To_Bull_Engulf"] = s["Entry_Price"] - to_bull_engulf.iloc[0]["Close"]
            to_bull_engulf_time_stamp = to_bull_engulf.iloc[0].name
        else:
            s["To_Bull_Engulf"] = 0
            to_bull_engulf_time_stamp = NULL_Timestamp

        to_ilr = entry_window.query("ILR == True")
        if to_ilr.empty is False:
            s["To_ILR"] = s["Entry_Price"] - to_ilr.iloc[0]["Close"]
            to_ilr_time_stamp = to_ilr.iloc[0].name
        else:
            s["To_ILR"] = 0
            to_ilr_time_stamp = NULL_Timestamp

        first_bullish_signal = min([to_bull_bbr_time_stamp, to_bull_engulf_time_stamp, to_ilr_time_stamp])
        if first_bullish_signal > NULL_Timestamp:
            s["To_Bull_0"] = s["Entry_Price"] - entry_window.loc[first_bullish_signal]["Close"]
        else:
            s["To_Bull_0"] = 0

        # how man times was resistance tested before signal
        r_test = before_signal_window.query("S_R == 1")["S_R"].count() 
        # how man times was resistance broken before signal
        r_break = before_signal_window.query("S_R == 2")["S_R"].count()
        # how man times was support tested before signal
        s_test = before_signal_window.query("S_R == 3")["S_R"].count()
        # how man times was support broken before signal
        s_break = before_signal_window.query("S_R == 4")["S_R"].count()

        h1_range = window[:START].iloc[-4:]["High"].max() - window[:START].iloc[-4:]["Low"].min()


        # append other useful df metrics to new df
        s["Range"] = row["Range"]
        s["ATR"] = row["ATR"]
        s["Close_%High"] = row["Close_%High"]
        s["SMA_Trend"] = row["SMA_Trend"]
        s["SMA16_Slope"] = row["SMA16_Slope"]
        s["SMA32_Slope"] = row["SMA32_Slope"]
        s["RSI"] = row["RSI"]
        s["IHR"] = row["IHR"]
        s["Dark_Cloud"] = row["Dark_Cloud"]
        s["Shooting_Star"] = row["Shooting_Star"]
        s["Bear_Engulf"] = row["Bear_Engulf"]
        s["Iday_Range"] = row["Iday_Range"]
        s["ADR"] = row["ADR"]
        s["Close_%DHigh"] = row["Close_%DHigh"]
        s["SMA16"] = row["SMA16"]
        s["SMA32"] = row["SMA32"]
        s["S_R"] = row["S_R"]
        s["YRA_Diff"] = row["YRA_Diff"]
        s["YRA_STD"] = row["YRA_STD"]
        s["R_Tested"] = r_test
        s["R_Broken"] = r_break
        s["S_Tested"] = s_test
        s["S_Broken"] = s_break
        s["H1_Range"] = h1_range
        

        signal.append(s)
    sdf = pd.DataFrame(signal)
    return sdf

### Get Bear_BBR Metrics

In [551]:
signal_idx_list = bbu_reversal.query("Bear_BBR == True")["Idx"].to_list()
bearish_bbr_df = bearish_bbr_metrics(bbu_reversal, signal_idx_list)
bearish_bbr_df.tail(10)

,Date,Entry_Price,D_Max_Up,D_Max_Down,D_Gain,Stop_Pips,Max_Up,Max_Down,To_SMA16,To_SMA32,To_BBL_16_2,To_Sig_Low,To_Bull_BBR,To_Bull_Engulf,To_ILR,To_Bull_0,Range,ATR,Close_%High,SMA_Trend,SMA16_Slope,SMA32_Slope,RSI,IHR,Dark_Cloud,Shooting_Star,Bear_Engulf,Iday_Range,ADR,Close_%DHigh,SMA16,SMA32,S_R,YRA_Diff,YRA_STD,R_Tested,R_Broken,S_Tested,S_Broken,H1_Range,To_S_0,To_S_1,To_S_2
484,2026-02-25 08:15:00-05:00,1.352465,-0.004140,0.001810,-0.003445,-0.001085,-0.001475,0.001810,0.001259,0.000870,0.000000,0.000000,0.00000,-0.000915,0.000000,0.00000,0.001090,0.000889,0.995413,1,28.396764,9.055358,57.268983,True,True,NaN,NaN,0.004450,0.009190,0.243820,1.351238,1.351654,1.0,-0.002540,0.003821,0,1,3,0,0.002810,NaN,NaN,NaN
485,2026-02-25 21:00:00-05:00,1.357065,-0.000120,0.012525,0.008850,0.000000,0.000590,0.012525,0.000869,0.001290,0.002140,0.002000,0.00496,0.001490,0.001490,0.00149,0.000560,0.000514,0.794643,2,28.719069,15.209658,67.148904,NaN,NaN,NaN,True,0.002445,0.009293,0.182004,1.356128,1.355746,NaN,-0.001788,0.003872,0,0,0,0,0.001045,0.00211,0.00516,NaN
486,2026-03-02 20:30:00-05:00,1.341450,-0.000320,0.016130,0.005990,0.000000,0.000490,0.016130,0.000713,0.000704,0.001739,0.002260,0.00501,0.005010,0.014555,0.00501,0.000900,0.000659,0.900000,1,21.388623,11.108936,55.027898,NaN,NaN,NaN,NaN,0.002740,0.009690,0.394161,1.340755,1.340783,NaN,0.004465,0.004017,0,0,0,0,0.002295,0.00226,NaN,NaN
487,2026-03-03 07:15:00-05:00,1.331485,-0.005520,0.006165,-0.003975,-0.001275,-0.001280,0.006165,0.001538,-0.001173,0.004575,-0.007705,0.00000,0.000000,0.004590,0.00000,0.002290,0.001823,0.556769,0,-4.051684,-60.495741,47.020131,NaN,NaN,NaN,NaN,0.016280,0.009690,0.678440,1.329575,1.332658,NaN,0.004465,0.004017,0,0,0,1,0.005725,NaN,NaN,NaN
488,2026-03-04 14:45:00-05:00,1.337470,-0.000595,0.000490,0.000085,-0.000260,-0.000515,0.000400,0.000000,0.001054,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.001615,0.000974,0.160991,0,-0.954841,-11.911215,56.666491,NaN,NaN,NaN,NaN,0.010000,0.009992,0.287000,1.335976,1.336416,NaN,0.007218,0.003755,1,3,5,2,0.002665,NaN,NaN,NaN
489,2026-03-04 20:00:00-05:00,1.338030,-0.000680,0.008280,0.002145,-0.000415,-0.000635,0.000015,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000815,0.000542,0.509202,2,10.042024,15.320750,57.892203,NaN,NaN,NaN,NaN,0.002045,0.010132,0.239609,1.337425,1.336817,NaN,-0.000132,0.003869,0,0,0,0,0.001470,NaN,NaN,NaN
490,2026-03-04 20:30:00-05:00,1.336975,-0.000705,0.007225,0.001090,0.000000,-0.000260,0.007225,-0.000480,-0.000002,0.000881,0.000500,0.00000,0.000495,0.000480,0.00000,0.001820,0.000709,0.942308,2,5.651495,28.118933,48.294997,NaN,NaN,NaN,NaN,0.002235,0.010132,0.776286,1.337455,1.336977,NaN,-0.000132,0.003869,0,0,0,0,0.001840,0.00050,0.00638,NaN
491,2026-03-05 20:15:00-05:00,1.335575,-0.006055,0.004420,-0.004505,-0.001080,-0.001145,0.000000,-0.000215,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.001195,0.000619,0.903766,2,5.828753,40.948449,53.285765,NaN,NaN,NaN,NaN,0.002125,0.010079,0.541176,1.335790,1.334766,NaN,-0.001119,0.003272,0,0,0,0,0.001265,NaN,NaN,NaN
492,2026-03-06 10:15:00-05:00,1.335440,-0.006190,0.000500,-0.004640,-0.002685,-0.003570,0.000500,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.002985,0.002402,0.899497,1,45.119118,-0.179049,52.486291,NaN,True,NaN,NaN,0.007940,0.010079,0.460327,1.334037,1.334415,1.0,-0.001119,0.003272,3,2,0,3,0.005245,NaN,NaN,NaN
493,2026-03-10 20:45:00-04:00,1.343060,-0.002700,0.003715,0.001875,-0.000690,-0.001175,0.000420,0.000000,0.000187,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000775,0.000553,0.890323,1,29.403071,-26.588919,51.484603,NaN,NaN,NaN,NaN,0.002735,0.009747,0.252285,1.342066,1.342959,NaN,-0.002632,0.003298,0,1,0,0,0.002275,NaN,NaN,NaN

## Signal Stats

### Initial Signal Stats

In [552]:
# get the total number of bear_bbr signals
total_signals_count = bearish_bbr_df[bearish_bbr_df.columns[0]].count()

day_closed_lower = bearish_bbr_df.query("D_Gain > 0")
day_closed_higher = bearish_bbr_df.query("D_Gain <= 0")
day_closed_lower_count = day_closed_lower["D_Gain"].count()
day_closed_higher_count = day_closed_higher["D_Gain"].count()
day_closed_lower_pct = round(day_closed_lower_count / total_signals_count * 100,2)
day_closed_lower_pips = bearish_bbr_df["D_Gain"].sum().round(6)

# filter the dataframe for occurences where after the signal
# the price moved lower more than it moved higher
d_max_down_greater = bearish_bbr_df.query("D_Max_Up.abs() < D_Max_Down")
# get the count of occurences where price dropped more then it rose after signal
d_max_down_greater_count = d_max_down_greater[d_max_down_greater.columns[0]].count()

# percentage of where price fell further than the max it went against the entry price
d_max_down_greater_pct = round(d_max_down_greater_count / total_signals_count * 100, 2)

max_down_win = bearish_bbr_df.query("Max_Down > Max_Up.abs()")["Date"].count()
max_down_loss = bearish_bbr_df.query("Max_Down <= Max_Up.abs()")["Date"].count()
total_max_down_trades = max_down_win + max_down_loss
max_down_win_rate = round((max_down_win / total_max_down_trades) * 100 ,2)

max_down_pips = bearish_bbr_df["Max_Down"].sum().round(6)
max_up_pips = bearish_bbr_df["Max_Up"].sum().round(6)
total_max_down_gain = max_down_pips + max_up_pips

average_max_up = bearish_bbr_df["Max_Up"].mean().round(6)
average_max_down = bearish_bbr_df["Max_Down"].mean().round(6)


print(
    f"""
    ========= Initial Bear_BBR Statistics =============

    Total Bear_BBR Signals: {total_signals_count}

    ** Where the move down from the signal resulted **
    ** in a positive gain at the close of the day **
    Day Closed Lower (Count): {day_closed_lower_count}
    Day Closed Higher (Count): {day_closed_higher_count}
    Day Closed Lower (%): {day_closed_lower_pct}
    Day Closed Lower (Pips): {day_closed_lower_pips}

    ** Where after the signal the max move down on the day **
    ** was greater than the max move up **
    D_Max_Down > D_Max_Up (Count): {d_max_down_greater_count}
    D_Max_Down > D_Max_Up (%): {d_max_down_greater_pct}

    ** Where the max move down after the signal **
    ** was greater than the max move up (exit if price closes above signal high) **
    Max_Down > Max_Up (Count): {max_down_win}
    Max_Down <= Max_Up (Count): {max_down_loss}
    Total Trades (Max_Down): {total_max_down_trades}
    Max_Down > Max_Up (Win Rate): {max_down_win_rate}

    Max_Down Pips: {max_down_pips}
    Max_Up Pips: {max_up_pips}
    Total Max_Down Gain: {total_max_down_gain}
    
    Average Max_Up Pips: {average_max_up}
    Average Max_Down Pips: {average_max_down}
 
    ==============================================================================
    """
)

    ========= Initial Bear_BBR Statistics =============

    Total Bear_BBR Signals: 494

    ** Where the move down from the signal resulted **
    ** in a positive gain at the close of the day **
    Day Closed Lower (Count): 245
    Day Closed Higher (Count): 249
    Day Closed Lower (%): 49.6
    Day Closed Lower (Pips): -0.11882

    ** Where after the signal the max move down on the day **
    ** was greater than the max move up **
    D_Max_Down > D_Max_Up (Count): 234
    D_Max_Down > D_Max_Up (%): 47.37

    ** Where the max move down after the signal **
    ** was greater than the max move up (exit if price closes above signal high) **
    Max_Down > Max_Up (Count): 239
    Max_Down <= Max_Up (Count): 249
    Total Trades (Max_Down): 488
    Max_Down > Max_Up (Win Rate): 48.98

    Max_Down Pips: 0.95317
    Max_Up Pips: -0.415825
    Total Max_Down Gain: 0.537345

    Average Max_Up Pips: -0.000852
    Average Max_Down Pips: 0.001953

    ==============================================================================

### Summary

- From the initial numbers, we can see that the Bear_BBR signal occurred `149` times.
- After the signal occuring, the *max price move down* was greater than the *max price move up* on the day, `47.65%` of the time.
- When the signal occurred, `44.59%` of the time the price dropped more than it gained after the signal, before closing above the signal high.
- The total gains where the price fell more than it rose after the signal (before closing above the signal high) was `1362` pips.
- The average number of pips where price moved against the signal was `10.56` pips
- The average number of pips gained before price closed above the signal high was `19.76` pips.

#### What does this tell us?

- We can see just under 50% of the time, the price moves lower after the signal, *before or without closing above the signal high*.
- Additionally, the gains from when the price moves in favour of the signal is greater than when the price moves against the signal. In short the signal generates more gains than losses overall.
- On average, the price moves down nearly double the amount it moves against the signal.

#### What information is missing?

- Although the signal gains more pips overall, this doesn't tell us the best place to take profit to capture the max move down.
- It is not clear what factors make a move down more likely, or when the signal is more likely to fail.

## Investigating factors that increase signal accuracy

### Holding a short position from signal entry to close of the day

In [553]:
def daily_pip_gain(df: Series, pct_adr: int):
    d_pip_gain = df["D_Gain"] if abs(df["D_Max_Up"]) < (df["ADR"] * pct_adr) else (df["ADR"] * -pct_adr)
    return d_pip_gain

def condition_stats(df: DataFrame, pct_adr: int):

    df["Pip_Gain"] = df.apply(daily_pip_gain, axis=1, args=[pct_adr])
    df["ADR%"] = df.apply(lambda x: x["ADR"] * pct_adr, axis=1)
    
    success_series = df.query(f"D_Max_Up.abs() < (ADR * {pct_adr})")["Pip_Gain"]
    fail_series = df.query(f"D_Max_Up.abs() >= (ADR * {pct_adr})")["Pip_Gain"]

    success_total = success_series.count()
    fail_total = fail_series.count()
    total_trades = success_total + fail_total
    
    win_rate = round(success_total / total_trades * 100,2)
    condition_total_pips = round(success_series.sum() + fail_series.sum(),6)

    return {
        "Pct_ADR": pct_adr,
        "Pct_ADR_Avg": df["ADR%"].mean(),
        "ADR_Avg": df["ADR"].mean(),
        "Total Trades": total_trades,
        "Win": success_total,
        "Loss": fail_total,
        "Win Rate": win_rate,
        "Avg_win": success_series.mean(),
        "Avg_Loss": fail_series.mean(),
        "Total Pips": condition_total_pips
    }
    
# columns
cols1 = [
    "Date", "Entry_Price", "Pip_Gain", "D_Max_Up", "ADR%", "D_Gain", "ADR"]
#df
d_gain_df = bearish_bbr_df

#### Using a stop loss set to a percentage of the ADR

Since we already know from the intial stats that the price will close lower on the day 48% of the time after the signal, we should try to limit the losses for the 52% of the times where it fails.

A `stop loss` is used to limit losses, and can be static (e.g. 10 pips) or dynamic (e.g. set as multiple of the `ATR`, or a trailing stop ... etc.).
The ATR takes into account the volatility of the last *x* candles, so is usually a good choice. 

For this particular scenario however, when the `Bear_BBR` signal occurs we are looking to hold a short position until the close of the day. The ATR is not the best approach here, because ATR will look at the average candle range within increments of the timeframe period (e.g. 15min) over *x* period of candles. 

To address this I will use a percentage of the the average daily range (**ADR**) as a stop loss. The ADR calculates the average daily price movement over last 30 days of trading, which will tell me the average number of pips the price moves within a day over that period.

To find a reasonable stop loss range, I'll iterate through different ADR percentages from 1 to 100.

In [554]:
d_gain_experimental_sl = [condition_stats(d_gain_df, x * 0.01) for x in range(1,101)]
d_gain_ex_sl_res_df = pd.DataFrame(d_gain_experimental_sl)
d_gain_ex_sl_res_df

,Pct_ADR,Pct_ADR_Avg,ADR_Avg,Total Trades,Win,Loss,Win Rate,Avg_win,Avg_Loss,Total Pips
0,0.01,0.000088,0.008848,448,6,442,1.34,0.004029,-0.000089,-0.014945
1,0.02,0.000177,0.008848,448,14,434,3.12,0.004249,-0.000177,-0.017316
2,0.03,0.000265,0.008848,448,28,420,6.25,0.004171,-0.000265,0.005474
3,0.04,0.000354,0.008848,448,41,407,9.15,0.003755,-0.000353,0.010274
4,0.05,0.000442,0.008848,448,53,395,11.83,0.003763,-0.000441,0.025115
5,0.06,0.000531,0.008848,448,61,387,13.62,0.003626,-0.000530,0.016154
6,0.07,0.000619,0.008848,448,71,377,15.85,0.003658,-0.000617,0.026949
7,0.08,0.000708,0.008848,448,79,369,17.63,0.003437,-0.000704,0.011619
8,0.09,0.000796,0.008848,448,82,366,18.30,0.003426,-0.000793,-0.009306
9,0.10,0.000885,0.008848,448,89,359,19.87,0.003687,-0.000882,0.011717
10,0.11,0.000973,0.008848,448,98,350,21.88,0.003979,-0.000969,0.050679
11,0.12,0.001062,0.008848,448,103,345,22.99,0.003962,-0.001057,0.043331
12,0.13,0.001150,0.008848,448,112,336,25.00,0.003852,-0.001145,0.046739
13,0.14,0.001239,0.008848,448,119,329,26.56,0.003903,-0.001233,0.058987
14,0.15,0.001327,0.008848,448,127,321,28.35,0.003821,-0.001320,0.061489
15,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
16,0.17,0.001504,0.008848,448,139,309,31.03,0.003629,-0.001499,0.041378
17,0.18,0.001593,0.008848,448,145,303,32.37,0.003535,-0.001588,0.031236
18,0.19,0.001681,0.008848,448,152,296,33.93,0.003447,-0.001675,0.028076
19,0.20,0.001770,0.008848,448,159,289,35.49,0.003390,-0.001761,0.030042
20,0.21,0.001858,0.008848,448,167,281,37.28,0.003287,-0.001849,0.029215
21,0.22,0.001947,0.008848,448,176,272,39.29,0.003136,-0.001937,0.025165
22,0.23,0.002035,0.008848,448,180,268,40.18,0.003113,-0.002025,0.017736
23,0.24,0.002124,0.008848,448,188,260,41.96,0.003006,-0.002118,0.014566
24,0.25,0.002212,0.008848,448,193,255,43.08,0.002973,-0.002208,0.010759
25,0.26,0.002301,0.008848,448,195,253,43.53,0.002984,-0.002296,0.001044
26,0.27,0.002389,0.008848,448,202,246,45.09,0.003010,-0.002389,0.020309
27,0.28,0.002477,0.008848,448,212,236,47.32,0.002941,-0.002475,0.039451
28,0.29,0.002566,0.008848,448,215,233,47.99,0.002903,-0.002567,0.026084
29,0.30,0.002654,0.008848,448,218,230,48.66,0.002938,-0.002655,0.029833
30,0.31,0.002743,0.008848,448,222,226,49.55,0.002928,-0.002745,0.029711
31,0.32,0.002831,0.008848,448,235,213,52.46,0.002756,-0.002833,0.044338
32,0.33,0.002920,0.008848,448,237,211,52.90,0.002734,-0.002926,0.030516
33,0.34,0.003008,0.008848,448,243,205,54.24,0.002684,-0.003010,0.035195
34,0.35,0.003097,0.008848,448,244,204,54.46,0.002683,-0.003097,0.022897
35,0.36,0.003185,0.008848,448,248,200,55.36,0.002637,-0.003189,0.016196
36,0.37,0.003274,0.008848,448,253,195,56.47,0.002571,-0.003266,0.013775
37,0.38,0.003362,0.008848,448,255,193,56.92,0.002553,-0.003357,0.003213
38,0.39,0.003451,0.008848,448,258,190,57.59,0.002497,-0.003444,-0.010188
39,0.40,0.003539,0.008848,448,264,184,58.93,0.002441,-0.003536,-0.006362
40,0.41,0.003628,0.008848,448,267,181,59.60,0.002403,-0.003632,-0.015803
41,0.42,0.003716,0.008848,448,274,174,61.16,0.002344,-0.003719,-0.004897
42,0.43,0.003805,0.008848,448,278,170,62.05,0.002296,-0.003812,-0.009646
43,0.44,0.003893,0.008848,448,281,167,62.72,0.002265,-0.003902,-0.015152
44,0.45,0.003982,0.008848,448,289,159,64.51,0.002182,-0.003978,-0.001688
45,0.46,0.004070,0.008848,448,293,155,65.40,0.002152,-0.004057,0.001692
46,0.47,0.004159,0.008848,448,299,149,66.74,0.002104,-0.004135,0.013133
47,0.48,0.004247,0.008848,448,305,143,68.08,0.002056,-0.004217,0.024075
48,0.49,0.004336,0.008848,448,307,141,68.53,0.002035,-0.004313,0.016463
49,0.50,0.004424,0.008848,448,308,140,68.75,0.002016,-0.004400,0.005105
50,0.51,0.004513,0.008848,448,309,139,68.97,0.002016,-0.004490,-0.001081
51,0.52,0.004601,0.008848,448,310,138,69.20,0.002026,-0.004568,-0.002141
52,0.53,0.004690,0.008848,448,312,136,69.64,0.002006,-0.004659,-0.007686
53,0.54,0.004778,0.008848,448,318,130,70.98,0.001914,-0.004749,-0.008817
54,0.55,0.004867,0.008848,448,319,129,71.21,0.001898,-0.004837,-0.018698
55,0.56,0.004955,0.008848,448,319,129,71.21,0.001898,-0.004925,-0.030044
56,0.57,0.005043,0.008848,448,321,127,71.65,0.001869,-0.005012,-0.036433
57,0.58,0.005132,0.008848,448,324,124,72.32,0.001818,-0.005100,-0.043514
58,0.59,0.005220,0.008848,448,330,118,73.66,0.001741,-0.005171,-0.035498
59,0.60,0.005309,0.008848,448,332,116,74.11,0.001709,-0.005259,-0.042776
60,0.61,0.005397,0.008848,448,335,113,74.78,0.001662,-0.005334,-0.045813
61,0.62,0.005486,0.008848,448,337,111,75.22,0.001625,-0.005411,-0.053137
62,0.63,0.005574,0.008848,448,344,104,76.79,0.001517,-0.005515,-0.051650
63,0.64,0.005663,0.008848,448,345,103,77.01,0.001496,-0.005597,-0.060307
64,0.65,0.005751,0.008848,448,347,101,77.46,0.001458,-0.005687,-0.068326
65,0.66,0.005840,0.008848,448,349,99,77.90,0.001421,-0.005768,-0.075116
66,0.67,0.005928,0.008848,448,353,95,78.79,0.001369,-0.005873,-0.074699
67,0.68,0.006017,0.008848,448,355,93,79.24,0.001339,-0.005971,-0.080076
68,0.69,0.006105,0.008848,448,358,90,79.91,0.001299,-0.006065,-0.080970
69,0.70,0.006194,0.008848,448,360,88,80.36,0.001260,-0.006147,-0.087385
70,0.71,0.006282,0.008848,448,363,85,81.03,0.001229,-0.006243,-0.084676
71,0.72,0.006371,0.008848,448,364,84,81.25,0.001230,-0.006308,-0.082139
72,0.73,0.006459,0.008848,448,369,79,82.37,0.001182,-0.006417,-0.070605
73,0.74,0.006548,0.008848,448,371,77,82.81,0.001159,-0.006494,-0.070087
74,0.75,0.006636,0.008848,448,374,74,83.48,0.001126,-0.006572,-0.065254
75,0.76,0.006725,0.008848,448,376,72,83.93,0.001101,-0.006662,-0.065859
76,0.77,0.006813,0.008848,448,377,71,84.15,0.001091,-0.006742,-0.067347
77,0.78,0.006902,0.008848,448,381,67,85.04,0.001045,-0.006860,-0.061341
78,0.79,0.006990,0.008848,448,384,64,85.71,0.000992,-0.006926,-0.062208
79,0.80,0.007079,0.008848,448,386,62,86.16,0.000977,-0.007000,-0.056710
80,0.81,0.007167,0.008848,448,387,61,86.38,0.000960,-0.007099,-0.061490
81,0.82,0.007256,0.008848,448,387,61,86.38,0.000960,-0.007186,-0.066836
82,0.83,0.007344,0.008848,448,387,61,86.38,0.000960,-0.007274,-0.072182
83,0.84,0.007432,0.008848,448,388,60,86.61,0.000946,-0.007378,-0.075796
84,0.85,0.007521,0.008848,448,388,60,86.61,0.000946,-0.007465,-0.081066
85,0.86,0.007609,0.008848,448,389,59,86.83,0.000939,-0.007568,-0.081351
86,0.87,0.007698,0.008848,448,390,58,87.05,0.000920,-0.007670,-0.085915
87,0.88,0.007786,0.008848,448,390,58,87.05,0.000920,-0.007758,-0.091028
88,0.89,0.007875,0.008848,448,391,57,87.28,0.000909,-0.007867,-0.093074
89,0.90,0.007963,0.008848,448,392,56,87.50,0.000890,-0.007959,-0.096632
90,0.91,0.008052,0.008848,448,393,55,87.72,0.000863,-0.007996,-0.100468
91,0.92,0.008140,0.008848,448,395,53,88.17,0.000829,-0.008102,-0.101827
92,0.93,0.008229,0.008848,448,396,52,88.39,0.000809,-0.008176,-0.104626
93,0.94,0.008317,0.008848,448,398,50,88.84,0.000774,-0.008269,-0.105565
94,0.95,0.008406,0.008848,448,401,47,89.51,0.000729,-0.008376,-0.101302
95,0.96,0.008494,0.008848,448,402,46,89.73,0.000708,-0.008463,-0.104641
96,0.97,0.008583,0.008848,448,404,44,90.18,0.000695,-0.008601,-0.097634
97,0.98,0.008671,0.008848,448,406,42,90.62,0.000654,-0.008673,-0.098861
98,0.99,0.008760,0.008848,448,408,40,91.07,0.000628,-0.008791,-0.095256
99,1.00,0.008848,0.008848,448,410,38,91.52,0.000603,-0.008924,-0.091701

- This shows the stop_loss is directly related to the win rate.
- It also shows that even with a higher win rate, it does not mean a higher `total pips` value. This makes sense because the larger the stop loss, the larger each loss will be.
- The ideal stop loss will be as low as possible and yield a reasonably high `total pips`.
- The maximum total pips returned was 0.011257 which was a result of 3% ADR stop loss, however we can't take this at face value because it could be an outlier. We also need to consider that when a trade is placed, a percentage of equity will be risked (e.g. 1%), so a lower ADR percentage will allow for a larger trade size to be used, which maximises the monetary return.
- We should look at the top ten `total pips` values and see what range of ADR percentages provided the best return.

In [555]:
top_ten_returns_by_adr_pct = d_gain_ex_sl_res_df["Total Pips"].nlargest(10)
top_ten_returns_by_adr_pct

15    0.065739
14    0.061489
13    0.058987
10    0.050679
12    0.046739
31    0.044338
11    0.043331
16    0.041378
27    0.039451
33    0.035195
Name: Total Pips, dtype: float64

The output shows the top ten `total pips` values by their index. Since the percent of ADR value is the `index+1`, we can see what contiguous index values provide the best return. I prefer contiguous values to get a better approximation of ADR percent ranges that work well, which should help to avoid outliers that may have been a fluke. 

From the output there's 3 contiguous index values between 15-17 which map to 16-18% ADR.

When you look at 16-18% ADR, the win rate is (33.59, 37.50, 39.06) but the average win for 16% ADR (0.003070) is double the average loss (0.001437). The 16% ADR value also yields the second highest `total pips` return out of all ADR percentage values. So 16% ADR looks good becauses it keeps the pip loss small, and still has a reasonable win rate which we can try to improve.

The reason for choosing the 2nd lowest ADR percentage value is that is allows us to take a larger trade size while risking the same equity percentage. A win with a larger trade value will generate a larger monetary return for the total pips. The reason for discounting 3% ADR is because of the terrible win rate, and the fact it is likely to be specifically good for this current dataset. 

To check the potential of monetary rerturns using this strategy, I'll simulate an account size of $100,000 and a trade risk value of 1%.

In [556]:
risk_ex_df = d_gain_ex_sl_res_df
risk_ex_df["Account_Size"] = risk_ex_df.apply(lambda x: 100000, axis=1)
risk_ex_df["Risk"] = risk_ex_df.apply(lambda x: 0.01, axis=1)
risk_ex_df["Trade_Value"] = risk_ex_df.apply(lambda x: round((x["Account_Size"] * x["Risk"])/x["Pct_ADR_Avg"],2), axis=1)
risk_ex_df["Return"] = risk_ex_df.apply(lambda x: round(x["Trade_Value"] * x["Total Pips"],2), axis=1)

risk_ex_df.filter(risk_ex_df["Return"].nlargest(10).index, axis=0)

,Pct_ADR,Pct_ADR_Avg,ADR_Avg,Total Trades,Win,Loss,Win Rate,Avg_win,Avg_Loss,Total Pips,Account_Size,Risk,Trade_Value,Return
4,0.05,0.000442,0.008848,448,53,395,11.83,0.003763,-0.000441,0.025115,100000,0.01,2260344.94,56768.56
10,0.11,0.000973,0.008848,448,98,350,21.88,0.003979,-0.000969,0.050679,100000,0.01,1027429.52,52069.10
13,0.14,0.001239,0.008848,448,119,329,26.56,0.003903,-0.001233,0.058987,100000,0.01,807266.05,47618.20
15,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739,100000,0.01,706357.79,46435.25
14,0.15,0.001327,0.008848,448,127,321,28.35,0.003821,-0.001320,0.061489,100000,0.01,753448.31,46328.78
6,0.07,0.000619,0.008848,448,71,377,15.85,0.003658,-0.000617,0.026949,100000,0.01,1614532.10,43510.03
11,0.12,0.001062,0.008848,448,103,345,22.99,0.003962,-0.001057,0.043331,100000,0.01,941810.39,40809.59
12,0.13,0.001150,0.008848,448,112,336,25.00,0.003852,-0.001145,0.046739,100000,0.01,869363.44,40633.18
5,0.06,0.000531,0.008848,448,61,387,13.62,0.003626,-0.000530,0.016154,100000,0.01,1883620.78,30428.01
3,0.04,0.000354,0.008848,448,41,407,9.15,0.003755,-0.000353,0.010274,100000,0.01,2825431.17,29028.48

The results show an ADR percentage of 1% yields the highest return but has a 3% win rate. This is clearly an anomaly because 2 to 3% ADR would also yield high returns if this was a good area for a stop loss. 

The better indicator is the range between 16-18%, which is a countiguous range of values with the highest monetary return out of the distribution. Based on this I'll view 16% ADR as an ideal stop loss and look for ways to improve the win rate.

#### Testing if the slope angle increases win rate

Considering the Bear_BBR is a short signal, we want to avoid cases were there is a strong uptrend. There's probably many ways to define a strong uptrend, but I think looking at the angle of the simple moving average (SMA) slopes is a way to define it. Generally, a strong trend or up-move will have SMA's pointing up. To quantify "pointing up" we'll say if the angle is greater than *x* the trend is too bullish, so skip the signal.

I think setting the angle limit to 45 degrees makes sense. Let's see what this shows:

In [557]:
# conditions
slope_lt_45_df = bearish_bbr_df.query("SMA32_Slope < 45").copy()
slope_lt_45_res = condition_stats(slope_lt_45_df, 0.16)
pd.DataFrame([slope_lt_45_res])

,Pct_ADR,Pct_ADR_Avg,ADR_Avg,Total Trades,Win,Loss,Win Rate,Avg_win,Avg_Loss,Total Pips
0,0.16,0.001417,0.008855,444,137,307,30.86,0.003681,-0.001412,0.070906

This shows a slight reduction in the total number of trades (98), which we'd expect with this filter. We also see a similar win rate, and an increase of pips gained, making the `total pips` 175. It definitely looks better, but we can also test for a range of angles betweem 90 and 0, to see of there is anything better.

In [558]:
slope_angle_ex = [condition_stats(bearish_bbr_df.query(f"SMA32_Slope < {x}").copy(), 0.16) for x in range(0,91)]
slope_angle_ex_df = pd.DataFrame(slope_angle_ex)
slope_angle_ex_df

,Pct_ADR,Pct_ADR_Avg,ADR_Avg,Total Trades,Win,Loss,Win Rate,Avg_win,Avg_Loss,Total Pips
0,0.16,0.001414,0.008837,252,62,190,24.60,0.003784,-0.001409,-0.033213
1,0.16,0.001413,0.008830,257,63,194,24.51,0.003804,-0.001409,-0.033742
2,0.16,0.001413,0.008830,262,65,197,24.81,0.003782,-0.001409,-0.031845
3,0.16,0.001413,0.008831,266,67,199,25.19,0.003811,-0.001408,-0.024892
4,0.16,0.001412,0.008823,271,70,201,25.83,0.003822,-0.001407,-0.015286
5,0.16,0.001411,0.008821,274,72,202,26.28,0.003788,-0.001406,-0.011360
6,0.16,0.001411,0.008821,274,72,202,26.28,0.003788,-0.001406,-0.011360
7,0.16,0.001410,0.008814,277,73,204,26.35,0.003741,-0.001405,-0.013610
8,0.16,0.001411,0.008821,279,74,205,26.52,0.003704,-0.001406,-0.014041
9,0.16,0.001411,0.008821,288,79,209,27.43,0.003822,-0.001404,0.008368
10,0.16,0.001411,0.008820,291,80,211,27.49,0.003786,-0.001405,0.006501
11,0.16,0.001411,0.008820,298,80,218,26.85,0.003786,-0.001405,-0.003353
12,0.16,0.001412,0.008822,307,87,220,28.34,0.003742,-0.001405,0.016445
13,0.16,0.001411,0.008822,315,88,227,27.94,0.003822,-0.001405,0.017345
14,0.16,0.001412,0.008828,318,89,229,27.99,0.003791,-0.001407,0.015265
15,0.16,0.001412,0.008827,324,91,233,28.09,0.003744,-0.001405,0.013272
16,0.16,0.001413,0.008832,328,95,233,28.96,0.003763,-0.001405,0.030037
17,0.16,0.001413,0.008829,330,95,235,28.79,0.003763,-0.001405,0.027334
18,0.16,0.001414,0.008835,336,96,240,28.57,0.003752,-0.001406,0.022688
19,0.16,0.001413,0.008829,339,97,242,28.61,0.003737,-0.001405,0.022489
20,0.16,0.001414,0.008835,343,100,243,29.15,0.003677,-0.001407,0.025795
21,0.16,0.001413,0.008834,344,101,243,29.36,0.003633,-0.001407,0.025010
22,0.16,0.001413,0.008830,352,102,250,28.98,0.003671,-0.001406,0.022961
23,0.16,0.001415,0.008844,362,106,256,29.28,0.003643,-0.001407,0.026033
24,0.16,0.001416,0.008847,373,112,261,30.03,0.003694,-0.001408,0.046284
25,0.16,0.001414,0.008840,376,114,262,30.32,0.003661,-0.001407,0.048643
26,0.16,0.001415,0.008841,378,115,263,30.42,0.003714,-0.001408,0.056842
27,0.16,0.001416,0.008851,382,116,266,30.37,0.003690,-0.001411,0.052827
28,0.16,0.001415,0.008847,387,118,269,30.49,0.003716,-0.001411,0.058907
29,0.16,0.001416,0.008849,391,120,271,30.69,0.003696,-0.001411,0.061235
30,0.16,0.001415,0.008844,397,121,276,30.48,0.003741,-0.001409,0.063779
31,0.16,0.001414,0.008836,406,125,281,30.79,0.003697,-0.001410,0.065924
32,0.16,0.001415,0.008841,412,127,285,30.83,0.003633,-0.001411,0.059312
33,0.16,0.001414,0.008837,415,129,286,31.08,0.003749,-0.001410,0.080259
34,0.16,0.001413,0.008830,418,129,289,30.86,0.003749,-0.001409,0.076516
35,0.16,0.001415,0.008841,422,131,291,31.04,0.003734,-0.001410,0.078801
36,0.16,0.001415,0.008844,424,131,293,30.90,0.003734,-0.001411,0.075803
37,0.16,0.001414,0.008836,434,133,301,30.65,0.003723,-0.001409,0.071092
38,0.16,0.001414,0.008838,436,134,302,30.73,0.003751,-0.001409,0.077058
39,0.16,0.001415,0.008845,437,135,302,30.89,0.003723,-0.001409,0.077053
40,0.16,0.001415,0.008845,437,135,302,30.89,0.003723,-0.001409,0.077053
41,0.16,0.001416,0.008847,439,135,304,30.75,0.003723,-0.001410,0.074062
42,0.16,0.001416,0.008853,442,136,306,30.77,0.003696,-0.001411,0.070977
43,0.16,0.001416,0.008851,443,137,306,30.93,0.003681,-0.001411,0.072582
44,0.16,0.001417,0.008855,444,137,307,30.86,0.003681,-0.001412,0.070906
45,0.16,0.001417,0.008855,444,137,307,30.86,0.003681,-0.001412,0.070906
46,0.16,0.001417,0.008854,445,137,308,30.79,0.003681,-0.001411,0.069574
47,0.16,0.001417,0.008854,446,137,309,30.72,0.003681,-0.001411,0.068117
48,0.16,0.001417,0.008854,446,137,309,30.72,0.003681,-0.001411,0.068117
49,0.16,0.001417,0.008854,446,137,309,30.72,0.003681,-0.001411,0.068117
50,0.16,0.001417,0.008854,446,137,309,30.72,0.003681,-0.001411,0.068117
51,0.16,0.001417,0.008854,446,137,309,30.72,0.003681,-0.001411,0.068117
52,0.16,0.001417,0.008854,446,137,309,30.72,0.003681,-0.001411,0.068117
53,0.16,0.001417,0.008854,446,137,309,30.72,0.003681,-0.001411,0.068117
54,0.16,0.001417,0.008854,446,137,309,30.72,0.003681,-0.001411,0.068117
55,0.16,0.001417,0.008854,446,137,309,30.72,0.003681,-0.001411,0.068117
56,0.16,0.001417,0.008854,446,137,309,30.72,0.003681,-0.001411,0.068117
57,0.16,0.001416,0.008851,447,137,310,30.65,0.003681,-0.001411,0.066928
58,0.16,0.001416,0.008851,447,137,310,30.65,0.003681,-0.001411,0.066928
59,0.16,0.001416,0.008851,447,137,310,30.65,0.003681,-0.001411,0.066928
60,0.16,0.001416,0.008851,447,137,310,30.65,0.003681,-0.001411,0.066928
61,0.16,0.001416,0.008851,447,137,310,30.65,0.003681,-0.001411,0.066928
62,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
63,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
64,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
65,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
66,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
67,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
68,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
69,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
70,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
71,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
72,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
73,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
74,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
75,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
76,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
77,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
78,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
79,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
80,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
81,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
82,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
83,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
84,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
85,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
86,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
87,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
88,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
89,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739
90,0.16,0.001416,0.008848,448,137,311,30.58,0.003681,-0.001410,0.065739

We can view the angles with the largest returns:

In [559]:
slope_angle_ex_df["Account_Size"] = slope_angle_ex_df.apply(lambda x: 100000, axis=1)
slope_angle_ex_df["Risk"] = slope_angle_ex_df.apply(lambda x: 0.01, axis=1)
slope_angle_ex_df["Trade_Value"] = slope_angle_ex_df.apply(lambda x: round((x["Account_Size"] * x["Risk"])/x["Pct_ADR_Avg"],2), axis=1)
slope_angle_ex_df["Return"] = slope_angle_ex_df.apply(lambda x: round(x["Trade_Value"] * x["Total Pips"],2), axis=1)
slope_angle_ex_df.filter(slope_angle_ex_df["Total Pips"].nlargest(10).index, axis=0)

,Pct_ADR,Pct_ADR_Avg,ADR_Avg,Total Trades,Win,Loss,Win Rate,Avg_win,Avg_Loss,Total Pips,Account_Size,Risk,Trade_Value,Return
33,0.16,0.001414,0.008837,415,129,286,31.08,0.003749,-0.001410,0.080259,100000,0.01,707227.74,56761.39
35,0.16,0.001415,0.008841,422,131,291,31.04,0.003734,-0.001410,0.078801,100000,0.01,706917.91,55705.84
38,0.16,0.001414,0.008838,436,134,302,30.73,0.003751,-0.001409,0.077058,100000,0.01,707195.65,54495.08
39,0.16,0.001415,0.008845,437,135,302,30.89,0.003723,-0.001409,0.077053,100000,0.01,706596.41,54445.37
40,0.16,0.001415,0.008845,437,135,302,30.89,0.003723,-0.001409,0.077053,100000,0.01,706596.41,54445.37
34,0.16,0.001413,0.008830,418,129,289,30.86,0.003749,-0.001409,0.076516,100000,0.01,707816.92,54159.32
36,0.16,0.001415,0.008844,424,131,293,30.90,0.003734,-0.001411,0.075803,100000,0.01,706722.05,53571.65
41,0.16,0.001416,0.008847,439,135,304,30.75,0.003723,-0.001410,0.074062,100000,0.01,706417.02,52318.66
43,0.16,0.001416,0.008851,443,137,306,30.93,0.003681,-0.001411,0.072582,100000,0.01,706096.34,51249.88
37,0.16,0.001414,0.008836,434,133,301,30.65,0.003723,-0.001409,0.071092,100000,0.01,707303.44,50283.62

This shows angles between the range of 28 and 30 have returns above 287 pips, however the best fit is **33** degrees. From this sample, if we only took `Bear_BBR` trades with an SMA32 slope under 29 degrees the `total pips` would be 319.7 with a monetary return of $22575.84 (excluding fees and commissions). 

The results look good, but this only shows filtering for trades which are held until the close of the day. It relies on the day being a complete reversal day and also using a tighter stop loss (16% ADR). These two factors may be unique to this dataset so we need to test over a different year and see if the results are similar.

When I run the tests over the 2025 period with file `FE_V2_GBPUSD_15mins_1yr_End_20250311`, it turns out the optimum stop loss is 2% ADR which gives a 3.64% win rate, but does deliver the highest return (~12k). Obviously this is unrealistic as we have to account for the spread + commissions, so the actual return is probably far less. Outside of that, if we look at the top ten highest `total pips`, the next best stop loss is 29% ADR, which is more reasonable and carries a 50% win rate and 280 pip gain over 147 trades (when sma32_slope < 50).

So comparing the two we can consider:
- The approach to calculating the stop loss is biased to the dataset, which is why the best stop loss (by gains) differs between 2024-2025 and 2025-2026. When looking at common ADR% stop loss values across both data sets, 25-30 seems to appear in both, so would be a good realistic start.
- The optimal slop value also changes, with the optimal slop being under 5 degress in 2024-2025 dataset. The slop is considered in the signal definition as well, so I think this reading is probably biased to the dataset.
- The max move down after the signal was greater than the max move up 47% of the time on both datasets. This shows the signals are good and are correctly identifying a drop in price at least half the time.

Since bollinger bands can be used for breakouts and mean reversion, it does explain why there's ~50% accuracy. In FX there are a lot of days where price moves in a range, or has low trend movement. This means even though a signal predicts a successful fall in price, the price could still reverse and close above the signal candle. To solve this we need to define a take profit target that will maximise the gains on a successful signal. When I briefly investigated strategies for targets by manual chart analysis, there appears to be a relationship between the high of the signal candle and the intraday range. I will delve into this further in the next section.

## High vs ADR% Stop Loss - 38.2% ADR Target

In [2805]:
def get_bear_bbr_pip_gain(
        df: Series, 
        high: Series, 
        low: Series,
        close: Series  
        ):
    """Get the pip gain and apply to df"""

    high_win = 0
    high_loss = 0
    adr_win = 0
    adr_loss = 0
    high_target_pips = 0 
    adr_target_pips = 0 
    high_sl_pips = 0
    adr_sl_pips = 0
    high_gain = 0
    adr_gain = 0
    high_trade_start =  None
    high_trade_end = None
    adr_trade_start =  None
    adr_trade_end = None
    
    if df["Bear_BBR"] is True:
        idx = int(df["Idx"])
        iday_idx = int(df["Iday_Idx"])
        # get signal start of fx day timestamp
        day_start_ts = high.iloc[idx-iday_idx:idx-iday_idx+1].index[0]
        OFFSET = day_start_ts + pd.DateOffset(days=1) # end of signal's fx day
        START = df.name # signal start time
        TD = pd.Timedelta(minutes=15)
        END = OFFSET - TD # 17:00 on the signals fx day

        # get stop loss time:
        sl_window = high.loc[START+TD:END] # from signal idx+1 to EOD
        close_window = close.loc[START+TD:END] # from signal idx+1 to EOD
        high_stop = False 
        high_sl_ts = None # get timestamp when stopped out
        adr_stop = False # update if stopped 
        adr_sl_ts = None # get timestamp when stopped out
        stoploss_high = max(high.iloc[idx-1], high.iloc[idx])

        for i in range(len(sl_window)):
            if sl_window.iloc[i] >= stoploss_high : #stoploss_high:
                high_stop = True # trade hit stop loss
                # get stop loss timestamp
                high_sl_ts = sl_window.iloc[i:i+1].index[0]
                break 
        for i in range(len(sl_window)): 
            if sl_window.iloc[i] >= (df["Close"] + df["ADR"] * 0.25 ): #(stoploss_high + df["ATR"]):
                adr_stop = True # trade hit stop loss
                # get stop loss timestamp
                adr_sl_ts = sl_window.iloc[i:i+1].index[0] 
                break
        # if not stopped out then the stop window is signal:EOD
        # don't include trade if it is the last candle of the day
        if high_stop is False:
            if close_window.empty is False:
                high_sl_ts = close_window.iloc[-1:].index[0]
            else:
                high_sl_ts = START+TD
        if adr_stop is False:
            if close_window.empty is False:
                adr_sl_ts = close_window.iloc[-1:].index[0]
            else:
                adr_sl_ts = START+TD

        # Take profit price
        tp = df["Close"] - (df["ADR"] * 0.382)

        # High trade window
        high_tp_window = low[START+TD:high_sl_ts+TD]
        high_trade_start = START+TD
        high_trade_end = high_sl_ts
        high_target_pips = df["Close"] - tp
        high_sl_pips = df["Close"] - stoploss_high
        if high_tp_window.min() <= tp:
            high_win = 1
            high_gain = df["Close"] - tp
        else:
            high_loss = 1
            if high_stop is True:
                high_gain = high_sl_pips
            else:
                high_gain = df["Close"] - close_window.iloc[-1] if close_window.empty is False else 0           
        # ATR trade window
        adr_tp_window = low[START+TD:adr_sl_ts+TD]
        adr_trade_start = START+TD
        adr_trade_end = adr_sl_ts
        adr_target_pips = df["Close"] - tp
        adr_sl_pips = df["Close"] - (df["Close"] + df["ADR"] * 0.25) 
        if adr_tp_window.min() <= tp:
            adr_win = 1
            adr_gain = df["Close"] - tp
        else:
            adr_loss = 1
            if adr_stop is True:
                adr_gain = adr_sl_pips
            else:
                adr_gain = df["Close"] - close_window.iloc[-1] if close_window.empty is False else 0
    
    data = high_win, high_loss, \
        adr_win, adr_loss, \
        high_target_pips, adr_target_pips, \
        high_sl_pips, adr_sl_pips, \
        high_gain, adr_gain, \
        adr_trade_start, adr_trade_end, \
        high_trade_start, high_trade_end
    
    return data

# Set new columns 
pct_50_idr_cols = [
    "High_Win", "High_Loss", 
    "ADR_Win", "ADR_Loss", 
    "High_TP", "ADR_TP", 
    "High_SL", "ADR_SL", 
    "High_Gain", "ADR_Gain",
    "ADR_Trade_Start", "ADR_Trade_End",
    "High_Trade_Start", "High_Trade_End"
    ]

df[pct_50_idr_cols] = df.apply(get_bear_bbr_pip_gain, axis=1, args=[df["High"], df["Low"], df["Close"]], result_type='expand')

In [2806]:
# check signals

df[
    [
        "Open", "High", "Low","Close", "Range",
        "ATR", "Iday_Range", "ADR", "RSI", "RSI_DVG", "Close_%SMA",
        "Bear_BBR", "Bear_Engulf", "Shooting_Star",
        "Dark_Cloud", "Hammer","BBU_BO", "IHR", "S_R",
        "SMA32_Slope", "SMA_Trend", *pct_50_idr_cols
     ]
].query("Bear_BBR == True")

,Open,High,Low,Close,Range,ATR,Iday_Range,ADR,RSI,RSI_DVG,Close_%SMA,Bear_BBR,Bear_Engulf,Shooting_Star,Dark_Cloud,Hammer,BBU_BO,IHR,S_R,SMA32_Slope,SMA_Trend,High_Win,High_Loss,ADR_Win,ADR_Loss,High_TP,ADR_TP,High_SL,ADR_SL,High_Gain,ADR_Gain,ADR_Trade_Start,ADR_Trade_End,High_Trade_Start,High_Trade_End
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2025-04-24 04:15:00-04:00,1.330050,1.330100,1.329455,1.329755,0.000645,0.000923,0.005130,0.010477,65.919402,NaN,0.133426,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.602304,2,0.0,1.0,0.0,1.0,0.004002,0.004002,-0.000625,-0.002619,-0.000625,-0.002619,2025-04-24 04:30:00-04:00,2025-04-24 10:15:00-04:00,2025-04-24 04:30:00-04:00,2025-04-24 04:45:00-04:00
2025-04-24 05:15:00-04:00,1.331510,1.331515,1.330775,1.330800,0.000740,0.001015,0.006450,0.010477,66.652679,NaN,0.141492,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.269961,2,0.0,1.0,0.0,1.0,0.004002,0.004002,-0.000900,-0.002619,-0.000900,-0.002619,2025-04-24 05:30:00-04:00,2025-04-24 13:00:00-04:00,2025-04-24 05:30:00-04:00,2025-04-24 06:00:00-04:00
2025-04-24 10:45:00-04:00,1.332840,1.333270,1.330915,1.331455,0.002355,0.001099,0.008020,0.010477,56.168380,True,0.027703,True,True,NaN,NaN,NaN,NaN,True,4.0,43.389699,2,0.0,1.0,0.0,1.0,0.004002,0.004002,-0.001815,-0.002619,-0.001815,-0.002619,2025-04-24 11:00:00-04:00,2025-04-24 15:30:00-04:00,2025-04-24 11:00:00-04:00,2025-04-24 13:00:00-04:00
2025-04-24 15:45:00-04:00,1.334300,1.334425,1.333715,1.333740,0.000710,0.000722,0.009220,0.010477,62.063477,NaN,0.097659,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.787895,2,0.0,1.0,0.0,1.0,0.004002,0.004002,-0.000730,-0.002619,-0.000730,-0.000445,2025-04-24 16:00:00-04:00,2025-04-24 16:45:00-04:00,2025-04-24 16:00:00-04:00,2025-04-24 16:15:00-04:00
2025-04-25 03:15:00-04:00,1.330950,1.331350,1.330235,1.330305,0.001115,0.000969,0.006820,0.010625,51.626643,NaN,0.091534,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-27.205996,1,0.0,1.0,0.0,1.0,0.004059,0.004059,-0.001125,-0.002656,-0.001125,-0.002656,2025-04-25 03:30:00-04:00,2025-04-25 11:45:00-04:00,2025-04-25 03:30:00-04:00,2025-04-25 06:45:00-04:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-09 02:00:00-04:00,1.333365,1.334075,1.332485,1.332730,0.001590,0.001371,0.006865,0.009884,55.186083,NaN,0.149988,True,NaN,NaN,True,NaN,NaN,NaN,NaN,0.835504,2,0.0,1.0,0.0,1.0,0.003776,0.003776,-0.001345,-0.002471,-0.001345,-0.002471,2026-03-09 02:15:00-04:00,2026-03-09 05:30:00-04:00,2026-03-09 02:15:00-04:00,2026-03-09 03:30:00-04:00
2026-03-09 11:15:00-04:00,1.339725,1.339780,1.338540,1.339030,0.001240,0.001635,0.011760,0.009884,65.245502,NaN,0.182250,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.519957,2,0.0,1.0,0.0,1.0,0.003776,0.003776,-0.001040,-0.002471,-0.001040,-0.002471,2026-03-09 11:30:00-04:00,2026-03-09 15:15:00-04:00,2026-03-09 11:30:00-04:00,2026-03-09 12:00:00-04:00
2026-03-09 15:45:00-04:00,1.343725,1.344570,1.342880,1.342940,0.001690,0.001246,0.016260,0.009884,68.540948,True,0.230155,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.532578,2,0.0,1.0,0.0,1.0,0.003776,0.003776,-0.001630,-0.002471,-0.001630,-0.000450,2026-03-09 16:00:00-04:00,2026-03-09 16:45:00-04:00,2026-03-09 16:00:00-04:00,2026-03-09 16:45:00-04:00
2026-03-10 02:45:00-04:00,1.345660,1.345775,1.344640,1.345030,0.001135,0.000777,0.004415,0.010196,63.597555,True,0.151154,True,NaN,NaN,True,NaN,NaN,NaN,3.0,26.133723,1,0.0,1.0,0.0,1.0,0.003895,0.003895,-0.000745,-0.002549,-0.000745,-0.002549,2026-03-10 03:00:00-04:00,2026-03-10 03:15:00-04:00,2026-03-10 03:00:00-04:00,2026-03-10 03:00:00-04:00
2026-03-10 20:45:00-04:00,1.343530,1.343750,1.342975,1.343060,0.000775,0.000553,0.002735,0.009747,51.484603,NaN,0.074070,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-26.588919,1,0.0,1.0,0.0,1.0,0.003723,0.003723,-0.000690,-0.002437,-0.000690,-0.002437,2026-03-10 21:00:00-04:00,2026-03-11 00:45:00-04:00,2026-03-10 21:00:00-04:00,2026-03-10 21:15:00-04:00

In [2807]:
df2 = df.query("Bear_BBR == True").between_time("02:00", "11:00")

In [2808]:
# Stats - High as SL
high_win_count = df2.query("Bear_BBR == True and High_Win > 0")["Bear_BBR"].count()
high_loss_count = df2.query("Bear_BBR == True and High_Loss > 0")["Bear_BBR"].count()
high_total_trades = high_win_count + high_loss_count
high_win_rate = high_win_count/high_total_trades * 100
high_win = df2.query("Bear_BBR == True and High_Gain > 0")["High_Gain"]
high_loss = df2.query("Bear_BBR == True and High_Gain < 0")["High_Gain"]
high_win_avg_pips = high_win.mean()
high_loss_avg_pips = high_loss.mean()
high_win_pips = high_win.sum()
high_loss_pips = high_loss.sum()
high_total_pips = high_win_pips + high_loss_pips

high_pct_50_idr = {
    "Win_Count": high_win_count,
    "Loss_Count": high_loss_count,
    "Total_Trades": high_total_trades,
    "Win_Rate": high_win_rate,
    "Avg_Win": high_win_avg_pips,
    "Avg_Loss": high_loss_avg_pips,
    "Win_Pips": high_win_pips,
    "Loss_Pips": high_loss_pips,
    "Total_Pips": high_total_pips
}

# Stats - High + ATR as SL
adr_win_count = df2.query("Bear_BBR == True and ADR_Win > 0")["Bear_BBR"].count()
adr_loss_count = df2.query("Bear_BBR == True and ADR_Loss > 0")["Bear_BBR"].count()
adr_total_trades = adr_win_count + adr_loss_count
adr_win_rate = adr_win_count/adr_total_trades * 100
adr_win = df2.query("Bear_BBR == True and ADR_Gain > 0")["ADR_Gain"]
adr_loss = df2.query("Bear_BBR == True and ADR_Gain < 0")["ADR_Gain"]
adr_win_avg_pips = adr_win.mean()
adr_loss_avg_pips = adr_loss.mean()
adr_win_pips = adr_win.sum()
adr_loss_pips = adr_loss.sum()
adr_total_pips = adr_win_pips + adr_loss_pips

adr_pct_50_idr = {
    "Win_Count": adr_win_count,
    "Loss_Count": adr_loss_count,
    "Total_Trades": adr_total_trades,
    "Win_Rate": adr_win_rate,
    "Avg_Win": adr_win_avg_pips,
    "Avg_Loss": adr_loss_avg_pips,
    "Win_Pips": adr_win_pips,
    "Loss_Pips": adr_loss_pips,
    "Total_Pips": adr_total_pips
}

pd.DataFrame([high_pct_50_idr, adr_pct_50_idr])

,Win_Count,Loss_Count,Total_Trades,Win_Rate,Avg_Win,Avg_Loss,Win_Pips,Loss_Pips,Total_Pips
0,46,157,203,22.660099,0.002968,-0.001090,0.166226,-0.160210,0.006016
1,70,133,203,34.482759,0.002907,-0.002039,0.261614,-0.230378,0.031237

In [2671]:
#pd.options.display.max_rows = 100
df2[["RSI", "Iday_Range", "RSI_DVG", "SMA32_Slope", "SMA16_Slope",*pct_50_idr_cols]].iloc[0:100].query("High_Gain < 0")

,RSI,Iday_Range,RSI_DVG,SMA32_Slope,SMA16_Slope,High_Win,High_Loss,ATR_Win,ATR_Loss,High_TP,ATR_TP,High_SL,ATR_SL,High_Gain,ATR_Gain,ADR_Trade_Start,ADR_Trade_End,High_Trade_Start,High_Trade_End
Date,,,,,,,,,,,,,,,,,,,
2024-04-25 03:00:00-04:00,70.613649,0.005145,NaN,37.812953,51.846915,0.0,1.0,0.0,1.0,0.002921,0.002921,-0.001360,-0.001912,-0.001360,-0.001912,2024-04-25 03:15:00-04:00,2024-04-25 04:00:00-04:00,2024-04-25 03:15:00-04:00,2024-04-25 03:45:00-04:00
2024-04-26 02:15:00-04:00,55.573530,0.002095,NaN,-1.163660,10.734924,0.0,1.0,0.0,1.0,0.002894,0.002894,-0.000425,-0.001894,-0.000425,-0.001894,2024-04-26 02:30:00-04:00,2024-04-26 04:30:00-04:00,2024-04-26 02:30:00-04:00,2024-04-26 02:30:00-04:00
2024-04-26 02:45:00-04:00,57.323323,0.002155,NaN,1.372449,27.465035,0.0,1.0,0.0,1.0,0.002894,0.002894,-0.000445,-0.001894,-0.000445,-0.001894,2024-04-26 03:00:00-04:00,2024-04-26 04:30:00-04:00,2024-04-26 03:00:00-04:00,2024-04-26 04:00:00-04:00
2024-05-01 05:00:00-04:00,58.836509,0.003195,NaN,9.462322,37.174255,0.0,1.0,0.0,1.0,0.003056,0.003056,-0.000585,-0.002000,-0.000585,-0.002000,2024-05-01 05:15:00-04:00,2024-05-01 14:00:00-04:00,2024-05-01 05:15:00-04:00,2024-05-01 10:00:00-04:00
2024-05-13 02:30:00-04:00,55.744258,0.001840,NaN,8.413991,25.650706,0.0,1.0,0.0,1.0,0.002997,0.002997,-0.000650,-0.001961,-0.000650,-0.001961,2024-05-13 02:45:00-04:00,2024-05-13 07:30:00-04:00,2024-05-13 02:45:00-04:00,2024-05-13 05:00:00-04:00
2024-05-13 07:45:00-04:00,67.491098,0.003645,True,24.326933,44.335906,0.0,1.0,0.0,1.0,0.002997,0.002997,-0.000790,-0.001961,-0.000790,-0.001961,2024-05-13 08:00:00-04:00,2024-05-13 09:45:00-04:00,2024-05-13 08:00:00-04:00,2024-05-13 08:30:00-04:00
2024-05-15 04:30:00-04:00,64.191352,0.002590,NaN,22.006917,26.850813,0.0,1.0,0.0,1.0,0.002988,0.002988,-0.000315,-0.001955,-0.000315,-0.001955,2024-05-15 04:45:00-04:00,2024-05-15 08:30:00-04:00,2024-05-15 04:45:00-04:00,2024-05-15 04:45:00-04:00
2024-05-20 00:15:00-04:00,59.188667,0.001775,NaN,3.516880,14.316759,0.0,1.0,0.0,1.0,0.003002,0.003002,-0.000235,-0.001964,-0.000235,0.000250,2024-05-20 00:30:00-04:00,2024-05-20 16:45:00-04:00,2024-05-20 00:30:00-04:00,2024-05-20 10:30:00-04:00
2024-05-21 02:30:00-04:00,57.322224,0.002080,NaN,7.799787,26.229852,0.0,1.0,0.0,1.0,0.002983,0.002983,-0.000515,-0.001952,-0.000515,0.000370,2024-05-21 02:45:00-04:00,2024-05-21 16:45:00-04:00,2024-05-21 02:45:00-04:00,2024-05-21 03:00:00-04:00
2024-05-21 03:15:00-04:00,57.013441,0.002355,NaN,7.682586,24.722131,0.0,1.0,0.0,1.0,0.002983,0.002983,-0.000595,-0.001952,-0.000595,0.000565,2024-05-21 03:30:00-04:00,2024-05-21 16:45:00-04:00,2024-05-21 03:30:00-04:00,2024-05-21 05:45:00-04:00
2024-05-21 22:15:00-04:00,60.665565,0.001655,NaN,10.763727,20.921439,0.0,1.0,0.0,1.0,0.002957,0.002957,-0.000400,-0.001936,-0.000400,-0.001936,2024-05-21 22:30:00-04:00,2024-05-22 02:00:00-04:00,2024-05-21 22:30:00-04:00,2024-05-22 02:00:00-04:00
2024-05-22 09:30:00-04:00,61.237189,0.006110,NaN,32.602304,38.183576,0.0,1.0,1.0,0.0,0.002957,0.002957,-0.000530,-0.001936,-0.000530,0.002957,2024-05-22 09:45:00-04:00,2024-05-22 16:45:00-04:00,2024-05-22 09:45:00-04:00,2024-05-22 12:45:00-04:00
2024-05-24 03:15:00-04:00,55.397265,0.002930,NaN,5.030258,22.262966,0.0,1.0,0.0,1.0,0.002788,0.002788,-0.000710,-0.001824,-0.000710,-0.001824,2024-05-24 03:30:00-04:00,2024-05-24 06:00:00-04:00,2024-05-24 03:30:00-04:00,2024-05-24 04:45:00-04:00
2024-05-27 06:00:00-04:00,62.832212,0.002385,NaN,14.959274,32.897818,0.0,1.0,0.0,1.0,0.002715,0.002715,-0.000460,-0.001777,-0.000460,-0.001777,2024-05-27 06:15:00-04:00,2024-05-27 09:30:00-04:00,2024-05-27 06:15:00-04:00,2024-05-27 08:45:00-04:00
2024-05-28 07:15:00-04:00,59.214509,0.002640,True,5.651495,28.535137,0.0,1.0,0.0,1.0,0.002692,0.002692,-0.000570,-0.001761,-0.000570,-0.001761,2024-05-28 07:30:00-04:00,2024-05-28 09:15:00-04:00,2024-05-28 07:30:00-04:00,2024-05-28 08:00:00-04:00
2024-05-29 02:45:00-04:00,58.178687,0.001855,NaN,2.802868,21.646890,0.0,1.0,1.0,0.0,0.002666,0.002666,-0.000390,-0.001745,-0.000390,0.002666,2024-05-29 03:00:00-04:00,2024-05-29 16:45:00-04:00,2024-05-29 03:00:00-04:00,2024-05-29 03:00:00-04:00
2024-06-02 20:30:00-04:00,62.144569,0.001340,NaN,25.163747,8.355576,0.0,1.0,1.0,0.0,0.002650,0.002650,-0.000275,-0.001734,-0.000275,0.002650,2024-06-02 20:45:00-04:00,2024-06-03 10:00:00-04:00,2024-06-02 20:45:00-04:00,2024-06-02 20:45:00-04:00
2024-06-07 03:15:00-04:00,59.154353,0.002050,NaN,8.443191,22.822981,0.0,1.0,1.0,0.0,0.002571,0.002571,-0.000575,-0.001683,-0.000575,0.002571,2024-06-07 03:30:00-04:00,2024-06-07 08:30:00-04:00,2024-06-07 03:30:00-04:00,2024-06-07 07:30:00-04:00
2024-06-12 04:15:00-04:00,63.925266,0.002575,NaN,21.466199,31.919466,0.0,1.0,0.0,1.0,0.002496,0.002496,-0.000380,-0.001634,-0.000380,-0.001634,2024-06-12 04:30:00-04:00,2024-06-12 08:30:00-04:00,2024-06-12 04:30:00-04:00,2024-06-12 04:30:00-04:00
2024-06-13 04:30:00-04:00,56.551779,0.002910,NaN,0.566971,29.176079,0.0,1.0,1.0,0.0,0.002551,0.002551,-0.000510,-0.001670,-0.000510,0.002551,2024-06-13 04:45:00-04:00,2024-06-13 16:45:00-04:00,2024-06-13 04:45:00-04:00,2024-06-13 04:45:00-04:00
2024-06-24 10:15:00-04:00,76.171095,0.006530,NaN,41.639096,43.152390,0.0,1.0,0.0,1.0,0.002513,0.002513,-0.000825,-0.001645,-0.000825,0.000635,2024-06-24 10:30:00-04:00,2024-06-24 16:45:00-04:00,2024-06-24 10:30:00-04:00,2024-06-24 10:30:00-04:00
2024-06-27 02:30:00-04:00,57.199338,0.003075,NaN,19.978314,22.772258,0.0,1.0,0.0,1.0,0.002434,0.002434,-0.000710,-0.001593,-0.000710,-0.001593,2024-06-27 02:45:00-04:00,2024-06-27 06:30:00-04:00,2024-06-27 02:45:00-04:00,2024-06-27 02:45:00-04:00
2024-06-30 21:30:00-04:00,63.264099,0.002280,NaN,15.042801,29.674130,0.0,1.0,0.0,1.0,0.002407,0.002407,-0.000605,-0.001575,-0.000605,-0.001575,2024-06-30 21:45:00-04:00,2024-07-01 02:00:00-04:00,2024-06-30 21:45:00-04:00,2024-07-01 01:45:00-04:00
2024-07-01 02:30:00-04:00,70.542995,0.004650,NaN,36.697623,47.726311,0.0,1.0,0.0,1.0,0.002407,0.002407,-0.000785,-0.001575,-0.000785,-0.001575,2024-07-01 02:45:00-04:00,2024-07-01 10:00:00-04:00,2024-07-01 02:45:00-04:00,2024-07-01 10:00:00-04:00
2024-07-02 08:15:00-04:00,69.152850,0.004740,True,25.188188,52.497869,0.0,1.0,0.0,1.0,0.002459,0.002459,-0.000650,-0.001610,-0.000650,-0.001610,2024-07-02 08:30:00-04:00,2024-07-02 09:00:00-04:00,2024-07-02 08:30:00-04:00,2024-07-02 08:45:00-04:00
2024-07-03 03:30:00-04:00,64.480001,0.001975,NaN,5.946863,17.679681,0.0,1.0,0.0,1.0,0.002500,0.002500,-0.000430,-0.001636,-0.000430,-0.001636,2024-07-03 03:45:00-04:00,2024-07-03 08:15:00-04:00,2024-07-03 03:45:00-04:00,2024-07-03 04:15:00-04:00
2024-07-03 06:45:00-04:00,58.785138,0.003020,NaN,20.320221,35.032056,0.0,1.0,0.0,1.0,0.002500,0.002500,-0.000880,-0.001636,-0.000880,-0.001636,2024-07-03 07:00:00-04:00,2024-07-03 08:15:00-04:00,2024-07-03 07:00:00-04:00,2024-07-03 08:15:00-04:00
2024-07-03 08:45:00-04:00,69.907778,0.004415,NaN,34.346097,42.961205,0.0,1.0,0.0,1.0,0.002500,0.002500,-0.000365,-0.001636,-0.000365,-0.001636,2024-07-03 09:00:00-04:00,2024-07-03 09:15:00-04:00,2024-07-03 09:00:00-04:00,2024-07-03 09:00:00-04:00
2024-07-03 21:00:00-04:00,60.737048,0.001250,NaN,-5.651495,18.649539,0.0,1.0,0.0,1.0,0.002548,0.002548,-0.000390,-0.001668,-0.000390,-0.001668,2024-07-03 21:15:00-04:00,2024-07-04 11:00:00-04:00,2024-07-03 21:15:00-04:00,2024-07-04 04:00:00-04:00
2024-07-04 20:45:00-04:00,61.871461,0.001300,NaN,4.437497,10.446589,0.0,1.0,0.0,1.0,0.002504,0.002504,-0.000300,-0.001639,-0.000300,-0.001639,2024-07-04 21:00:00-04:00,2024-07-05 04:30:00-04:00,2024-07-04 21:00:00-04:00,2024-07-04 21:15:00-04:00
2024-07-10 20:45:00-04:00,67.047386,0.001065,True,15.846814,19.449400,0.0,1.0,0.0,1.0,0.002488,0.002488,-0.000390,-0.001628,-0.000390,-0.001628,2024-07-10 21:00:00-04:00,2024-07-11 04:00:00-04:00,2024-07-10 21:00:00-04:00,2024-07-10 22:00:00-04:00
2024-07-26 03:30:00-04:00,58.562467,0.002240,NaN,15.542579,18.434949,0.0,1.0,0.0,1.0,0.002328,0.002328,-0.000520,-0.001524,-0.000520,0.000200,2024-07-26 03:45:00-04:00,2024-07-26 16:45:00-04:00,2024-07-26 03:45:00-04:00,2024-07-26 06:45:00-04:00
2024-08-05 19:15:00-04:00,61.242650,0.002605,NaN,29.062205,50.292070,0.0,1.0,1.0,0.0,0.002502,0.002502,-0.000415,-0.001637,-0.000415,0.002502,2024-08-05 19:30:00-04:00,2024-08-06 16:45:00-04:00,2024-08-05 19:30:00-04:00,2024-08-05 19:30:00-04:00
2024-08-06 21:00:00-04:00,55.402063,0.002320,NaN,-1.640837,24.376469,0.0,1.0,0.0,1.0,0.002627,0.002627,-0.000350,-0.001720,-0.000350,-0.001720,2024-08-06 21:15:00-04:00,2024-08-07 00:30:00-04:00,2024-08-06 21:15:00-04:00,2024-08-06 22:00:00-04:00
2024-08-15 02:15:00-04:00,64.952449,0.003215,True,24.103543,37.438572,0.0,1.0,0.0,1.0,0.002587,0.002587,-0.000475,-0.001693,-0.000475,-0.001693,2024-08-15 02:30:00-04:00,2024-08-15 08:00:00-04:00,2024-08-15 02:30:00-04:00,2024-08-15 02:45:00-04:00
2024-08-19 10:45:00-04:00,65.896303,0.005860,True,29.448349,55.845257,0.0,1.0,0.0,1.0,0.002687,0.002687,-0.001090,-0.001758,-0.000280,-0.000280,2024-08-19 11:00:00-04:00,2024-08-19 16:45:00-04:00,2024-08-19 11:00:00-04:00,2024-08-19 16:45:00-04:00
2024-08-20 02:45:00-04:00,62.537973,0.002825,NaN,9.636444,36.447413,0.0,1.0,0.0,1.0,0.002698,0.002698,-0.000800,-0.001766,-0.000800,-0.001766,2024-08-20 03:00:00-04:00,2024-08-20 04:00:00-04:00,2024-08-20 03:00:00-04:00,2024-08-20 03:45:00-04:00
2024-08-20 20:30:00-04:00,55.962898,0.000910,NaN,5.148685,3.516880,0.0,1.0,0.0,1.0,0.002737,0.002737,-0.000345,-0.001791,-0.000345,-0.001791,2024-08-20 20:45:00-04:00,2024-08-21 10:00:00-04:00,2024-08-20 20:45:00-04:00,2024-08-21 06:30:00-04:00
2024-08-22 03:15:00-04:00,59.855362,0.002640,NaN,5.207882,22.314064,0.0,1.0,0.0,1.0,0.002792,0.002792,-0.001170,-0.001827,-0.001170,-0.001827,2024-08-22 03:30:00-04:00,2024-08-22 04:30:00-04:00,2024-08-22 03:30:00-04:00,2024-08-22 04:30:00-04:00
2024-08-22 04:45:00-04:00,65.818390,0.004745,NaN,30.787895,54.137151,0.0,1.0,1.0,0.0,0.002792,0.002792,-0.001495,-0.001827,-0.001495,0.002792,2024-08-22 05:00:00-04:00,2024-08-22 16:45:00-04:00,2024-08-22 05:00:00-04:00,2024-08-22 09:15:00-04:00
2024-08-23 01:30:00-04:00,63.944064,0.002515,NaN,24.746748,16.150135,0.0,1.0,0.0,1.0,0.002731,0.002731,-0.000205,-0.001788,-0.000205,-0.001788,2024-08-23 01:45:00-04:00,2024-08-23 04:45:00-04:00,2024-08-23 01:45:00-04:00,2024-08-23 01:45:00-04:00
2024-08-27 01:15:00-04:00,56.171500,0.002190,NaN,13.331967,23.328121,0.0,1.0,0.0,1.0,0.002812,0.002812,-0.000650,-0.001840,-0.000650,-0.001840,2024-08-27 01:30:00-04:00,2024-08-27 03:00:00-04:00,2024-08-27 01:30:00-04:00,2024-08-27 02:15:00-04:00
2024-08-27 03:15:00-04:00,60.008352,0.003560,NaN,19.183638,38.550465,0.0,1.0,0.0,1.0,0.002812,0.002812,-0.001050,-0.001840,-0.001050,-0.001840,2024-08-27 03:30:00-04:00,2024-08-27 05:00:00-04:00,2024-08-27 03:30:00-04:00,2024-08-27 04:15:00-04:00
2024-08-29 02:15:00-04:00,70.244796,0.003735,NaN,32.112553,42.445517,0.0,1.0,1.0,0.0,0.002890,0.002890,-0.000550,-0.001891,-0.000550,0.002890,2024-08-29 02:30:00-04:00,2024-08-29 16:45:00-04:00,2024-08-29 02:30:00-04:00,2024-08-29 03:15:00-04:00
2024-08-30 02:15:00-04:00,61.287196,0.001655,NaN,9.694444,23.779489,0.0,1.0,0.0,1.0,0.002902,0.002902,-0.000325,-0.001899,-0.000325,-0.001899,2024-08-30 02:30:00-04:00,2024-08-30 03:30:00-04:00,2024-08-30 02:30:00-04:00,2024-08-30 02:45:00-04:00
2024-08-30 03:45:00-04:00,70.368821,0.003800,True,30.033280,50.822012,0.0,1.0,1.0,0.0,0.002902,0.002902,-0.000750,-0.001899,-0.000750,0.002902,2024-08-30 04:00:00-04:00,2024-08-30 16:45:00-04:00,2024-08-30 04:00:00-04:00,2024-08-30 04:00:00-04:00
2024-09-02 02:45:00-04:00,60.907006,0.002550,NaN,12.196616,32.475054,0.0,1.0,0.0,1.0,0.002954,0.002954,-0.000560,-0.001933,-0.000560,-0.000690,2024-09-02 03:00:00-04:00,2024-09-02 16:45:00-04:00,2024-09-02 03:00:00-04:00,2024-09-02 04:00:00-04:00
2024-09-04 21:45:00-04:00,55.602975,0.001535,NaN,18.488647,9.694444,0.0,1.0,0.0,1.0,0.002988,0.002988,-0.000715,-0.001956,-0.000715,-0.001956,2024-09-04 22:00:00-04:00,2024-09-05 04:15:00-04:00,2024-09-04 22:00:00-04:00,2024-09-05 02:15:00-04:00
2024-09-10 03:00:00-04:00,69.671794,0.004440,True,29.606502,52.431408,0.0,1.0,1.0,0.0,0.003086,0.003086,-0.000570,-0.002020,-0.000570,0.003086,2024-09-10 03:15:00-04:00,2024-09-10 16:45:00-04:00,2024-09-10 03:15:00-04:00,2024-09-10 03:15:00-04:00
2024-09-10 22:15:00-04:00,65.345627,0.002735,NaN,22.518081,30.211887,0.0,1.0,1.0,0.0,0.003101,0.003101,-0.000300,-0.002030,-0.000300,0.003101,2024-09-10 22:30:00-04:00,2024-09-11 16:45:00-04:00,2024-09-10 22:30:00-04:00,2024-09-11 00:15:00-04:00
2024-09-12 20:15:00-04:00,83.273902,0.002145,True,48.758556,39.699740,0.0,1.0,0.0,1.0,0.003133,0.003133,-0.000480,-0.002050,-0.000480,0.001545,2024-09-12 20:30:00-04:00,2024-09-13 16:45:00-04:00,2024-09-12 20:30:00-04:00,2024-09-12 20:45:00-04:00
2024-09-12 21:00:00-04:00,85.212601,0.002660,True,49.029430,39.664391,0.0,1.0,0.0,1.0,0.003133,0.003133,-0.000405,-0.002050,-0.000405,0.002135,2024-09-12 21:15:00-04:00,2024-09-13 16:45:00-04:00,2024-09-12 21:15:00-04:00,2024-09-12 23:30:00-04:00
2024-09-16 03:00:00-04:00,63.204965,0.004980,NaN,33.998844,38.805081,0.0,1.0,0.0,1.0,0.003019,0.003019,-0.000975,-0.001975,-0.000975,-0.001975,2024-09-16 03:15:00-04:00,2024-09-16 04:15:00-04:00,2024-09-16 03:15:00-04:00,2024-09-16 03:30:00-04:00
2024-09-17 02:15:00-04:00,56.788432,0.001890,NaN,3.011221,13.303709,0.0,1.0,1.0,0.0,0.003006,0.003006,-0.000400,-0.001967,-0.000400,0.003006,2024-09-17 02:30:00-04:00,2024-09-17 16:45:00-04:00,2024-09-17 02:30:00-04:00,2024-09-17 03:30:00-04:00
2024-09-18 02:15:00-04:00,56.517805,0.002230,NaN,14.764125,22.058201,0.0,1.0,0.0,1.0,0.002946,0.002946,-0.000875,-0.001928,-0.000875,-0.001928,2024-09-18 02:30:00-04:00,2024-09-18 03:00:00-04:00,2024-09-18 02:30:00-04:00,2024-09-18 02:30:00-04:00
2024-09-19 03:00:00-04:00,71.695471,0.010505,True,41.202822,67.830564,0.0,1.0,0.0,1.0,0.003057,0.003057,-0.000545,-0.002001,-0.000545,-0.002001,2024-09-19 03:15:00-04:00,2024-09-19 05:00:00-04:00,2024-09-19 03:15:00-04:00,2024-09-19 04:30:00-04:00
2024-09-24 19:15:00-04:00,67.650125,0.001135,NaN,34.080808,34.871676,0.0,1.0,1.0,0.0,0.003230,0.003230,-0.000320,-0.002114,-0.000320,0.003230,2024-09-24 19:30:00-04:00,2024-09-25 16:45:00-04:00,2024-09-24 19:30:00-04:00,2024-09-24 19:30:00-04:00
2024-09-26 05:30:00-04:00,66.614231,0.005440,NaN,37.022381,30.522893,0.0,1.0,0.0,1.0,0.003313,0.003313,-0.000625,-0.002169,-0.000625,-0.002169,2024-09-26 05:45:00-04:00,2024-09-26 07:00:00-04:00,2024-09-26 05:45:00-04:00,2024-09-26 06:15:00-04:00
2024-10-04 02:45:00-04:00,67.344755,0.003455,True,25.456395,39.487101,0.0,1.0,0.0,1.0,0.003558,0.003558,-0.000715,-0.002328,-0.000715,-0.002328,2024-10-04 03:00:00-04:00,2024-10-04 06:30:00-04:00,2024-10-04 03:00:00-04:00,2024-10-04 03:45:00-04:00
2024-10-10 03:45:00-04:00,61.582164,0.002620,NaN,19.396317,19.872812,0.0,1.0,1.0,0.0,0.003447,0.003447,-0.000585,-0.002256,-0.000585,0.003447,2024-10-10 04:00:00-04:00,2024-10-10 16:45:00-04:00,2024-10-10 04:00:00-04:00,2024-10-10 06:45:00-04:00
2024-10-10 21:15:00-04:00,57.405544,0.001215,NaN,36.620808,14.596576,0.0,1.0,0.0,1.0,0.003435,0.003435,-0.000275,-0.002248,-0.000275,-0.000370,2024-10-10 21:30:00-04:00,2024-10-11 16:45:00-04:00,2024-10-10 21:30:00-04:00,2024-10-11 03:45:00-04:00
2024-10-11 04:00:00-04:00,62.616443,0.003550,NaN,14.260712,37.098394,0.0,1.0,0.0,1.0,0.003435,0.003435,-0.000745,-0.002248,-0.000745,0.000215,2024-10-11 04:15:00-04:00,2024-10-11 16:45:00-04:00,2024-10-11 04:15:00-04:00,2024-10-11 04:15:00-04:00
2024-10-14 20:00:00-04:00,56.166044,0.001075,NaN,14.652454,23.829449,0.0,1.0,0.0,1.0,0.003381,0.003381,-0.000485,-0.002213,-0.000485,-0.002213,2024-10-14 20:15:00-04:00,2024-10-15 04:45:00-04:00,2024-10-14 20:15:00-04:00,2024-10-14 21:30:00-04:00
2024-10-17 18:15:00-04:00,58.662104,0.000720,NaN,20.686745,13.867603,0.0,1.0,0.0,1.0,0.003423,0.003423,-0.000120,-0.002240,-0.000120,-0.002240,2024-10-17 18:30:00-04:00,2024-10-18 02:00:00-04:00,2024-10-17 18:30:00-04:00,2024-10-17 19:45:00-04:00
2024-10-17 22:45:00-04:00,60.603965,0.001850,NaN,15.570274,21.336859,0.0,1.0,0.0,1.0,0.003423,0.003423,-0.000385,-0.002240,-0.000385,-0.002240,2024-10-17 23:00:00-04:00,2024-10-18 02:00:00-04:00,2024-10-17 23:00:00-04:00,2024-10-18 01:45:00-04:00
2024-10-24 02:15:00-04:00,55.927258,0.002565,NaN,22.390641,20.136303,0.0,1.0,0.0,1.0,0.003334,0.003334,-0.000475,-0.002182,-0.000475,-0.002182,2024-10-24 02:30:00-04:00,2024-10-24 03:00:00-04:00,2024-10-24 02:30:00-04:00,2024-10-24 02:30:00-04:00
2024-10-24 03:15:00-04:00,66.527596,0.005055,True,41.672413,48.939464,0.0,1.0,0.0,1.0,0.003334,0.003334,-0.000970,-0.002182,-0.000970,-0.002182,2024-10-24 03:30:00-04:00,2024-10-24 04:00:00-04:00,2024-10-24 03:30:00-04:00,2024-10-24 03:30:00-04:00
2024-10-24 03:45:00-04:00,68.718055,0.005950,NaN,46.721684,58.571910,0.0,1.0,0.0,1.0,0.003334,0.003334,-0.000665,-0.002182,-0.000665,-0.002182,2024-10-24 04:00:00-04:00,2024-10-24 10:00:00-04:00,2024-10-24 04:00:00-04:00,2024-10-24 04:00:00-04:00
2024-10-28 03:30:00-04:00,61.847399,0.002975,NaN,6.212424,35.902972,0.0,1.0,0.0,1.0,0.003312,0.003312,-0.000385,-0.002168,-0.000385,-0.002168,2024-10-28 03:45:00-04:00,2024-10-28 07:00:00-04:00,2024-10-28 03:45:00-04:00,2024-10-28 03:45:00-04:00
2024-10-29 04:45:00-04:00,68.278296,0.003175,NaN,15.348504,45.619868,0.0,1.0,0.0,1.0,0.003268,0.003268,-0.000555,-0.002139,-0.000555,-0.002139,2024-10-29 05:00:00-04:00,2024-10-29 11:45:00-04:00,2024-10-29 05:00:00-04:00,2024-10-29 07:00:00-04:00
2024-10-29 21:30:00-04:00,61.420222,0.001260,NaN,15.874427,19.396317,0.0,1.0,1.0,0.0,0.003236,0.003236,-0.000200,-0.002118,-0.000200,0.003236,2024-10-29 21:45:00-04:00,2024-10-30 10:15:00-04:00,2024-10-29 21:45:00-04:00,2024-10-30 04:00:00-04:00
2024-10-31 03:00:00-04:00,58.688609,0.003490,NaN,13.020767,44.152133,0.0,1.0,0.0,1.0,0.003192,0.003192,-0.001230,-0.002089,-0.001230,-0.002089,2024-10-31 03:15:00-04:00,2024-10-31 03:30:00-04:00,2024-10-31 03:15:00-04:00,2024-10-31 03:30:00-04:00
2024-10-31 04:00:00-04:00,66.863915,0.005640,NaN,35.032056,59.823464,0.0,1.0,1.0,0.0,0.003192,0.003192,-0.001150,-0.002089,-0.001150,0.003192,2024-10-31 04:15:00-04:00,2024-10-31 16:45:00-04:00,2024-10-31 04:15:00-04:00,2024-10-31 06:15:00-04:00
2024-11-07 08:15:00-05:00,66.031480,0.009995,NaN,41.855043,64.280539,0.0,1.0,0.0,1.0,0.003292,0.003292,-0.001355,-0.002155,-0.001355,-0.002155,2024-11-07 08:30:00-05:00,2024-11-07 09:30:00-05:00,2024-11-07 08:30:00-05:00,2024-11-07 09:15:00-05:00
2024-11-18 12:00:00-05:00,66.830959,0.005580,True,38.238846,54.075607,0.0,1.0,0.0,1.0,0.003261,0.003261,-0.000920,-0.002134,-0.000920,-0.002134,2024-11-18 12:15:00-05:00,2024-11-18 13:45:00-05:00,2024-11-18 12:15:00-05:00,2024-11-18 12:30:00-05:00
2024-11-18 22:30:00-05:00,62.027028,0.002345,NaN,8.559948,17.299635,0.0,1.0,1.0,0.0,0.003263,0.003263,-0.000580,-0.002135,-0.000580,0.003263,2024-11-18 22:45:00-05:00,2024-11-19 16:45:00-05:00,2024-11-18 22:45:00-05:00,2024-11-18 23:00:00-05:00

In [2043]:
df.loc["2024-12-06 08:45:00-05:00"]

Open                 1.280485
High                  1.28064
Low                  1.278535
Close                 1.27948
Idx                     18302
Body                 0.001005
Range                0.002105
UWick                0.000155
LWick                0.000945
Close_%High          0.551069
Open_%High           0.073634
Iday_Idx                   62
Iday_High            1.281145
Iday_Low             1.273985
Iday_Range            0.00716
Close_%DHigh         0.232542
Open_%DHigh          0.092179
Yday_High             1.27708
Yday_Low             1.269315
Day_Idx                   192
ADR                  0.009483
ATR                  0.001106
SMA4                 1.278546
SMA16                1.276926
SMA32                1.276297
BB_Upper_16_2        1.279555
BB_Lower_16_2        1.274297
Close_%SMA           0.199992
RSI                 69.540125
RSI_DVG                   NaN
Sig_High             1.277425
Sig_Low              1.273985
SMA_Trend                   2
SMA4_Slope          78.763056
SMA16_Slope         58.523161
SMA32_Slope          49.20839
Hammer                    NaN
Shooting_Star             NaN
Bull_Engulf               NaN
Bear_Engulf               NaN
Dark_Cloud                NaN
Piercing                  NaN
ILR                       NaN
IHR                       NaN
S_R                       NaN
BBU_BO                    NaN
BBL_BO                    NaN
Bull_BBR                  NaN
Bear_BBR                  NaN
High_Win                  0.0
High_Loss                 0.0
ATR_Win                   0.0
ATR_Loss                  0.0
High_TP                   0.0
ATR_TP                    0.0
High_SL                   0.0
ATR_SL                    0.0
High_Gain                 0.0
ATR_Gain                  0.0
High_Trade_Start          NaT
High_Trade_End            NaT
Name: 2024-12-06 08:45:00-05:00, dtype: object