In [67]:
import pandas as pd 
import os
import datetime

PATH = os.getcwd()
FILE = "../output/FE_GBPUSD_15mins_1yr_End_20260311.csv"
df = pd.read_csv(FILE)
df["Date"] = pd.DatetimeIndex(df["Date"], tz="US/Eastern")
df.set_index("Date", inplace=True)
df

,Open,High,Low,Close,Idx,Body,Range,UWick,LWick,Close_%High,Open_%High,Iday_Idx,Iday_High,Iday_Low,Iday_Range,Close_%DHigh,Open_%DHigh,...,Sig_Low,SMA_Trend,SMA16_Slope,SMA32_Slope,Hammer,Shooting_Star,Bull_Engulf,Bear_Engulf,Dark_Cloud,Piercing,Bull_BBR,Bear_BBR,ILR,IHR,S/R,BBU_BO,BBL_BO
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2025-03-11 17:15:00-04:00,1.295630,1.295685,1.295180,1.295335,0,0.000295,0.000505,0.000055,0.000155,0.693069,0.108911,0,1.295685,1.295180,0.000505,0.693069,0.108911,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-11 17:30:00-04:00,1.295335,1.295360,1.294550,1.294780,1,0.000555,0.000810,0.000025,0.000230,0.716049,0.030864,1,1.295685,1.294550,0.001135,0.797357,0.308370,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-11 17:45:00-04:00,1.294780,1.294800,1.294590,1.294655,2,0.000125,0.000210,0.000020,0.000065,0.690476,0.095238,2,1.295685,1.294550,0.001135,0.907489,0.797357,...,NaN,0,-87.042245,-84.097964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-11 18:00:00-04:00,1.294655,1.295075,1.294470,1.294995,3,0.000340,0.000605,0.000080,0.000185,0.132231,0.694215,3,1.295685,1.294470,0.001215,0.567901,0.847737,...,NaN,0,-87.014011,-84.089748,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-11 18:15:00-04:00,1.294995,1.295000,1.294595,1.294665,4,0.000330,0.000405,0.000005,0.000070,0.827160,0.012346,4,1.295685,1.294470,0.001215,0.839506,0.567901,...,NaN,-2,-87.017085,-84.255226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-11 15:45:00-04:00,1.341870,1.342230,1.341675,1.341855,24575,0.000015,0.000555,0.000360,0.000180,0.675676,0.648649,90,1.345760,1.339345,0.006415,0.608730,0.606391,...,1.339345,1,38.477385,-13.473158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-11 16:00:00-04:00,1.341855,1.341855,1.341475,1.341765,24576,0.000090,0.000380,0.000000,0.000290,0.236842,0.000000,91,1.345760,1.339345,0.006415,0.622759,0.608730,...,1.339345,1,31.007621,-10.331105,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-11 16:15:00-04:00,1.341765,1.341770,1.341560,1.341580,24577,0.000185,0.000210,0.000005,0.000020,0.904762,0.023810,92,1.345760,1.339345,0.006415,0.651598,0.622759,...,1.339345,2,22.568992,-12.992437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-11 16:30:00-04:00,1.341580,1.341665,1.341260,1.341265,24578,0.000315,0.000405,0.000085,0.000005,0.987654,0.209877,93,1.345760,1.339345,0.006415,0.700701,0.651598,...,1.339345,2,20.241452,-9.229886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-11 16:45:00-04:00,1.341265,1.341340,1.341000,1.341185,24579,0.000080,0.000340,0.000075,0.000185,0.455882,0.220588,94,1.345760,1.339345,0.006415,0.713172,0.700701,...,1.339345,2,8.589126,6.624982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Get al columns

In [68]:
df.columns

Index(['Open', 'High', 'Low', 'Close', 'Idx', 'Body', 'Range', 'UWick',
       'LWick', 'Close_%High', 'Open_%High', 'Iday_Idx', 'Iday_High',
       'Iday_Low', 'Iday_Range', 'Close_%DHigh', 'Open_%DHigh', 'Yday_High',
       'Yday_Low', 'Day_Idx', 'ADR', 'ATR', 'SMA4', 'SMA16', 'SMA32',
       'BB_Upper_16_2', 'BB_Lower_16_2', 'RSI', 'Sig_High', 'Sig_Low',
       'SMA_Trend', 'SMA16_Slope', 'SMA32_Slope', 'Hammer', 'Shooting_Star',
       'Bull_Engulf', 'Bear_Engulf', 'Dark_Cloud', 'Piercing', 'Bull_BBR',
       'Bear_BBR', 'ILR', 'IHR', 'S/R', 'BBU_BO', 'BBL_BO'],
      dtype='object')

Get all rows that have `Bear_BBR` as True

In [161]:
pd.options.display.max_rows = 50
cols = ['Day_Idx', 'Open', 'High', 'Low', 'Close', 'Body', 'Range', 'ATR',
        'Close_%High', 'Open_%High', 'Iday_High', 'Iday_Low', 
        'Iday_Range', 'ADR', 'Close_%DHigh', 'Open_%DHigh', 
        'Yday_High', 'Yday_Low', 'SMA4', 'SMA16', 'SMA32',
       'BB_Upper_16_2', 'BB_Lower_16_2', 'RSI', 'Sig_High', 'Sig_Low',
       'SMA_Trend', 'SMA16_Slope', 'SMA32_Slope', 'Bear_BBR', 'Shooting_Star',
       'Bear_Engulf', 'Dark_Cloud', 'IHR', 'S/R', 'BBU_BO']
pd.options.display.max_columns = len(cols)
bbu_reversal = df[cols]#.query("Bear_BBR == True")
bbu_reversal

,Day_Idx,Open,High,Low,Close,Body,Range,ATR,Close_%High,Open_%High,Iday_High,Iday_Low,Iday_Range,ADR,Close_%DHigh,Open_%DHigh,Yday_High,Yday_Low,SMA4,SMA16,SMA32,BB_Upper_16_2,BB_Lower_16_2,RSI,Sig_High,Sig_Low,SMA_Trend,SMA16_Slope,SMA32_Slope,Bear_BBR,Shooting_Star,Bear_Engulf,Dark_Cloud,IHR,S/R,BBU_BO
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2025-03-11 17:15:00-04:00,0,1.295630,1.295685,1.295180,1.295335,0.000295,0.000505,NaN,0.693069,0.108911,1.295685,1.295180,0.000505,NaN,0.693069,0.108911,NaN,NaN,NaN,1.338512,1.339928,1.338512,1.338512,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-11 17:30:00-04:00,0,1.295335,1.295360,1.294550,1.294780,0.000555,0.000810,NaN,0.716049,0.030864,1.295685,1.294550,0.001135,NaN,0.797357,0.308370,NaN,NaN,NaN,1.335580,1.338460,1.335580,1.335580,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-11 17:45:00-04:00,0,1.294780,1.294800,1.294590,1.294655,0.000125,0.000210,NaN,0.690476,0.095238,1.295685,1.294550,0.001135,NaN,0.907489,0.797357,NaN,NaN,NaN,1.332706,1.337026,1.332706,1.332706,NaN,NaN,NaN,0,-87.042245,-84.097964,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-11 18:00:00-04:00,0,1.294655,1.295075,1.294470,1.294995,0.000340,0.000605,NaN,0.132231,0.694215,1.295685,1.294470,0.001215,NaN,0.567901,0.847737,NaN,NaN,NaN,1.329829,1.335562,1.329829,1.329829,NaN,NaN,NaN,0,-87.014011,-84.089748,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-11 18:15:00-04:00,0,1.294995,1.295000,1.294595,1.294665,0.000330,0.000405,NaN,0.827160,0.012346,1.295685,1.294470,0.001215,NaN,0.839506,0.567901,NaN,NaN,1.294774,1.326948,1.334044,1.326948,1.326948,NaN,NaN,NaN,-2,-87.017085,-84.255226,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-11 15:45:00-04:00,255,1.341870,1.342230,1.341675,1.341855,0.000015,0.000555,0.000814,0.675676,0.648649,1.345760,1.339345,0.006415,0.009747,0.608730,0.606391,1.34834,1.341225,1.341610,1.341201,1.341394,1.342075,1.340328,51.591073,1.34576,1.339345,1,38.477385,-13.473158,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-11 16:00:00-04:00,255,1.341855,1.341855,1.341475,1.341765,0.000090,0.000380,0.000798,0.236842,0.000000,1.345760,1.339345,0.006415,0.009747,0.622759,0.608730,1.34834,1.341225,1.341737,1.341251,1.341368,1.342156,1.340346,50.971669,1.34576,1.339345,1,31.007621,-10.331105,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-11 16:15:00-04:00,255,1.341765,1.341770,1.341560,1.341580,0.000185,0.000210,0.000720,0.904762,0.023810,1.345760,1.339345,0.006415,0.009747,0.651598,0.622759,1.34834,1.341225,1.341768,1.341326,1.341324,1.342123,1.340529,49.664290,1.34576,1.339345,2,22.568992,-12.992437,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-11 16:30:00-04:00,255,1.341580,1.341665,1.341260,1.341265,0.000315,0.000405,0.000594,0.987654,0.209877,1.345760,1.339345,0.006415,0.009747,0.700701,0.651598,1.34834,1.341225,1.341616,1.341362,1.341320,1.342090,1.340634,47.453690,1.34576,1.339345,2,20.241452,-9.229886,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-11 16:45:00-04:00,255,1.341265,1.341340,1.341000,1.341185,0.000080,0.000340,0.000550,0.455882,0.220588,1.345760,1.339345,0.006415,0.009747,0.713172,0.700701,1.34834,1.341225,1.341449,1.341371,1.341359,1.342086,1.340656,46.888313,1.34576,1.339345,2,8.589126,6.624982,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- Create new signal dataframe
- index is the signal id e.g. 0,1,2...
- columns = 
    - datetime of signal
    - max price up from start of signal until end of day
    - max price down from signal until start of day
    - lowest low from signal until EOD
    - lowest close from signal until EOD
    - highest high from signal until EOD
    - highest close from signal until EOD
    - Close at EOD

In [237]:
signal = []
row = bbu_reversal.iloc[47]
s = {}
START = row.name
s["Date"] = START
s["Entry_Price"] = row["Close"]
day = row["Day_Idx"]
window = bbu_reversal.query(f"Day_Idx == {day}")
signal_window = window[START:]
s["Max_High"] = signal_window["High"].max() # Max high from signal until EOD
s["Min_Low"] = signal_window["Low"].min() # Min low from signal until EOD
s["Max_Up"] = s["Entry_Price"] - s["Max_High"] # Max price gain from signal until EOD
s["Max_Down"] = s["Entry_Price"] - s["Min_Low"] # Max price loss from signal until EOD
s["EOD_Close"] = signal_window.iloc[-1]["Close"] # Closing price at EOD
s["EOD_Gain"] = s["Entry_Price"] - s["EOD_Close"] # Gain at EOD from signal price


if signal_window.query(f"Close > {row["High"]}").empty is False:
    # If price closed above signal price within the day, 
    # get the dataframe between start and failure time
    EXIT = signal_window[START:].query(f"Close > {row["High"]}").iloc[0].name
    entry_window = signal_window[START:EXIT]
else:
    # If price didn't close above signal price within the day
    # get the dataframe from signal time until EOD
    EXIT = signal_window[START:].query(f"Close > {row["High"]}").iloc[0].name
    entry_window = signal_window

# If the price fell to the SMA16 after the signal
# calcuate the gain
below_sma16 = entry_window.query("Low < SMA16")
if below_sma16.empty is False:
    s["To_SMA16"] = s["Entry_Price"] - below_sma16.iloc[0]["SMA16"] 
else: 
    s["To_SMA16"] = 0

# If the price fell to the SMA32 after the signal
# calcuate the gain
below_sma32 = entry_window.query("Low < SMA32")
if below_sma32.empty is False:
    s["To_SMA32"] = s["Entry_Price"] - below_sma32.iloc[0]["SMA32"]
else:
    s["To_SMA32"] = 0

# If the price fell to the BB_Lower_16_2 after the signal
# calcuate the gain
below_bbl = entry_window.query("Low < BB_Lower_16_2")
if below_bbl.empty is False:
    s["To_BBL"] = s["Entry_Price"] - below_bbl.iloc[0]["BB_Lower_16_2"]
else:
    s["To_BBL"] = 0

s

{'Date': Timestamp('2025-03-12 05:00:00-0400', tz='US/Eastern'),
 'Entry_Price': np.float64(1.293895),
 'Max_High': np.float64(1.299),
 'Min_Low': np.float64(1.29246),
 'Max_Up': np.float64(-0.005104999999999915),
 'Max_Down': np.float64(0.001435000000000075),
 'EOD_Close': np.float64(1.29633),
 'EOD_Signal_Gain': np.float64(-0.002434999999999965),
 'To_SMA16': np.float64(0.0006021874999999621),
 'To_SMA32': np.float64(0.0009062500000001084),
 'To_BBL': 0}