In [1]:
import pandas as pd 
import numpy as np
import os
from pandas import DataFrame, Series
import plotly.graph_objects as go

In [118]:
def get_fe_price_data(
        filename: str = "FE_V2_GBPUSD_15mins_1yr_End_20250311.csv"
        ) -> DataFrame:
    """
    Return the FE price data as a DatetimeIndexed 
    DataFrame set to US/Eastern TZ
    """
    FOLDER = "price_data"
    PATH = f"{os.getcwd()}/{FOLDER}"
    df = pd.read_csv(f"{PATH}/{filename}")
    df["Date"] = pd.DatetimeIndex(df["Date"], tz="US/Eastern")
    df.set_index("Date", inplace=True)
    return df

In [119]:
fn = "FE_GBPUSD_15mins_1yr_End_20260311.csv"
data = get_fe_price_data(filename=fn)

/var/folders/zj/znqgk8kn6rqg7hbspq68r8_h0000gp/T/ipykernel_87870/1547086338.py:10: DtypeWarning: Columns (59,60,61,62,63,64,65,66,71,72,73,74,75,76,78,79,80,81,89,95,96,97) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f"{PATH}/{filename}")

In [430]:
base_cols = [
        "Iday_Idx", "Iday_Range","Yday_Range", "ADR", "Range", "ATR4", "Body", "RSI_DVG", "RSI", 
        "SMA4_Slope_SMA", "SMA16_Slope_SMA", "SMA32_Slope_SMA","Close_Pct_SMA", "Daily_IB", "IHR", "ILR"]

In [431]:
class TradingRange():
    """Define a daily trading range"""
    def __init__(self) -> None:
        self.range_high = None 
        self.range_low = None
        self.range_open = None 
        self.range_close = None
        self.range_hclose = None
        self.range_lclose = None

    def daily_inside_bar(
            self, 
            df: Series, 
            yday_high: Series, 
            yday_low: Series,
            yday_open: Series,
            yday_close: Series,
            yday_hclose: Series,
            yday_lclose: Series
            ):
        """Return index of daily trading range"""
        inside_day = False
        idx = int(df["Idx"])
        if df["Day_Idx"] > 0 and df["Iday_Idx"] == 0:
            yday_open_close_max = max([df["Yday_Close"],df["Yday_Open"]])
            yday_open_close_min = min([df["Yday_Close"],df["Yday_Open"]])
            if self.range_high is None and self.range_low is None:
                self.range_high = yday_high.iloc[idx-1]
                self.range_low = yday_low.iloc[idx-1]
                self.range_open = yday_open.iloc[idx-1]
                self.range_close = yday_close.iloc[idx-1]
                self.range_hclose = yday_hclose.iloc[idx-1]
                self.range_lclose = yday_lclose.iloc[idx-1]
            if self.range_high is not None and self.range_low is not None\
                and yday_open_close_max < self.range_high and yday_open_close_min > self.range_low:
                pass
            else:
                self.range_high = None 
                self.range_low = None
        if self.range_high is not None and self.range_low is not None:
            inside_day = True

        return inside_day

In [432]:
tr = TradingRange()
d_range_cols = ["Daily_IB", "MB_High","MB_Low","MB_Open","MB_Close","MB_HClose","MB_LClose"]
data["Daily_IB"] = data.apply(tr.daily_inside_bar, axis=1, args=[data["Yday_High"], data["Yday_Low"]])

In [402]:
data[base_cols].at_time("17:15").query("Daily_IB == True")

,Iday_Idx,Iday_Range,Yday_Range,ADR,Range,ATR4,Body,RSI_DVG,RSI,SMA4_Slope_SMA,SMA16_Slope_SMA,SMA32_Slope_SMA,Close_Pct_SMA,Daily_IB
Date,,,,,,,,,,,,,,
2025-03-13 17:15:00-04:00,0,0.000405,0.005250,NaN,0.000405,0.000524,0.000155,NaN,53.699461,17.557484,6.961392,-0.373162,0.033573,True
2025-03-16 17:15:00-04:00,0,0.000725,0.004795,NaN,0.000725,0.000504,0.000205,NaN,48.356022,4.474393,5.953221,-6.265584,0.009497,True
2025-03-19 17:15:00-04:00,0,0.000880,0.005595,NaN,0.000880,0.000570,0.000320,NaN,59.331009,45.025605,37.014209,20.439340,0.074067,True
2025-03-20 17:15:00-04:00,0,0.000965,0.007875,NaN,0.000965,0.000486,0.000355,NaN,55.472742,20.188959,4.182293,11.136652,0.042548,True
2025-03-24 17:15:00-04:00,0,0.000320,0.008090,NaN,0.000320,0.000349,0.000290,NaN,48.085950,8.422697,-4.475309,-35.418566,0.010692,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-04 17:15:00-05:00,0,0.000340,0.010000,0.010048,0.000340,0.000484,0.000035,NaN,54.364148,-20.130700,5.708960,-8.669633,0.043949,True
2026-03-05 17:15:00-05:00,0,0.001250,0.008960,0.009633,0.001250,0.000700,0.001070,NaN,58.559745,12.354379,25.152410,-11.836124,0.089900,True
2026-03-08 17:15:00-04:00,0,0.000545,0.010475,0.009752,0.000545,0.001059,0.000280,NaN,38.809031,28.018922,25.110044,47.832370,0.304245,True
2026-03-09 17:15:00-04:00,0,0.000765,0.016405,0.010429,0.000765,0.001121,0.000020,NaN,69.964818,40.032065,43.584159,51.608306,0.218328,True
2026-03-10 17:15:00-04:00,0,0.000095,0.007115,0.010353,0.000095,0.000480,0.000050,NaN,35.961751,-20.330808,-35.316902,-17.330037,0.114553,True

In [436]:
data[base_cols].query("Daily_IB == True and (IHR == True or ILR == True)").tail(51)

,Iday_Idx,Iday_Range,Yday_Range,ADR,Range,ATR4,Body,RSI_DVG,RSI,SMA4_Slope_SMA,SMA16_Slope_SMA,SMA32_Slope_SMA,Close_Pct_SMA,Daily_IB,IHR,ILR
Date,,,,,,,,,,,,,,,,
2026-01-28 23:00:00-05:00,23,0.004275,0.010145,0.009370,0.000710,0.000796,0.000285,NaN,62.892973,67.811826,18.811785,37.481527,0.100788,True,True,NaN
2026-01-28 23:30:00-05:00,25,0.004295,0.010145,0.009370,0.000625,0.000835,0.000040,NaN,63.150414,62.555969,13.312548,36.921835,0.102547,True,True,NaN
2026-01-30 04:45:00-05:00,46,0.008955,0.010570,0.009640,0.001690,0.001391,0.000680,True,34.938121,-73.306389,3.889972,-37.643247,0.159298,True,NaN,True
2026-01-30 10:00:00-05:00,67,0.009500,0.010570,0.009640,0.002410,0.001700,0.001295,True,35.394083,-48.431186,11.987478,6.051567,0.231066,True,NaN,True
2026-01-30 10:30:00-05:00,69,0.009845,0.010570,0.009640,0.002360,0.001991,0.000425,True,41.328807,-58.855223,3.551020,1.548948,0.133752,True,NaN,True
2026-01-30 16:00:00-05:00,91,0.013555,0.010570,0.009640,0.000725,0.000814,0.000215,True,36.713653,-67.372913,-55.423783,-48.314981,0.098890,True,NaN,True
2026-02-02 00:45:00-05:00,30,0.004540,0.013555,0.010400,0.001190,0.000915,0.000350,NaN,40.439890,-45.738417,-6.194653,-14.659512,0.076625,True,NaN,True
2026-02-03 11:00:00-05:00,71,0.005605,0.009220,0.010476,0.000915,0.001274,0.000125,NaN,61.170092,75.701207,12.228462,-15.248416,0.158188,True,True,NaN
2026-02-03 12:15:00-05:00,76,0.005650,0.009220,0.010476,0.001120,0.000979,0.000330,NaN,58.725145,-4.195921,31.982807,-5.493139,0.093974,True,True,NaN
2026-02-04 09:00:00-05:00,63,0.004715,0.005650,0.010556,0.003145,0.001904,0.002000,NaN,37.564508,-39.755093,-15.838516,2.455206,0.122628,True,NaN,True
2026-02-04 10:00:00-05:00,67,0.005600,0.005650,0.010556,0.001785,0.001220,0.000490,NaN,39.916272,-70.778997,-18.309835,-4.946028,0.099951,True,NaN,True
2026-02-09 01:00:00-05:00,31,0.004080,0.011505,0.011529,0.001560,0.000657,0.000350,NaN,59.596504,60.252167,2.824453,-11.774965,0.077602,True,True,NaN
2026-02-09 03:30:00-05:00,41,0.004250,0.011505,0.011529,0.000940,0.001310,0.000245,NaN,43.687734,-32.855442,6.277341,-2.514345,0.088512,True,NaN,True
2026-02-09 13:45:00-05:00,82,0.010490,0.011505,0.011529,0.001200,0.000987,0.000895,True,67.798699,55.813855,48.466577,55.037422,0.123029,True,True,NaN
2026-02-10 21:00:00-05:00,15,0.001820,0.006055,0.010743,0.000545,0.000582,0.000180,NaN,50.809194,39.986180,-17.321688,-31.388126,0.049581,True,True,NaN
2026-02-11 08:30:00-05:00,61,0.010295,0.006055,0.010743,0.007645,0.002532,0.003935,NaN,32.439760,-47.428527,22.701592,31.176318,0.307759,True,NaN,True
2026-02-12 01:30:00-05:00,33,0.003760,0.010295,0.011013,0.001540,0.001032,0.000430,NaN,40.634340,-21.418223,-6.083097,-5.613331,0.051946,True,NaN,True
2026-02-12 03:15:00-05:00,40,0.004220,0.010295,0.011013,0.001285,0.000914,0.000190,NaN,57.348909,67.857074,-18.637551,-0.381280,0.090001,True,True,NaN
2026-02-12 09:00:00-05:00,63,0.005245,0.010295,0.011013,0.001525,0.001236,0.000310,NaN,56.022992,29.761039,15.466172,14.298323,0.042724,True,True,NaN
2026-02-13 03:45:00-05:00,42,0.003845,0.006685,0.009855,0.001040,0.000755,0.000350,NaN,60.786838,62.776939,-18.711790,-14.087252,0.110435,True,True,NaN
2026-02-13 04:45:00-05:00,46,0.003935,0.006685,0.009855,0.000735,0.000679,0.000445,NaN,57.220814,48.926386,-4.939222,-8.402434,0.074633,True,True,NaN
2026-02-13 08:30:00-05:00,61,0.005605,0.006685,0.009855,0.003420,0.001486,0.000555,NaN,55.676638,38.880387,2.548373,-3.287153,0.041691,True,True,NaN
2026-02-16 02:30:00-05:00,37,0.001610,0.006930,0.009587,0.001580,0.000763,0.000475,NaN,58.313309,18.343921,-4.288434,-7.840189,0.051383,True,True,NaN
2026-02-16 03:00:00-05:00,39,0.002495,0.006930,0.009587,0.001835,0.001211,0.000315,NaN,55.427800,10.396670,-1.667352,-7.309639,0.037431,True,True,NaN
2026-02-16 10:45:00-05:00,70,0.003435,0.006930,0.009587,0.000565,0.000499,0.000075,NaN,42.210825,-12.837709,-25.291629,-5.019358,0.029447,True,NaN,True
2026-02-16 11:15:00-05:00,72,0.003625,0.006930,0.009587,0.000655,0.000591,0.000140,NaN,40.320575,-16.349841,-30.096744,-7.976877,0.027778,True,NaN,True
2026-02-16 16:30:00-05:00,93,0.003685,0.006930,0.009587,0.000480,0.000231,0.000405,NaN,36.696119,-18.719380,-5.485259,-16.566949,0.030218,True,NaN,True
2026-02-23 01:15:00-05:00,32,0.005125,0.008025,0.009160,0.000535,0.000684,0.000300,NaN,64.575701,20.898568,1.267664,30.973725,0.100990,True,True,NaN
2026-02-23 01:45:00-05:00,34,0.005150,0.008025,0.009160,0.000600,0.000746,0.000005,NaN,61.121604,63.398940,-3.413035,31.478614,0.071908,True,True,NaN
2026-02-23 07:00:00-05:00,55,0.005240,0.008025,0.009160,0.000815,0.001165,0.000240,True,30.417533,-62.886588,-28.887741,-15.810574,0.131628,True,NaN,True
2026-02-23 22:00:00-05:00,19,0.002345,0.005930,0.008482,0.000370,0.000486,0.000080,NaN,53.205178,54.976890,2.132840,-8.994229,0.030570,True,True,NaN
2026-02-24 02:15:00-05:00,36,0.002790,0.005930,0.008482,0.000680,0.000750,0.000095,NaN,39.709693,-8.329809,-18.388562,-8.379921,0.045282,True,NaN,True
2026-02-24 02:45:00-05:00,38,0.002795,0.005930,0.008482,0.000820,0.000890,0.000245,NaN,40.108723,-53.793161,-20.009428,-10.478565,0.038473,True,NaN,True
2026-02-24 04:30:00-05:00,45,0.003265,0.005930,0.008482,0.000580,0.000766,0.000315,NaN,61.195195,58.694830,-6.970171,-8.411643,0.101236,True,True,NaN
2026-02-24 05:00:00-05:00,47,0.003270,0.005930,0.008482,0.000680,0.000671,0.000260,NaN,57.810477,62.667245,-2.753206,-5.994699,0.070458,True,True,NaN
2026-02-24 05:30:00-05:00,49,0.003610,0.005930,0.008482,0.000810,0.000676,0.000145,NaN,58.419525,42.124347,1.976709,-4.826433,0.071030,True,True,NaN
2026-02-25 06:30:00-05:00,53,0.004305,0.006650,0.008077,0.000730,0.000814,0.000305,NaN,36.625737,-59.291460,-13.573994,8.777651,0.126755,True,NaN,True
2026-02-25 08:15:00-05:00,60,0.004450,0.006650,0.008077,0.001090,0.000960,0.000515,NaN,57.268983,70.635098,-18.084957,-1.201542,0.090773,True,True,NaN
2026-02-25 10:45:00-05:00,70,0.004620,0.006650,0.008077,0.001670,0.001234,0.000725,NaN,60.198146,64.045062,13.470591,-1.236368,0.098462,True,True,NaN
2026-03-04 21:30:00-05:00,17,0.002810,0.010000,0.010048,0.000635,0.000756,0.000025,NaN,45.332738,-67.346428,9.522509,11.089241,0.059308,True,NaN,True
2026-03-05 11:00:00-05:00,71,0.008505,0.010000,0.010048,0.002110,0.001864,0.001310,True,36.450447,-71.656243,-5.684161,14.959931,0.256879,True,NaN,True
2026-03-06 08:30:00-05:00,61,0.007940,0.008960,0.009633,0.003775,0.002252,0.002110,NaN,62.297559,72.976772,-42.230430,-33.544770,0.313183,True,True,NaN
2026-03-06 11:00:00-05:00,71,0.008285,0.008960,0.009633,0.003560,0.002549,0.002070,NaN,59.348580,69.592806,14.134897,-18.011824,0.228265,True,True,NaN
2026-03-06 11:15:00-05:00,72,0.008695,0.008960,0.009633,0.001905,0.002279,0.001030,NaN,61.801953,68.588428,22.567368,-13.689750,0.272889,True,True,NaN
2026-03-06 16:45:00-05:00,94,0.010475,0.008960,0.009633,0.002560,0.001210,0.000770,NaN,58.693773,59.212874,31.620747,48.853129,0.066598,True,True,NaN
2026-03-09 05:30:00-04:00,49,0.008055,0.010475,0.009752,0.002935,0.001984,0.000370,NaN,57.855666,-1.323783,43.221083,15.441641,0.113466,True,True,NaN
2026-03-10 15:30:00-04:00,89,0.007115,0.016405,0.010429,0.001335,0.001150,0.000330,NaN,36.440646,-73.176567,0.678018,-12.528573,0.211421,True,NaN,True
2026-03-10 15:45:00-04:00,90,0.007115,0.016405,0.010429,0.000860,0.001091,0.000060,NaN,36.228130,-68.083686,-5.286344,-13.850778,0.197723,True,NaN,True
2026-03-11 04:45:00-04:00,46,0.004755,0.007115,0.010353,0.001700,0.001410,0.001290,True,40.974606,-62.971673,-4.976767,22.567943,0.106135,True,NaN,True
2026-03-11 05:00:00-04:00,47,0.005555,0.007115,0.010353,0.002560,0.001751,0.000320,True,39.121945,-61.673132,-10.643478,19.715520,0.116264,True,NaN,True
2026-03-11 11:45:00-04:00,74,0.006415,0.007115,0.010353,0.001335,0.001118,0.000370,True,38.155498,-66.697679,-24.127965,-32.816445,0.135358,True,NaN,True