# Bull BBR Reversal - Stats

## Import Libs

In [2]:
import pandas as pd 
import numpy as np
import os
from pandas import DataFrame, Series
import plotly.graph_objects as go

## Get Price Data

In [597]:
PATH = os.getcwd()
FILE = "../output/FE_V2_GBPUSD_15mins_1yr_End_20260311.csv"
df = pd.read_csv(FILE)
df["Date"] = pd.DatetimeIndex(df["Date"], tz="US/Eastern")
df.set_index("Date", inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 24580 entries, 2025-03-11 17:15:00-04:00 to 2026-03-11 16:45:00-04:00
Data columns (total 49 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Open           24580 non-null  float64
 1   High           24580 non-null  float64
 2   Low            24580 non-null  float64
 3   Close          24580 non-null  float64
 4   Idx            24580 non-null  int64
 5   Body           24580 non-null  float64
 6   Range          24580 non-null  float64
 7   UWick          24580 non-null  float64
 8   LWick          24580 non-null  float64
 9   Close_%High    24580 non-null  float64
 10  Open_%High     24580 non-null  float64
 11  Iday_Idx       24580 non-null  int64
 12  Iday_High      24580 non-null  float64
 13  Iday_Low       24580 non-null  float64
 14  Iday_Range     24580 non-null  float64
 15  Close_%DHigh   24580 non-null  float64
 16  Open_%DHigh    24580 non-null  float64
 17  Yday_High      24485 non-null  float64
 18  Yday_Low       24485 non-null  float64
 19  Day_Idx        24580 non-null  int64
 20  ADR            21646 non-null  float64
 21  ATR            24568 non-null  float64
 22  SMA4           24576 non-null  float64
 23  SMA16          24580 non-null  float64
 24  SMA32          24580 non-null  float64
 25  BB_Upper_16_2  24580 non-null  float64
 26  BB_Lower_16_2  24580 non-null  float64
 27  Close_%SMA     24580 non-null  float64
 28  RSI            24564 non-null  float64
 29  RSI_DVG        1233 non-null   object
 30  Sig_High       20360 non-null  float64
 31  Sig_Low        20726 non-null  float64
 32  SMA_Trend      24580 non-null  int64
 33  SMA4_Slope     24574 non-null  float64
 34  SMA16_Slope    24578 non-null  float64
 35  SMA32_Slope    24578 non-null  float64
 36  Hammer         957 non-null    object
 37  Shooting_Star  927 non-null    object
 38  Bull_Engulf    520 non-null    object
 39  Bear_Engulf    506 non-null    object
 40  Dark_Cloud     192 non-null    object
 41  Piercing       213 non-null    object
 42  ILR            277 non-null    object
 43  IHR            305 non-null    object
 44  S_R            3168 non-null   float64
 45  BBU_BO         554 non-null    object
 46  BBL_BO         183 non-null    object
 47  Bull_BBR       416 non-null    object
 48  Bear_BBR       389 non-null    object
dtypes: float64(32), int64(4), object(13)
memory usage: 9.4+ MB

## Low vs ADR% Stop Loss - 38.2% ADR Target

In [598]:
def get_bull_bbr_pip_gain(
        df: Series, 
        high: Series, 
        low: Series,
        close: Series  
        ):
    """Get the pip gain and apply to df"""

    low_win = 0
    low_loss = 0
    adr_win = 0
    adr_loss = 0
    low_target_pips = 0 
    adr_target_pips = 0 
    low_sl_pips = 0
    adr_sl_pips = 0
    low_gain = 0
    adr_gain = 0
    low_trade_start =  None
    low_trade_end = None
    adr_trade_start =  None
    adr_trade_end = None
    
    if df["Bull_BBR"] is True:
        idx = int(df["Idx"])
        iday_idx = int(df["Iday_Idx"])
        # get signal start of fx day timestamp
        day_start_ts = low.iloc[idx-iday_idx:idx-iday_idx+1].index[0]
        OFFSET = day_start_ts + pd.DateOffset(days=1) # end of signal's fx day
        START = df.name # signal start time
        TD = pd.Timedelta(minutes=15)
        END = OFFSET - TD # 17:00 on the signals fx day

        # get stop loss time:
        sl_window = low.loc[START+TD:END] # from signal idx+1 to EOD
        close_window = close.loc[START+TD:END] # from signal idx+1 to EOD
        low_stop = False 
        low_sl_ts = None # get timestamp when stopped out
        adr_stop = False # update if stopped 
        adr_sl_ts = None # get timestamp when stopped out
        stoploss_low = max(low.iloc[idx-1], low.iloc[idx])

        for i in range(len(sl_window)):
            if sl_window.iloc[i] <= stoploss_low : #stoploss_high:
                low_stop = True # trade hit stop loss
                # get stop loss timestamp
                low_sl_ts = sl_window.iloc[i:i+1].index[0]
                break 
        for i in range(len(sl_window)): 
            if sl_window.iloc[i] <= (df["Close"] - df["ADR"] * 0.25 ): #(stoploss_high + df["ATR"]):
                adr_stop = True # trade hit stop loss
                # get stop loss timestamp
                adr_sl_ts = sl_window.iloc[i:i+1].index[0] 
                break
        # if not stopped out then the stop window is signal:EOD
        # don't include trade if it is the last candle of the day
        if low_stop is False:
            if close_window.empty is False:
                low_sl_ts = close_window.iloc[-1:].index[0]
            else:
                low_sl_ts = START+TD
        if adr_stop is False:
            if close_window.empty is False:
                adr_sl_ts = close_window.iloc[-1:].index[0]
            else:
                adr_sl_ts = START+TD

        # Take profit price
        tp = df["Close"] + (df["ADR"] * 0.382)

        # High trade window
        low_tp_window = high[START+TD:low_sl_ts+TD]
        low_trade_start = START+TD
        low_trade_end = low_sl_ts
        low_target_pips = tp - df["Close"]
        low_sl_pips = stoploss_low - df["Close"]
        if low_tp_window.max() >= tp:
            low_win = 1
            low_gain = low_target_pips
        else:
            low_loss = 1
            if low_stop is True:
                low_gain = low_sl_pips
            else:
                low_gain = close_window.iloc[-1] - df["Close"] if close_window.empty is False else 0           
        # ATR trade window
        adr_tp_window = high[START+TD:adr_sl_ts+TD]
        adr_trade_start = START+TD
        adr_trade_end = adr_sl_ts
        adr_target_pips = tp - df["Close"]
        adr_sl_pips = (df["Close"] - df["ADR"] * 0.25) - df["Close"] 
        if adr_tp_window.max() >= tp:
            adr_win = 1
            adr_gain = tp - df["Close"]
        else:
            adr_loss = 1
            if adr_stop is True:
                adr_gain = adr_sl_pips
            else:
                adr_gain = close_window.iloc[-1] - df["Close"] if close_window.empty is False else 0
    
    data = low_win, low_loss, \
        adr_win, adr_loss, \
        low_target_pips, adr_target_pips, \
        low_sl_pips, adr_sl_pips, \
        low_gain, adr_gain, \
        adr_trade_start, adr_trade_end, \
        low_trade_start, low_trade_end
    
    return data

# Set new columns 
pct_50_idr_cols = [
    "Low_Win", "Low_Loss", 
    "ADR_Win", "ADR_Loss", 
    "Low_TP", "ADR_TP", 
    "Low_SL", "ADR_SL", 
    "Low_Gain", "ADR_Gain",
    "ADR_Trade_Start", "ADR_Trade_End",
    "Low_Trade_Start", "Low_Trade_End"
    ]

df[pct_50_idr_cols] = df.apply(get_bull_bbr_pip_gain, axis=1, args=[df["High"], df["Low"], df["Close"]], result_type='expand')

In [599]:
df2 = df.query("Bull_BBR == True ").between_time("01:00", "16:00")

In [600]:
# Stats - High as SL
low_win_count = df2.query("Bull_BBR == True and Low_Win > 0")["Bull_BBR"].count()
low_loss_count = df2.query("Bull_BBR == True and Low_Loss > 0")["Bull_BBR"].count()
low_total_trades = low_win_count + low_loss_count
low_win_rate = low_win_count/low_total_trades * 100
low_win = df2.query("Bull_BBR == True and Low_Gain > 0")["Low_Gain"]
low_loss = df2.query("Bull_BBR == True and Low_Gain < 0")["Low_Gain"]
low_win_avg_pips = low_win.mean()
low_loss_avg_pips = low_loss.mean()
low_win_pips = low_win.sum()
low_loss_pips = low_loss.sum()
low_total_pips = low_win_pips + low_loss_pips

low_pct_50_idr = {
    "Win_Count": low_win_count,
    "Loss_Count": low_loss_count,
    "Total_Trades": low_total_trades,
    "Win_Rate": low_win_rate,
    "Avg_Win": low_win_avg_pips,
    "Avg_Loss": low_loss_avg_pips,
    "Win_Pips": low_win_pips,
    "Loss_Pips": low_loss_pips,
    "Total_Pips": low_total_pips
}

# Stats - High + ATR as SL
adr_win_count = df2.query("Bull_BBR == True and ADR_Win > 0")["Bull_BBR"].count()
adr_loss_count = df2.query("Bull_BBR == True and ADR_Loss > 0")["Bull_BBR"].count()
adr_total_trades = adr_win_count + adr_loss_count
adr_win_rate = adr_win_count/adr_total_trades * 100
adr_win = df2.query("Bull_BBR == True and ADR_Gain > 0")["ADR_Gain"]
adr_loss = df2.query("Bull_BBR == True and ADR_Gain < 0")["ADR_Gain"]
adr_win_avg_pips = adr_win.mean()
adr_loss_avg_pips = adr_loss.mean()
adr_win_pips = adr_win.sum()
adr_loss_pips = adr_loss.sum()
adr_total_pips = adr_win_pips + adr_loss_pips

adr_pct_50_idr = {
    "Win_Count": adr_win_count,
    "Loss_Count": adr_loss_count,
    "Total_Trades": adr_total_trades,
    "Win_Rate": adr_win_rate,
    "Avg_Win": adr_win_avg_pips,
    "Avg_Loss": adr_loss_avg_pips,
    "Win_Pips": adr_win_pips,
    "Loss_Pips": adr_loss_pips,
    "Total_Pips": adr_total_pips
}

pd.DataFrame([low_pct_50_idr, adr_pct_50_idr])

,Win_Count,Loss_Count,Total_Trades,Win_Rate,Avg_Win,Avg_Loss,Win_Pips,Loss_Pips,Total_Pips
0,44,239,283,15.547703,0.002665,-0.000741,0.162555,-0.164450,-0.001895
1,81,202,283,28.621908,0.002461,-0.001990,0.312508,-0.310438,0.002069

In [595]:
df2[["RSI", "Iday_Range", "RSI_DVG", "SMA32_Slope", "SMA16_Slope",*pct_50_idr_cols]].iloc[200:].query("ADR_Gain > 0")

,RSI,Iday_Range,RSI_DVG,SMA32_Slope,SMA16_Slope,Low_Win,Low_Loss,ADR_Win,ADR_Loss,Low_TP,ADR_TP,Low_SL,ADR_SL,Low_Gain,ADR_Gain,ADR_Trade_Start,ADR_Trade_End,Low_Trade_Start,Low_Trade_End
Date,,,,,,,,,,,,,,,,,,,
2024-11-25 03:45:00-05:00,35.774245,0.005865,NaN,-37.905960,-58.094924,1.0,0.0,1.0,0.0,0.003439,0.003439,-0.001190,-0.002251,0.003439,0.003439,2024-11-25 04:00:00-05:00,2024-11-25 16:45:00-05:00,2024-11-25 04:00:00-05:00,2024-11-25 10:45:00-05:00
2024-11-26 03:15:00-05:00,51.877864,0.006640,NaN,22.772258,-27.465035,1.0,0.0,1.0,0.0,0.003477,0.003477,-0.001050,-0.002276,0.003477,0.003477,2024-11-26 03:30:00-05:00,2024-11-26 13:30:00-05:00,2024-11-26 03:30:00-05:00,2024-11-26 11:45:00-05:00
2024-11-27 01:00:00-05:00,50.791761,0.001365,NaN,0.477454,-11.653841,1.0,0.0,1.0,0.0,0.003531,0.003531,-0.000295,-0.002311,0.003531,0.003531,2024-11-27 01:15:00-05:00,2024-11-27 16:45:00-05:00,2024-11-27 01:15:00-05:00,2024-11-27 16:45:00-05:00
2024-11-28 02:45:00-05:00,38.249735,0.003745,NaN,-29.809114,-31.138972,0.0,1.0,1.0,0.0,0.003566,0.003566,-0.000475,-0.002334,-0.000475,0.003566,2024-11-28 03:00:00-05:00,2024-11-28 16:45:00-05:00,2024-11-28 03:00:00-05:00,2024-11-28 03:00:00-05:00
2024-11-29 09:15:00-05:00,40.268276,0.007825,NaN,-35.291337,-31.182676,1.0,0.0,1.0,0.0,0.003561,0.003561,-0.000570,-0.002331,0.003561,0.003561,2024-11-29 09:30:00-05:00,2024-11-29 16:45:00-05:00,2024-11-29 09:30:00-05:00,2024-11-29 16:45:00-05:00
2024-12-03 07:30:00-05:00,39.793070,0.005855,NaN,7.447992,-57.328655,0.0,1.0,1.0,0.0,0.003629,0.003629,-0.000370,-0.002375,-0.000370,0.003629,2024-12-03 07:45:00-05:00,2024-12-03 16:45:00-05:00,2024-12-03 07:45:00-05:00,2024-12-03 07:45:00-05:00
2024-12-03 10:30:00-05:00,46.448184,0.006035,NaN,-20.188896,-36.408775,1.0,0.0,1.0,0.0,0.003629,0.003629,-0.001705,-0.002375,0.003629,0.003629,2024-12-03 10:45:00-05:00,2024-12-03 16:45:00-05:00,2024-12-03 10:45:00-05:00,2024-12-03 16:45:00-05:00
2024-12-09 07:45:00-05:00,49.215224,0.006650,NaN,38.440789,-17.787973,1.0,0.0,1.0,0.0,0.003683,0.003683,-0.000565,-0.002411,0.003683,0.003683,2024-12-09 08:00:00-05:00,2024-12-09 16:45:00-05:00,2024-12-09 08:00:00-05:00,2024-12-09 14:45:00-05:00
2024-12-11 14:00:00-05:00,44.583561,0.006855,NaN,17.354025,-44.028978,0.0,1.0,0.0,1.0,0.003702,0.003702,-0.000495,-0.002423,0.001155,0.001155,2024-12-11 14:15:00-05:00,2024-12-11 16:45:00-05:00,2024-12-11 14:15:00-05:00,2024-12-11 16:45:00-05:00
2024-12-13 02:30:00-05:00,25.391781,0.006040,True,-44.940255,-56.088286,0.0,1.0,1.0,0.0,0.003610,0.003610,-0.000200,-0.002363,-0.000200,0.003610,2024-12-13 02:45:00-05:00,2024-12-13 16:45:00-05:00,2024-12-13 02:45:00-05:00,2024-12-13 02:45:00-05:00
2024-12-17 15:45:00-05:00,49.123492,0.006295,NaN,1.163660,-18.273654,0.0,1.0,0.0,1.0,0.003608,0.003608,-0.000310,-0.002361,0.000145,0.000145,2024-12-17 16:00:00-05:00,2024-12-17 16:45:00-05:00,2024-12-17 16:00:00-05:00,2024-12-17 16:45:00-05:00
2024-12-26 09:45:00-05:00,30.853831,0.004645,True,-35.410448,-47.070031,0.0,1.0,0.0,1.0,0.003481,0.003481,-0.000170,-0.002278,-0.000170,0.002025,2024-12-26 10:00:00-05:00,2024-12-26 18:45:00-05:00,2024-12-26 10:00:00-05:00,2024-12-26 10:00:00-05:00
2024-12-27 04:45:00-05:00,34.285175,0.002940,NaN,-19.343199,-32.219472,1.0,0.0,1.0,0.0,0.003435,0.003435,-0.000230,-0.002248,0.003435,0.003435,2024-12-27 05:00:00-05:00,2024-12-27 16:45:00-05:00,2024-12-27 05:00:00-05:00,2024-12-27 16:45:00-05:00
2024-12-30 03:30:00-05:00,42.824876,0.002590,NaN,-11.453329,-22.721498,0.0,1.0,1.0,0.0,0.003432,0.003432,-0.000760,-0.002246,-0.000760,0.003432,2024-12-30 03:45:00-05:00,2024-12-30 09:00:00-05:00,2024-12-30 03:45:00-05:00,2024-12-30 03:45:00-05:00
2025-01-03 10:30:00-05:00,47.994793,0.004085,NaN,0.954841,-37.887377,1.0,0.0,1.0,0.0,0.003559,0.003559,-0.001020,-0.002329,0.003559,0.003559,2025-01-03 10:45:00-05:00,2025-01-03 16:45:00-05:00,2025-01-03 10:45:00-05:00,2025-01-03 16:45:00-05:00
2025-01-09 03:00:00-05:00,23.312107,0.012815,True,-62.631216,-72.110046,0.0,1.0,1.0,0.0,0.003712,0.003712,-0.001850,-0.002430,-0.001850,0.003712,2025-01-09 03:15:00-05:00,2025-01-09 16:45:00-05:00,2025-01-09 03:15:00-05:00,2025-01-09 05:30:00-05:00
2025-01-13 04:30:00-05:00,38.213413,0.010785,True,-59.853598,-47.563770,0.0,1.0,1.0,0.0,0.003739,0.003739,-0.001190,-0.002447,-0.001190,0.003739,2025-01-13 04:45:00-05:00,2025-01-13 16:45:00-05:00,2025-01-13 04:45:00-05:00,2025-01-13 04:45:00-05:00
2025-01-15 02:15:00-05:00,48.881215,0.005350,NaN,-19.608441,-18.273654,1.0,0.0,1.0,0.0,0.003868,0.003868,-0.002345,-0.002531,0.003868,0.003868,2025-01-15 02:30:00-05:00,2025-01-15 16:45:00-05:00,2025-01-15 02:30:00-05:00,2025-01-15 16:45:00-05:00
2025-01-16 04:45:00-05:00,37.129140,0.005840,NaN,-38.732519,-31.790290,0.0,1.0,1.0,0.0,0.003898,0.003898,-0.000505,-0.002551,-0.000505,0.003898,2025-01-16 05:00:00-05:00,2025-01-16 16:45:00-05:00,2025-01-16 05:00:00-05:00,2025-01-16 05:00:00-05:00
2025-01-16 07:45:00-05:00,41.221438,0.005840,NaN,-26.301844,-21.025512,0.0,1.0,1.0,0.0,0.003898,0.003898,-0.000505,-0.002551,-0.000505,0.003898,2025-01-16 08:00:00-05:00,2025-01-16 16:45:00-05:00,2025-01-16 08:00:00-05:00,2025-01-16 08:00:00-05:00
2025-01-16 08:30:00-05:00,40.485471,0.007310,NaN,-26.803286,-19.820008,0.0,1.0,1.0,0.0,0.003898,0.003898,-0.001255,-0.002551,-0.001255,0.003898,2025-01-16 08:45:00-05:00,2025-01-16 16:45:00-05:00,2025-01-16 08:45:00-05:00,2025-01-16 09:30:00-05:00
2025-01-17 02:45:00-05:00,26.739815,0.008380,NaN,-53.301304,-69.436594,1.0,0.0,1.0,0.0,0.003926,0.003926,-0.000805,-0.002569,0.003926,0.003926,2025-01-17 03:00:00-05:00,2025-01-17 16:45:00-05:00,2025-01-17 03:00:00-05:00,2025-01-17 09:15:00-05:00
2025-01-17 09:15:00-05:00,40.563902,0.008380,NaN,-37.551282,-52.739850,1.0,0.0,1.0,0.0,0.003926,0.003926,-0.000880,-0.002569,0.003926,0.003926,2025-01-17 09:30:00-05:00,2025-01-17 16:45:00-05:00,2025-01-17 09:30:00-05:00,2025-01-17 13:00:00-05:00
2025-01-20 04:15:00-05:00,38.348252,0.006165,NaN,0.208890,-47.454846,0.0,1.0,1.0,0.0,0.003916,0.003916,-0.000310,-0.002563,-0.000310,0.003916,2025-01-20 04:30:00-05:00,2025-01-20 16:45:00-05:00,2025-01-20 04:30:00-05:00,2025-01-20 04:30:00-05:00
2025-01-20 04:45:00-05:00,39.411607,0.006165,NaN,-17.408382,-58.144868,1.0,0.0,1.0,0.0,0.003916,0.003916,-0.001215,-0.002563,0.003916,0.003916,2025-01-20 05:00:00-05:00,2025-01-20 16:45:00-05:00,2025-01-20 05:00:00-05:00,2025-01-20 16:45:00-05:00
2025-01-22 02:15:00-05:00,38.428930,0.004290,NaN,-8.589126,-30.655576,1.0,0.0,1.0,0.0,0.004105,0.004105,-0.000595,-0.002686,0.004105,0.004105,2025-01-22 02:30:00-05:00,2025-01-22 16:45:00-05:00,2025-01-22 02:30:00-05:00,2025-01-22 10:45:00-05:00
2025-01-23 02:15:00-05:00,36.747329,0.002840,NaN,-8.384786,-21.181350,0.0,1.0,1.0,0.0,0.004088,0.004088,-0.000370,-0.002676,-0.000370,0.004088,2025-01-23 02:30:00-05:00,2025-01-23 16:45:00-05:00,2025-01-23 02:30:00-05:00,2025-01-23 02:30:00-05:00
2025-01-27 03:00:00-05:00,48.136935,0.004835,NaN,-19.449400,-33.978328,1.0,0.0,1.0,0.0,0.004233,0.004233,-0.001985,-0.002770,0.004233,0.004233,2025-01-27 03:15:00-05:00,2025-01-27 16:45:00-05:00,2025-01-27 03:15:00-05:00,2025-01-27 16:45:00-05:00
2025-01-28 02:45:00-05:00,40.398126,0.007345,True,-20.791144,-22.058201,0.0,1.0,0.0,1.0,0.004202,0.004202,-0.001065,-0.002750,-0.001065,0.000465,2025-01-28 03:00:00-05:00,2025-01-28 16:45:00-05:00,2025-01-28 03:00:00-05:00,2025-01-28 06:45:00-05:00
2025-01-29 05:15:00-05:00,31.889480,0.005160,NaN,-28.512100,-59.503742,0.0,1.0,0.0,1.0,0.004220,0.004220,-0.000580,-0.002762,-0.000580,0.003025,2025-01-29 05:30:00-05:00,2025-01-29 16:45:00-05:00,2025-01-29 05:30:00-05:00,2025-01-29 05:30:00-05:00
2025-02-05 15:15:00-05:00,44.818567,0.008640,NaN,-29.221558,-28.719069,0.0,1.0,0.0,1.0,0.004115,0.004115,-0.000540,-0.002693,0.000090,0.000090,2025-02-05 15:30:00-05:00,2025-02-05 16:45:00-05:00,2025-02-05 15:30:00-05:00,2025-02-05 16:45:00-05:00
2025-02-11 02:15:00-05:00,43.729756,0.002620,NaN,-13.360218,2.564659,0.0,1.0,1.0,0.0,0.004298,0.004298,-0.000710,-0.002813,-0.000710,0.004298,2025-02-11 02:30:00-05:00,2025-02-11 16:45:00-05:00,2025-02-11 02:30:00-05:00,2025-02-11 02:30:00-05:00
2025-02-11 03:00:00-05:00,41.338970,0.003835,NaN,-16.260205,-25.505032,1.0,0.0,1.0,0.0,0.004298,0.004298,-0.000820,-0.002813,0.004298,0.004298,2025-02-11 03:15:00-05:00,2025-02-11 16:45:00-05:00,2025-02-11 03:15:00-05:00,2025-02-11 16:45:00-05:00
2025-02-19 11:30:00-05:00,39.661206,0.007015,NaN,-42.768825,-14.204636,0.0,1.0,0.0,1.0,0.004161,0.004161,-0.000760,-0.002723,-0.000760,0.000635,2025-02-19 11:45:00-05:00,2025-02-19 16:45:00-05:00,2025-02-19 11:45:00-05:00,2025-02-19 11:45:00-05:00
2025-02-20 08:00:00-05:00,52.992170,0.004085,NaN,10.878886,-12.623564,1.0,0.0,1.0,0.0,0.004039,0.004039,-0.001220,-0.002644,0.004039,0.004039,2025-02-20 08:15:00-05:00,2025-02-20 16:45:00-05:00,2025-02-20 08:15:00-05:00,2025-02-20 16:45:00-05:00
2025-02-25 02:15:00-05:00,46.317663,0.002325,NaN,12.025449,-10.677301,0.0,1.0,1.0,0.0,0.003853,0.003853,-0.000280,-0.002522,-0.000280,0.003853,2025-02-25 02:30:00-05:00,2025-02-25 16:45:00-05:00,2025-02-25 02:30:00-05:00,2025-02-25 02:30:00-05:00
2025-02-25 03:00:00-05:00,47.960534,0.003295,True,2.534877,-28.026001,0.0,1.0,1.0,0.0,0.003853,0.003853,-0.001635,-0.002522,-0.001635,0.003853,2025-02-25 03:15:00-05:00,2025-02-25 16:45:00-05:00,2025-02-25 03:15:00-05:00,2025-02-25 03:30:00-05:00
2025-02-28 01:30:00-05:00,34.734522,0.003750,NaN,-27.512003,-24.277358,0.0,1.0,1.0,0.0,0.003730,0.003730,-0.000200,-0.002441,-0.000200,0.003730,2025-02-28 01:45:00-05:00,2025-02-28 16:45:00-05:00,2025-02-28 01:45:00-05:00,2025-02-28 01:45:00-05:00
2025-02-28 13:30:00-05:00,39.556057,0.005885,NaN,-28.902357,-52.118588,0.0,1.0,0.0,1.0,0.003730,0.003730,-0.000725,-0.002441,-0.000725,0.000290,2025-02-28 13:45:00-05:00,2025-02-28 16:45:00-05:00,2025-02-28 13:45:00-05:00,2025-02-28 13:45:00-05:00
2025-02-28 14:00:00-05:00,36.739485,0.006250,NaN,-31.291757,-60.459511,0.0,1.0,0.0,1.0,0.003730,0.003730,-0.000470,-0.002441,0.001240,0.001240,2025-02-28 14:15:00-05:00,2025-02-28 16:45:00-05:00,2025-02-28 14:15:00-05:00,2025-02-28 16:45:00-05:00
2025-03-03 02:15:00-05:00,41.981060,0.003290,NaN,-9.288024,-16.205185,0.0,1.0,1.0,0.0,0.003703,0.003703,-0.000105,-0.002423,-0.000105,0.003703,2025-03-03 02:30:00-05:00,2025-03-03 16:45:00-05:00,2025-03-03 02:30:00-05:00,2025-03-03 02:30:00-05:00
2025-03-05 08:15:00-05:00,50.264005,0.008665,NaN,25.989234,-50.750446,1.0,0.0,1.0,0.0,0.003638,0.003638,-0.001310,-0.002381,0.003638,0.003638,2025-03-05 08:30:00-05:00,2025-03-05 16:45:00-05:00,2025-03-05 08:30:00-05:00,2025-03-05 16:45:00-05:00
2025-03-10 04:15:00-04:00,32.167076,0.007000,True,-43.703246,-49.170150,0.0,1.0,1.0,0.0,0.003580,0.003580,-0.000930,-0.002343,-0.000930,0.003580,2025-03-10 04:30:00-04:00,2025-03-10 14:15:00-04:00,2025-03-10 04:30:00-04:00,2025-03-10 04:45:00-04:00
2025-03-10 05:00:00-04:00,30.431554,0.007150,NaN,-51.491084,-50.845818,1.0,0.0,1.0,0.0,0.003580,0.003580,-0.000690,-0.002343,0.003580,0.003580,2025-03-10 05:15:00-04:00,2025-03-10 16:45:00-04:00,2025-03-10 05:15:00-04:00,2025-03-10 14:00:00-04:00
2025-03-11 01:45:00-04:00,40.648637,0.002575,NaN,-3.606059,-25.065884,0.0,1.0,1.0,0.0,0.003564,0.003564,-0.000210,-0.002333,-0.000210,0.003564,2025-03-11 02:00:00-04:00,2025-03-11 16:45:00-04:00,2025-03-11 02:00:00-04:00,2025-03-11 02:00:00-04:00
2025-03-12 03:00:00-04:00,40.790388,0.004320,NaN,-31.487469,-29.266997,1.0,0.0,1.0,0.0,0.003575,0.003575,-0.000675,-0.002339,0.003575,0.003575,2025-03-12 03:15:00-04:00,2025-03-12 16:45:00-04:00,2025-03-12 03:15:00-04:00,2025-03-12 16:45:00-04:00